/* Diagnostic — compléments POIDS LOURDS : mode 24 V pour tous les modules VL, multiplexage et moteur PL,
   contrôle de la VCR (prédominance, rupture, frein de parc, défaillance d’un circuit), tests faisceau des prises remorque.
   Sources : cours AGB 03 (VCR, harmonisation / prédominance 0 à 1 bar, réglage après échange, fonction rupture, commande par
   le frein de parc, défaillance d’un circuit 41 / 42, VRU 2,8 bar, conduites 8 bar maxi) ; AGA 01 (24 V : 28 à 29,5 V) ;
   WABCO 973 002 (contrôle VCR à prédominance : alimentation 7 à 8 bar, manomètres sur 41 / 42 / 2) ;
   brochages : ISO 1185 (24N) et ISO 3731 (24S) d’après Parts and Go, ISO 12098 d’après Tralert, ISO 7638 d’après Hella. */
(function () {
  var D = window.DIAG, M = D.MEASURES, P = D.MODULES.pl.steps;
  function mes(id, label, unit, min, max, note) { M[id] = { id: id, label: label, unit: unit, min: min, max: max, note: note || '' }; }
  function r1(n) { return String(Math.round(n * 10) / 10).replace('.', ','); }
  function end(v, title, html, dep) { var s = { type: 'end', v: v, title: title, html: html }; if (dep) s.dep = dep; return s; }
  function info(title, html, bouton, next) { return { type: 'info', title: title, html: html, bouton: bouton, next: next }; }

  /* ---------- Mode 24 V : plages de tension adaptées (min, max, note, libellé) ---------- */
  D.V24 = {
    ubat: [24.8, 25.8, 'Deux batteries 12 V en série chargées : ≈ 25 V. Mesure aussi chaque batterie séparément (écart < 0,3 V).', 'Tension 24 V (deux batteries en série), moteur arrêté'],
    u_alim: [23, 29.5, 'Réseau 24 V : au moins 23 V (≈ 25 V moteur arrêté, ≈ 28 V moteur tournant).', 'Alimentation du calculateur (+BAT ou +APC 24 V au connecteur)'],
    u_ev_plus: [23, 29.5, 'Réseau 24 V : tension batterie ; le calculateur pilote souvent la masse en RCO.', 'Alimentation + de l’électrovanne en 24 V (contact mis)'],
    u_12: [22, 29.5, 'Réseau 24 V : tension batterie par relais.', 'Tension d’alimentation 24 V au connecteur (contact mis ou moteur tournant)'],
    u_chg: [28, 29.5, 'Cours AGA 01 : régulation d’un circuit 24 V entre 28 et 29,5 V.', 'Tension de charge 24 V, ≈ 2 000 tr/min, sans consommateurs'],
    u_chg_c: [26.5, 29.5, 'Valeur type 24 V : reste au-dessus d’environ 26,5 V.', 'Tension de charge 24 V, avec consommateurs (feux, ventilation…)'],
    u_crank: [19, Infinity, 'Valeur type 24 V : ≈ 19 V mini pendant le démarrage.', 'Tension 24 V pendant le démarrage'],
    u_50: [16, Infinity, 'Valeur type 24 V : proche de la tension batterie pendant le démarrage (au moins 16 V).', 'Tension de commande du démarreur (borne 50) pendant l’action sur la clé']
  };

  /* ---------- Menu PL : accès aux contrôles VL en 24 V ---------- */
  function lk(mod, txt) { return '<a class="btn" href="#/run/' + mod + '/{vid}/24">' + txt + '</a>'; }
  P.start.choices = [['Freinage pneumatique', 'pl_frein'], ['Remorque : VCR, prédominance, rupture, prises électriques', 'pl_rem'], ['Électricité 24 V : batteries, charge, démarrage', 'pl_24'], ['Multiplexage J1939, calculateurs', 'pl_can'], ['Moteur, injection, antipollution, capteurs', 'pl_mot'], ['Suspension pneumatique', 'pl_susp'], ['Prises de remorque : tests du faisceau', 'pr_type'], ['🆘 Dépannage d’urgence PL', 'pl_urg']];
  P.pl_mot = info('Moteur PL : mêmes contrôles que le VL, en 24 V', '<p>Le diagnostic moteur d’un PL suit <b>exactement la même démarche</b> que le VL. Ces boutons lancent le module en <b>mode 24 V</b> (tensions adaptées ; capteurs toujours en 5 V) :</p><div class="row-actions">' +
    lk('cr', '⛽ Common rail : basse / haute pression, injecteurs, suralimentation') + lk('anti', '🌫️ Antipollution : EGR, FAP, SCR / AdBlue') + lk('meca', '⚙️ Mécanique : préchauffage, refroidissement, huile, compression') + lk('capteurs', '📡 Capteurs : alimentations et signaux') + lk('mux', '🔌 Multiplexage : réseau, calculateur, capteurs, actionneurs') + lk('charge', '🔋 Batteries, charge et démarrage') + '</div>' +
    '<ul><li>Systèmes PL : common rail, <b>injecteurs-pompes</b> ou pompes unitaires (≈ 1 800 à 2 400 bar, cours GD 22), anciennes <b>pompes en ligne</b> (alimentation 1 à 2,5 bar).</li><li>SCR / AdBlue : conditions d’activation du cours (T° moteur > 40 °C, T° cata > 180 °C, régime > 400 tr/min, couple > 5 %).</li><li>Frein moteur, ralentisseur, boîte robotisée : défauts et apprentissages avec l’outil constructeur PL.</li><li>Ne jamais brancher un appareil 12 V (lampe, testeur, booster) sur le 24 V.</li></ul>', 'Terminer ici', 'end_mot');
  P.end_24_ok.html += '<div class="row-actions">' + lk('charge', '🔋 Poursuivre avec le module Batterie, charge et démarrage en 24 V') + '</div>';
  P.end_bat24.html += '<div class="row-actions">' + lk('charge', '🔋 Test détaillé en 24 V') + '</div>';
  P.end_alt24.html += '<div class="row-actions">' + lk('charge', '🔋 Chutes de tension et ondulation en 24 V') + '</div>';

  /* ---------- Multiplexage PL ---------- */
  mes('u_d24', 'Prise de diagnostic : tension + batterie → masse (ex. prise 9 broches : B → A)', 'V', 22, 29.5, 'La prise de diagnostic est alimentée en 24 V : sans alimentation, l’outil ne communique pas.');
  P.pl_can = { type: 'measure', title: 'Multiplexage PL : prise de diagnostic et réseau J1939', why: '<p><b>SAE J1939</b> : CAN haute vitesse à <b>250 kbit/s</b> (souvent 500 kbit/s sur les récents), deux fils torsadés, <b>deux résistances de 120 Ω</b> → 60 Ω entre CAN H et CAN L. Les niveaux CAN sont les mêmes que sur un VL (≈ 2,5 V au repos) même en 24 V. Plusieurs réseaux (moteur / transmission, véhicule, freinage EBS, carrosserie) sont reliés par un <b>calculateur véhicule</b>.</p><p><b>Prise de diagnostic</b> : 16 broches type OBD sur les récents (brochage selon marque) ou ancienne prise ronde <b>9 broches</b> : A masse, B + batterie, C CAN H, D CAN L (à vérifier sur le schéma).</p>',
    how: '<ol><li>Contact mis : tension + batterie → masse à la prise.</li><li><b>Contact coupé</b>, calculateurs en veille : résistance CAN H – CAN L.</li><li>Contact mis : tension moyenne CAN H – masse et CAN L – masse.</li></ol>', measures: ['u_d24', 'r_can', 'u_ch', 'u_cl'],
    decide: function (m) {
      if (m('u_d24').st === 'bad') return { v: 'bad', msg: 'Prise de diagnostic non alimentée : fusible de la prise, fil, masse.', next: 'end_can' };
      var r = m('r_can').v;
      if (r > 100 && r < 140) return { v: 'bad', msg: 'Environ 120 Ω : une seule terminaison vue — fil CAN coupé entre la prise et une extrémité, ou calculateur de terminaison débranché.', next: 'pl_can_suite' };
      if (r >= 140) return { v: 'bad', msg: 'Résistance très élevée : prise non reliée au réseau (fil coupé, connecteur) ou mauvaises broches.', next: 'pl_can_suite' };
      if (r < 55) return { v: 'bad', msg: 'Résistance trop basse : court-circuit entre CAN H et CAN L ou terminaison en trop (calculateur de remplacement).', next: 'pl_can_suite' };
      if (m('u_ch').st === 'bad' || m('u_cl').st === 'bad') return { v: 'bad', msg: 'Tensions CAN anormales : court-circuit d’un fil à la masse ou au +, ou calculateur qui bloque le réseau (débrancher un par un).', next: 'pl_can_suite' };
      return { v: 'ok', msg: 'Prise alimentée et réseau correct à la prise : localise le calculateur muet avec l’outil constructeur.', next: 'pl_can_suite' }; } };
  P.pl_can_suite = info('Suite du diagnostic multiplexé', '<p>Pour un calculateur précis (alimentation, masse, terminaison, capteurs et actionneurs), utilise le module Multiplexage en mode 24 V :</p><div class="row-actions">' + lk('mux', '🔌 Multiplexage en 24 V') + lk('capteurs', '📡 Capteurs en 24 V') + '</div><p class="small">Liaison <b>tracteur – remorque</b> (EBS) : CAN ISO 11992 sur les broches 6 et 7 de la prise ISO 7638 — voir « Prises de remorque ».</p>', 'Conclusion', 'end_can');

  /* ---------- Remorque : VCR et prédominance ---------- */
  mes('p_auto', 'Tête d’accouplement AUTOMATIQUE (rouge) : pression, freins desserrés', 'bar', 6.5, 8, 'Valeur type ≈ 7 à 8 bar (cours AGB 03 : 8 bar maxi dans la conduite).');
  mes('p_pil', 'Pression de PILOTAGE de la VCR (prise d’épreuve du circuit qui la pilote), freinage partiel stabilisé', 'bar', null, null);
  mes('p_dir', 'Tête d’accouplement DIRECTE (jaune) : pression au même moment', 'bar', null, null);
  mes('pred_att', 'Prédominance attendue (doc constructeur / plaque), en bar', 'bar', null, null);
  mes('p_dir_max', 'Tête d’accouplement DIRECTE (jaune) : pression, freinage à fond', 'bar', 6.5, 8, 'Valeur type ; cours AGB 03 : 8 bar maxi dans la conduite directe.');
  P.pl_rem = { type: 'choice', title: 'Remorque : que veux-tu contrôler ?', why: '<p>Deux conduites : <b>automatique</b> (main <b>rouge</b> : alimente la remorque en air) et <b>directe</b> (main <b>jaune</b> : transmet l’ordre de freinage). La <b>VCR</b> commande la remorque à partir des circuits AV et AR du tracteur (et du frein de parc), avec une <b>prédominance / harmonisation</b> réglable de 0 à 1 bar pour que la remorque freine un peu plus que le tracteur. La <b>VRU</b> de la remorque freine automatiquement si la conduite automatique chute ; ses freins restent serrés jusqu’à <b>2,8 bar</b>.</p>',
    choices: [['Contrôle complet de la VCR (prédominance, rupture, frein de parc, défaillance d’un circuit)', 'vcr'], ['La remorque ne se desserre pas', 'end_vru'], ['La remorque freine mal ou l’ensemble se met en portefeuille', 'vcr'], ['Freinage d’urgence de la remorque intempestif', 'end_rupture'], ['Prises électriques : tests du faisceau', 'pr_type']] };
  P.pl_frein.choices = [['Pression d’air faible, remplissage long, fuite', 'pl_air'], ['Frein de parc : ne se desserre pas ou inefficace', 'pl_parc'], ['Remorque : VCR, prédominance, rupture', 'pl_rem'], ['Analyser un passage au banc de freinage', 'pl_banc']];
  P.vcr = { type: 'measure', title: 'VCR : pression automatique et prédominance', why: '<p>La <b>prédominance</b> (ou harmonisation) est la différence entre la pression envoyée à la remorque (tête <b>jaune</b>) et la pression qui pilote la VCR. Cours AGB 03 : réglable de <b>0 à 1 bar</b> ; <b>après un échange de VCR, il est impératif de contrôler et régler</b> ce dispositif (la même VCR se monte sur des véhicules aux réglages différents). Le réglage se fait par une vis, interne ou externe selon le type.</p>',
    how: '<ol><li>Réservoirs pleins (pression de coupure), moteur arrêté, véhicule calé.</li><li>Sans remorque, les têtes arrière ont un clapet : branche des <b>têtes d’accouplement d’essai</b> (mains factices) avec manomètre sur la rouge et sur la jaune.</li><li>Manomètre sur la <b>prise d’épreuve</b> du circuit qui pilote la VCR (circuit AR / pression délivrée aux vases AR).</li><li>Lis la tête rouge freins desserrés.</li><li>Freine <b>faiblement</b> et stabilise (≈ 1 bar de pilotage, ou la valeur de la doc) : relève pilotage et tête jaune.</li><li>Freine à fond : relève la tête jaune.</li></ol>', measures: ['p_auto', 'p_pil', 'p_dir', 'pred_att', 'p_dir_max'],
    decide: function (m) {
      if (m('p_auto').st === 'bad') return { v: 'bad', msg: 'Pression à la tête rouge hors plage (' + r1(m('p_auto').v) + ' bar) : ' + (m('p_auto').dir === 'low' ? 'alimentation de la VCR, valve de protection, détendeur, fuite de la conduite automatique.' : 'détendeur / limiteur de la conduite automatique.'), next: 'end_vcr_auto' };
      if (m('p_dir').v <= 0) return { v: 'bad', msg: 'Aucune pression à la tête jaune en freinant : pilotage de la VCR absent ou VCR bloquée.', next: 'end_vcr_pred' };
      var d = m('p_dir').v - m('p_pil').v, e = d - m('pred_att').v;
      var txt = 'Prédominance mesurée : ' + r1(d) + ' bar (attendue ' + r1(m('pred_att').v) + ' bar, écart ' + r1(e) + ' bar).';
      if (Math.abs(e) > 0.3) return { v: 'bad', msg: txt + (e < 0 ? ' La remorque freine moins que prévu : risque de mise en portefeuille.' : ' La remorque freine trop tôt / trop fort : usure et blocage des roues de la remorque.') + ' Règle la prédominance.', next: 'end_vcr_pred' };
      if (m('p_dir_max').st === 'bad') return { v: 'bad', msg: txt + ' Mais la tête jaune n’atteint pas la bonne pression à fond (' + r1(m('p_dir_max').v) + ' bar) : VCR, alimentation ou fuite.', next: 'end_vcr_pred' };
      return { v: 'ok', msg: txt + ' Conforme (tolérance type ± 0,3 bar ; la doc constructeur prime). On teste la fonction rupture.', next: 'vcr_rup' }; } };
  P.vcr_rup = { type: 'choice', title: 'Test de la fonction rupture', why: '<p>Cours AGB 03 : la fonction rupture s’active quand <b>deux conditions</b> sont réunies — le conducteur <b>freine</b> et il y a une <b>fuite sur la conduite directe</b>. La VCR calibre alors le passage de l’air vers la conduite automatique et la met en communication avec la directe : la pression de la conduite automatique <b>chute</b>, ce qui déclenche le <b>freinage d’urgence</b> de la remorque par la VRU.</p>',
    choices: [['Tête jaune laissée ouverte à l’air, freinage à fond : la pression de la tête rouge chute rapidement', 'vcr_parc'], ['La pression de la tête rouge ne chute pas (ou très lentement)', 'end_vcr_rup']] };
  P.vcr_parc = { type: 'choice', title: 'Freinage de la remorque par le frein de parc', why: '<p>Cours AGB 03 : quand on serre le frein de parc (mise à l’air progressive des cylindres à ressort), la VCR (orifice 43) <b>freine la remorque</b>. Pour un ensemble, le frein de parc doit tenir une pente de 12 % <b>avec le tracteur seul freiné</b> : beaucoup de robinets ont une position <b>contrôle</b> qui desserre la remorque pour le vérifier.</p><p>Test : têtes d’essai en place, serre le frein de parc et regarde la tête jaune ; puis position contrôle (si équipé).</p>',
    choices: [['La pression monte à la tête jaune (et retombe en position contrôle)', 'vcr_def'], ['Aucune pression à la tête jaune au serrage du frein de parc', 'end_vcr_parc'], ['La pression ne retombe pas en position contrôle', 'end_vcr_parc']] };
  P.vcr_def = { type: 'choice', title: 'Défaillance d’un circuit de freinage', why: '<p>La VCR est pilotée par <b>deux circuits</b> (41 et 42). Cours AGB 03 : si l’un est défaillant, l’autre suffit à freiner la remorque (sans l’harmonisation si c’est le circuit 41 qui manque : pression un peu plus faible).</p><p>Test : vide le réservoir d’<b>un</b> circuit (AV ou AR) par sa purge, freine : la tête jaune doit encore recevoir de la pression. Recommence avec l’autre circuit (après remplissage).</p>',
    choices: [['La remorque est freinée avec chacun des deux circuits seuls', 'end_vcr_ok'], ['Pas de pression à la tête jaune avec un seul circuit', 'end_vcr_def']] };
  P.end_vcr_ok = end('ok', 'VCR conforme', '<p>Prédominance, fonction rupture, commande par le frein de parc et secours d’un circuit conformes. Contrôle aussi l’<b>étanchéité</b> de la VCR (eau savonneuse sur les échappements, freins serrés et desserrés) et le freinage de l’ensemble au <b>banc</b>.</p>');
  P.end_vcr_auto = end('bad', 'Conduite automatique', '<p>Contrôle l’alimentation de la VCR (orifice 11), la valve de protection du circuit remorque, le détendeur, les fuites (tête rouge, flexible, joint de la main). Refais le contrôle complet après réparation.</p>');
  P.end_vcr_pred = end('bad', 'Prédominance / VCR', '<p>Règle la prédominance par la <b>vis de réglage</b> (interne ou externe selon le type de VCR) à la valeur constructeur, puis refais la mesure. Si le réglage est impossible ou si la VCR fuit : <b>échange de la VCR</b>, puis <b>contrôle et réglage obligatoires</b> de la prédominance (cours AGB 03).</p>');
  P.end_vcr_rup = end('bad', 'Fonction rupture inopérante', '<p>La VCR ne déclenche pas le freinage d’urgence de la remorque en cas de fuite de la conduite directe : <b>VCR à remplacer</b> (pièce de sécurité), puis contrôle complet.</p>');
  P.end_vcr_parc = end('bad', 'Commande de la remorque par le frein de parc', '<p>Contrôle le pilotage 43 de la VCR depuis le robinet de frein de parc (canalisation, raccord), le robinet (position contrôle), puis la VCR.</p>');
  P.end_vcr_def = end('bad', 'Secours d’un circuit de la VCR', '<p>Contrôle les deux pilotages (41 et 42) jusqu’à la VCR (canalisations, double valve d’arrêt si montée), puis la VCR (diaphragme / piston de secours).</p>');

  /* ---------- Prises de remorque ---------- */
  var PIN = 'Valeur type : tension batterie moins une petite chute (au moins ≈ 22 V en 24 V).';
  function pin(id, txt) { mes(id, txt + ' — tension, fonction activée', 'V', 22, 29.5, PIN); }
  function masse(id, txt) { mes(id, 'Chute de tension de la masse : ' + txt + ' → borne – batterie (feux allumés)', 'V', 0, 0.5, 'Valeur type : moins de 0,5 V.'); }
  pin('n_2', 'Broche 2 : feux de position gauche'); pin('n_3', 'Broche 3 : clignotant gauche (valeur haute)'); pin('n_4', 'Broche 4 : feux stop'); pin('n_5', 'Broche 5 : clignotant droit (valeur haute)'); pin('n_6', 'Broche 6 : feux de position droite'); masse('n_m', 'broche 1');
  pin('s_3', 'Broche 3 : feu de recul'); pin('s_4', 'Broche 4 : + 24 V permanent'); pin('s_6', 'Broche 6 : + 24 V après contact'); pin('s_7', 'Broche 7 : feu antibrouillard'); masse('s_m', 'broche 1');
  pin('q_1', 'Broche 1 : clignotant gauche (valeur haute)'); pin('q_2', 'Broche 2 : clignotant droit (valeur haute)'); pin('q_3', 'Broche 3 : feu antibrouillard'); pin('q_5', 'Broche 5 : feux de position / gabarit / plaque gauche'); pin('q_6', 'Broche 6 : feux de position / gabarit / plaque droite'); pin('q_7', 'Broche 7 : feux stop'); pin('q_8', 'Broche 8 : feu de recul'); pin('q_9', 'Broche 9 : + 24 V permanent'); masse('q_m', 'broche 4');
  pin('e_1', 'Broche 1 : + 24 V électrovannes (permanent)'); pin('e_2', 'Broche 2 : + 24 V électronique (après contact)'); masse('e_m3', 'broche 3 (masse électronique)'); masse('e_m4', 'broche 4 (masse électrovannes)');
  function prStep(title, table, ms) { return { type: 'measure', title: title, why: table + '<p class="small">Brochage normalisé à vérifier sur le schéma du véhicule (des broches « spécifiques » varient selon le constructeur).</p>',
    how: '<ol><li>Contact mis, remorque débranchée, <b>testeur de prise 24 V</b> (voyants) ou voltmètre entre chaque broche et la broche de masse.</li><li>Active chaque fonction l’une après l’autre (feux, clignotants, stop, recul…). Clignotants au voltmètre : lis la valeur haute.</li><li>Masse : voltmètre entre la broche de masse et la borne – batterie, feux allumés.</li><li>Regarde aussi : broches oxydées ou écartées, spirale et fiche abîmées, couvercle et joint.</li></ol>', measures: ms,
    decide: function (m) { var bad = ms.filter(function (k) { return m(k).st === 'bad'; });
      if (!bad.length) return { v: 'ok', msg: 'Toutes les fonctions arrivent à la prise côté tracteur. Si la remorque a un défaut, contrôle son côté.', next: 'pr_rem' };
      var pins = bad.filter(function (k) { return D.MEASURES[k].max > 1; }).map(function (k) { return D.MEASURES[k].label.split(' — ')[0]; }), mm = bad.filter(function (k) { return D.MEASURES[k].max <= 1; });
      var msg = (pins.length ? 'Pas de tension correcte : ' + pins.join(' ; ') + '. Contrôle le fusible, le relais ou le module de remorque, la commande (commodo, calculateur véhicule), le fil et la broche. ' : '') + (mm.length ? 'Masse résistante : fil de masse de la prise, point de masse châssis.' : '');
      return { v: 'bad', msg: msg, next: 'end_pr' }; } }; }
  function tbl(rows) { return '<div class="tw"><table><tr><th>Broche</th><th>Fonction</th></tr>' + rows.map(function (r) { return '<tr><td>' + r[0] + '</td><td>' + r[1] + '</td></tr>'; }).join('') + '</table></div>'; }
  P.pr_type = { type: 'choice', title: 'Quelle prise de remorque ?', why: '<ul><li><b>24N</b> (ISO 1185, couvercle noir) : éclairage de base.</li><li><b>24S</b> (ISO 3731, couvercle blanc / gris) : fonctions auxiliaires (recul, alimentations, antibrouillard).</li><li><b>15 broches</b> (ISO 12098) : remplace 24N + 24S sur les véhicules récents.</li><li><b>ISO 7638</b> (7 broches) : alimentation et communication de l’<b>ABS / EBS</b> de la remorque. L’éclairage reste sur 24N / 24S ou 15 broches.</li></ul><p>Toujours tester <b>côté tracteur</b> d’abord, puis <b>côté remorque</b>.</p>',
    choices: [['24N (ISO 1185) — éclairage', 'pr_n'], ['24S (ISO 3731) — auxiliaires', 'pr_s'], ['15 broches (ISO 12098)', 'pr_q'], ['ISO 7638 — ABS / EBS de la remorque', 'pr_e'], ['Côté remorque : feux ou EBS de la remorque en défaut', 'pr_rem']] };
  P.pr_n = prStep('Prise 24N (ISO 1185)', tbl([['1', 'Masse'], ['2', 'Feux de position gauche (+ plaque)'], ['3', 'Clignotant gauche'], ['4', 'Feux stop'], ['5', 'Clignotant droit'], ['6', 'Feux de position droite'], ['7', 'Freinage / commande (selon véhicule)']]), ['n_2', 'n_3', 'n_4', 'n_5', 'n_6', 'n_m']);
  P.pr_s = prStep('Prise 24S (ISO 3731)', tbl([['1', 'Masse'], ['2', 'Fonction spécifique (selon constructeur)'], ['3', 'Feu de recul'], ['4', '+ 24 V permanent'], ['5', 'Commande / fonction spécifique (selon constructeur)'], ['6', '+ 24 V après contact'], ['7', 'Feu antibrouillard']]), ['s_3', 's_4', 's_6', 's_7', 's_m']);
  P.pr_q = prStep('Prise 15 broches (ISO 12098)', tbl([['1', 'Clignotant gauche'], ['2', 'Clignotant droit'], ['3', 'Feu antibrouillard'], ['4', 'Masse'], ['5', 'Feux de position, gabarit, plaque gauche'], ['6', 'Feux de position, gabarit, plaque droite'], ['7', 'Feux stop'], ['8', 'Feu de recul'], ['9', '+ 24 V permanent'], ['10', 'Capteur d’usure des garnitures'], ['11', 'Témoin de frein à ressort'], ['12', 'Essieu relevable'], ['13', 'Masse des lignes de données'], ['14', 'CAN H'], ['15', 'CAN L']]), ['q_1', 'q_2', 'q_3', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_m']);
  P.pr_e = prStep('Prise ISO 7638 (ABS / EBS remorque)', tbl([['1', '+ 24 V électrovannes (permanent, gros fil 4 mm²)'], ['2', '+ 24 V électronique (après contact, 1,5 mm²)'], ['3', 'Masse électronique'], ['4', 'Masse électrovannes (4 mm²)'], ['5', 'Voyant d’alerte'], ['6', 'CAN H (ISO 11992, liaison tracteur – remorque)'], ['7', 'CAN L (ISO 11992)']]) + '<p class="small">Version 5 broches (sans CAN) pour l’ABS seul. Sans cette prise branchée, l’ABS / EBS de la remorque ne fonctionne pas (freinage pneumatique de base conservé) et le voyant s’allume.</p>', ['e_1', 'e_2', 'e_m3', 'e_m4']);
  P.pr_rem = info('Côté remorque', '<ol><li>Branche la remorque sur un <b>boîtier de simulation / testeur 24 V</b> (ou sur un tracteur connu bon) et active chaque fonction.</li><li>Contrôle la fiche, la <b>spirale</b>, les boîtiers de dérivation, les <b>masses</b> des feux (souvent par le châssis de la remorque), les feux (ampoules ou blocs LED).</li><li><b>EBS remorque</b> : lecture des défauts à la valise par la prise ISO 7638 (ou la prise de diagnostic de la remorque) ; voyant EBS remorque au tableau de bord du tracteur.</li><li>Freinage pneumatique de la remorque : VRU, valve de desserrage, correcteur, cylindres ; passage au banc.</li></ol>', 'Conclusion', 'end_pr_ok');
  P.end_pr = end('bad', 'Faisceau de la prise remorque', '<p>Répare la fonction en défaut : fusible / relais / module de remorque, commande, fil, <b>broche</b> (nettoyage, resserrage, remplacement de la prise). Refais le test de <b>toutes</b> les broches, puis un essai avec la remorque.</p>', '<p>Feu stop ou clignotants de remorque absents : ne pas rouler de nuit ou sur route sans signalisation de remplacement réglementaire.</p>');
  P.end_pr_ok = end('ok', 'Prises et faisceau remorque', '<p>Côté tracteur conforme : le défaut est sur la remorque (voir les contrôles ci-dessus). Après réparation, essai de toutes les fonctions remorque attelée.</p>');
})();
