/* Diagnostic — modules TURBO, MÉLANGE EAU / HUILE (joint de culasse) et FUMÉES (essence / diesel).
   Valeurs TYPES (la valeur constructeur prime). Turbo : jeu axial quasi nul, jeu radial léger normal (paliers lisses),
   la roue ne doit jamais toucher le carter ; test d’étanchéité de l’admission à 2 bar maxi ; la plupart des casses viennent
   de la lubrification ou d’un corps étranger. Eau / huile : test CO₂, mise sous pression, isolement de l’échangeur. */
(function () {
  var D = window.DIAG, M = D.MEASURES;
  function mes(id, label, unit, min, max, note) { M[id] = { id: id, label: label, unit: unit, min: min, max: max, note: note || '' }; }
  function r1(n) { return String(Math.round(n * 10) / 10).replace('.', ','); }
  function end(v, title, html, dep) { var s = { type: 'end', v: v, title: title, html: html }; if (dep) s.dep = dep; return s; }
  function info(title, html, bouton, next) { return { type: 'info', title: title, html: html, bouton: bouton, next: next }; }
  function ch(title, why, choices) { return { type: 'choice', title: title, why: why, choices: choices }; }
  function lk(mod, txt) { return '<a class="btn" href="#/run/' + mod + '/{vid}">' + txt + '</a>'; }
  function lks() { return '<div class="row-actions">' + Array.prototype.slice.call(arguments).join('') + '</div>'; }

  /* ========================= TURBO ========================= */
  mes('ps_arret', 'Pression de suralimentation lue à la valise, moteur arrêté, contact mis', 'mbar', 950, 1050, 'Capteur en pression absolue : il doit lire la pression atmosphérique (≈ 1 013 mbar au niveau de la mer, moins en altitude). Si ta valise affiche en relatif, elle doit lire ≈ 0 : entre alors 1013 + la valeur lue.');
  mes('dep_pav', 'Dépression de la pompe à vide (vacuomètre, moteur au ralenti)', 'bar', 0.6, 0.95, 'Valeur type : ≈ 0,6 à 0,9 bar de dépression. Elle commande la capsule du turbo (et souvent le servofrein et l’EGR).');
  var T = {};
  T.start = ch('Turbo : quel symptôme ?', '<p>Le turbo récupère l’énergie des gaz d’échappement (<b>turbine</b>) pour comprimer l’air d’admission (<b>compresseur</b>). La pression est régulée par une <b>wastegate</b> (soupape de décharge) ou une <b>géométrie variable</b>, commandées par une capsule pneumatique (électrovanne en RCO + pompe à vide) ou un actionneur électrique. L’axe tourne sur des paliers <b>lubrifiés par l’huile moteur</b> : la plupart des casses viennent de la <b>lubrification</b> ou d’un <b>corps étranger</b>. Avant d’accuser le turbo, on contrôle tout ce qui l’entoure.</p>',
    [['Manque de puissance, mode dégradé, défaut « sous-suralimentation »', 't_ps'], ['Sifflement anormal', 't_fuite'], ['Fumée bleue, huile dans l’admission ou l’échangeur', 't_huile'], ['À-coups, défaut « sur-suralimentation »', 't_act'], ['Bruit métallique, frottement', 't_meca'], ['Turbo cassé : que vérifier avant d’en remonter un ?', 't_cause'], ['🆘 Moteur diesel qui s’emballe', 'end_t_embal']]);
  T.t_ps = { type: 'measure', title: 'Pression de suralimentation', why: '<p>On vérifie d’abord que le <b>capteur</b> dit vrai (moteur arrêté, il doit lire la pression atmosphérique), puis on compare la pression <b>demandée</b> et la pression <b>mesurée</b> en charge.</p>',
    how: '<ol><li>Contact mis, moteur arrêté : pression lue à la valise.</li><li>Essai en charge (3ᵉ rapport, pied à fond de 1 500 à 3 500 tr/min) : pression demandée et mesurée au même moment (valise en enregistrement).</li></ol>', measures: ['ps_arret', 'ps_cons', 'ps_mes'],
    decide: function (m) { if (m('ps_arret').st === 'bad') return { v: 'bad', msg: 'Le capteur ne lit pas la pression atmosphérique moteur arrêté (' + Math.round(m('ps_arret').v) + ' mbar) : capteur ou son circuit (5 V, masse, signal).', next: 'end_t_capt' };
      var c = m('ps_cons').v, x = m('ps_mes').v, e = c ? (x - c) / c * 100 : 0;
      if (e < -10) return { v: 'bad', msg: 'Sous-suralimentation (' + r1(e) + ' %) : on cherche d’abord une fuite d’air.', next: 't_fuite' };
      if (e > 10) return { v: 'bad', msg: 'Sur-suralimentation (+' + r1(e) + ' %) : commande du turbo (géométrie ou wastegate grippée, électrovanne, actionneur).', next: 't_act' };
      return { v: 'ok', msg: 'Suralimentation conforme (écart ' + r1(e) + ' %) : le manque de puissance vient d’ailleurs (injection, débitmètre, EGR, FAP).', next: 'end_t_ok_ps' }; } };
  T.t_fuite = ch('Étanchéité du circuit d’air', '<p>Une fuite entre le turbo et le moteur fait perdre de la pression (sifflement aigu en charge, fumée noire sur diesel). Une fuite <b>côté échappement avant la turbine</b> (collecteur fissuré, joint) enlève de l’énergie au turbo (bruit de « claquement » à froid).</p><p><b>Test</b> : obturer le circuit (adaptateur à la place du filtre à air ou de la durite de sortie), le mettre sous air comprimé <b>détendu à 2 bar maxi</b> (sans dépasser la pression de suralimentation maxi), écouter et pulvériser de l’eau savonneuse : durites (fissures, colliers), échangeur (traces d’huile, fuite dans les ailettes), raccords, collecteur d’admission.</p>',
    [['Fuite trouvée', 'end_t_fuite'], ['Circuit étanche', 't_act']]);
  T.t_act = ch('Quelle commande de turbo ?', '<p>Regarde sur le turbo : une <b>capsule</b> avec une durite (commande pneumatique par électrovanne et pompe à vide) ou un <b>actionneur électrique</b> avec un connecteur.</p>', [['Capsule pneumatique', 't_cmd'], ['Actionneur électrique', 't_act_el']]);
  T.t_cmd = { type: 'measure', title: 'Commande pneumatique : dépression', why: '<p>La <b>pompe à vide</b> fournit la dépression ; l’<b>électrovanne</b> (pilotée en RCO par le calculateur) la dose vers la capsule, qui déplace la géométrie variable ou la wastegate.</p>', how: '<p>Vacuomètre en T sur la durite d’arrivée de l’électrovanne, moteur au ralenti.</p>', measures: ['dep_pav'],
    decide: function (m) { if (m('dep_pav').st === 'bad' && m('dep_pav').dir === 'low') return { v: 'bad', msg: 'Dépression insuffisante : pompe à vide, durite fendue, clapet anti-retour.', next: 'end_t_pav' }; return { v: 'ok', msg: 'Dépression correcte : on contrôle la capsule, la tige et l’électrovanne.', next: 't_pneu' }; } };
  T.t_pneu = ch('Capsule, tige et électrovanne', '<ol><li><b>Tige</b> : moteur arrêté et froid, déplace-la à la main (ou avec une pompe à vide manuelle sur la capsule) : elle doit bouger <b>librement sur toute sa course</b> et revenir seule. Géométrie variable souvent <b>grippée par la calamine</b>.</li><li><b>Capsule</b> : pompe à vide manuelle, la dépression doit <b>tenir</b> (membrane étanche).</li><li><b>Électrovanne</b> : test actionneur à la valise, la dépression en sortie doit varier ; résistance, alimentation (module 🔌 → électrovanne RCO).</li></ol>',
    [['Tige ou géométrie grippée, course incomplète', 'end_t_vgt'], ['La capsule ne tient pas la dépression', 'end_t_caps'], ['L’électrovanne ne fait pas varier la dépression', 'end_t_ev'], ['Tout est bon', 't_meca']]);
  T.t_act_el = ch('Actionneur électrique', '<p>L’actionneur électrique contient un moteur et un capteur de position. À la valise : <b>test actionneur</b> et comparaison position demandée / position mesurée. Après remplacement du turbo ou de l’actionneur : <b>apprentissage des butées</b>.</p>',
    [['La position suit la consigne sur toute la course', 't_meca'], ['Ne suit pas, défaut de position ou de butée', 'end_t_elec']]);
  T.t_huile = ch('Huile côté admission ou échappement', '<p>Un <b>léger film d’huile</b> dans les durites est normal (vapeurs du reniflard). De l’huile <b>en quantité</b> (qui coule, flaque dans l’échangeur) ou une fumée bleue n’est pas normale. Le turbo n’a pas de vrai joint : des <b>segments</b> retiennent l’huile tant qu’elle <b>retourne librement au carter</b>. Retour gêné, pression dans le carter trop forte ou dépression trop forte à l’entrée du compresseur (filtre à air colmaté) = l’huile passe.</p>',
    [['Léger film gras seulement', 'end_t_film'], ['Huile en quantité ou fumée bleue', 't_retour']]);
  T.t_retour = ch('Pourquoi l’huile passe ?', '<ol><li><b>Tuyau de retour d’huile</b> écrasé, coudé, bouché (calamine), joint mal posé.</li><li><b>Pression dans le carter</b> (reniflard / recyclage des vapeurs bouché, usure segments moteur : trop de gaz de carter).</li><li><b>Filtre à air colmaté</b> ou entrée d’air obstruée.</li><li>Niveau d’huile trop haut (dilution par le gazole sur diesel à FAP).</li><li>Sinon : paliers du turbo usés (jeu).</li></ol>',
    [['Retour d’huile gêné ou reniflard bouché / pression carter forte', 'end_t_retour'], ['Filtre à air colmaté', 'end_t_filtre'], ['Niveau d’huile trop haut', 'end_t_niveau'], ['Tout est bon', 't_meca']]);
  T.t_meca = ch('État mécanique du turbo', '<p>Moteur arrêté et <b>froid</b>, durite d’entrée du compresseur déposée (et si possible côté turbine) :</p><ul><li>La roue tourne <b>librement</b> à la main, sans point dur ni frottement.</li><li><b>Jeu axial</b> (pousser / tirer l’axe) : <b>quasiment nul</b>.</li><li><b>Jeu radial</b> (monter / descendre) : un <b>léger jeu est normal</b> (paliers lisses, comblé par la pression d’huile en fonctionnement), mais la roue ne doit <b>jamais toucher le carter</b>.</li><li><b>Ailettes</b> intactes : ni impact, ni usure, ni bord replié (corps étranger).</li><li>Mesure précise au comparateur : valeurs du fabricant du turbo.</li></ul>',
    [['Roue qui touche, jeu axial sensible, ailettes abîmées, point dur', 't_cause'], ['Tout est bon', 'end_t_ok']]);
  T.t_cause = info('Avant de remplacer un turbo : trouver la cause', '<p>Un turbo neuf monté sans corriger la cause casse à nouveau. Vérifie :</p><ol><li><b>Lubrification</b> : niveau et qualité d’huile, vidanges trop espacées, <b>pression d’huile</b> (module ⚙️), <b>tuyau d’arrivée d’huile</b> obstrué par la calamine (à remplacer, pas à nettoyer), tuyau de retour.</li><li><b>Corps étranger</b> côté compresseur (filtre à air mal monté, débris) ou côté turbine (morceau de soupape, rondelle d’injecteur, débris du collecteur).</li><li><b>Température</b> : arrêts moteur à chaud sans ralenti (l’huile cuit dans les paliers).</li><li><b>Sur-régime</b> : commande déréglée, reprogrammation.</li><li><b>Contre-pression</b> : FAP ou catalyseur colmaté (module 🌫️).</li></ol>', 'Procédure de remplacement', 'end_t_remp');
  T.end_t_ok_ps = end('ok', 'Suralimentation conforme', '<p>Le turbo fournit la pression demandée. Cherche du côté de l’injection, du débitmètre, de l’EGR ou du FAP.</p>' + lks(lk('cr', '⛽ Common rail'), lk('anti', '🌫️ Antipollution')));
  T.end_t_capt = end('bad', 'Capteur de pression de suralimentation', '<p>Contrôle l’alimentation 5 V, la masse et le signal (module 📡 Capteurs → capteur de pression), le connecteur et la prise de pression (durite, encrassement).</p>' + lks(lk('capteurs', '📡 Capteurs')));
  T.end_t_fuite = end('bad', 'Fuite du circuit d’air', '<p>Remplace la durite ou le collier, l’échangeur s’il fuit (nettoyer l’huile), les joints. Refais le test d’étanchéité puis l’essai en charge.</p>', '<p>Durite déboîtée : la remettre et serrer le collier. Sinon rouler doucement en mode dégradé.</p>');
  T.end_t_pav = end('bad', 'Pompe à vide / durites', '<p>Contrôle les durites et le clapet, puis la pompe à vide (sur beaucoup de diesels, elle commande aussi le servofrein : pédale dure = même cause).</p>');
  T.end_t_vgt = end('bad', 'Géométrie variable / wastegate grippée', '<p>Décalaminage possible si ce n’est pas trop avancé (dépose, nettoyage), sinon remplacement du turbo. Cherche la cause de l’encrassement (usage urbain, EGR, injecteurs).</p>', '<p>Rouler doucement jusqu’à l’atelier (mode dégradé).</p>');
  T.end_t_caps = end('bad', 'Capsule du turbo', '<p>Remplace la capsule (ou le turbo si elle n’est pas vendue seule) ; règle la tige à la valeur constructeur.</p>');
  T.end_t_ev = end('bad', 'Électrovanne de commande du turbo', '<p>Contrôle électrique (résistance, + permanent, masse pilotée en RCO) avec le module 🔌, puis remplace l’électrovanne. Contrôle aussi les durites (inversées, fendues).</p>' + lks(lk('mux', '🔌 Multiplexage → électrovanne')));
  T.end_t_elec = end('bad', 'Actionneur électrique du turbo', '<p>Alimentation, masse, liaison avec le calculateur, puis actionneur ; <b>apprentissage des butées</b> après remplacement. Si la géométrie est grippée, l’actionneur force et tombe en défaut : contrôle la libre course.</p>');
  T.end_t_film = end('ok', 'Film d’huile normal', '<p>Un léger film gras vient des vapeurs du reniflard. Surveille la consommation d’huile ; nettoie l’échangeur à l’occasion.</p>');
  T.end_t_retour = end('bad', 'Retour d’huile / pression du carter', '<p>Remplace le tuyau de retour (et ses joints), débouche ou remplace le reniflard / décanteur d’huile. Si le moteur fait trop de gaz de carter (usure), le turbo n’est que la victime : compression (module ⚙️).</p>', '<p>Surveiller le niveau d’huile ; risque d’<b>emballement</b> sur diesel si l’huile est aspirée en quantité.</p>');
  T.end_t_filtre = end('bad', 'Filtre à air', '<p>Remplace le filtre, contrôle le boîtier et l’entrée d’air (obstruction). Nettoie l’huile de l’admission et de l’échangeur.</p>');
  T.end_t_niveau = end('bad', 'Niveau d’huile trop haut', '<p>Vidange au bon niveau. Sur diesel à FAP, un niveau qui <b>monte</b> = dilution par le gazole (régénérations interrompues) : l’huile sent le gazole. Voir le module 🌫️ (FAP).</p>');
  T.end_t_ok = end('ok', 'Turbo en bon état mécanique', '<p>Libre, sans jeu anormal ni impact. Cherche la cause du symptôme ailleurs (commande, fuite, capteur, moteur).</p>');
  T.end_t_remp = end('bad', 'Remplacement du turbo : procédure', '<ol><li>Corriger la <b>cause</b> (voir l’étape précédente).</li><li><b>Vidange</b> + filtre à huile neufs ; <b>tuyau d’arrivée d’huile neuf</b> et joints neufs ; retour contrôlé.</li><li>Nettoyer ou remplacer l’<b>échangeur</b> et les durites (huile, débris) ; filtre à air neuf.</li><li>Avant de brancher l’arrivée, <b>remplir le turbo d’huile propre</b> par l’orifice d’arrivée (amorçage).</li><li>Faire tourner au démarreur, injection coupée, jusqu’à l’extinction du voyant de pression d’huile.</li><li>Démarrer et laisser <b>au ralenti quelques minutes</b> sans accélérer ; contrôler les fuites.</li><li>Actionneur électrique : <b>apprentissage</b> ; effacer les défauts ; essai en charge avec pression demandée / mesurée.</li></ol>');
  T.end_t_embal = { type: 'end', v: 'bad', noApres: true, title: 'Moteur diesel qui s’emballe', html: '<p>Si le turbo casse, le moteur peut aspirer son <b>huile</b> et s’en servir comme carburant : il s’emballe, <b>couper le contact ne l’arrête pas</b>, beaucoup de fumée.</p><ol><li><b>Véhicule en roulant</b> : frein à fond, rapport <b>élevé</b> engagé, relâcher l’embrayage d’un coup pour <b>caler</b> le moteur.</li><li><b>À l’arrêt</b> : boucher l’entrée d’air avec un objet plat et rigide (jamais la main, jamais un chiffon qui serait aspiré), ou utiliser un extincteur CO₂ dans l’entrée d’air.</li><li>S’éloigner si ce n’est pas possible : risque de casse violente.</li><li>Ne pas redémarrer : remorquage, recherche de la cause (turbo, reniflard, niveau d’huile).</li></ol>' };

  /* ========================= EAU / HUILE — JOINT DE CULASSE ========================= */
  var C = {};
  C.start = ch('Quel symptôme ?', '<p>Trois circuits se croisent dans le moteur : la <b>combustion</b> (gaz à forte pression), l’<b>huile</b> (plusieurs bar) et le <b>liquide de refroidissement</b> (≈ 1 à 1,5 bar). Quand ils communiquent, le sens du passage oriente le diagnostic : l’huile, plus haute en pression, passe dans le liquide ; les gaz de combustion passent dans le liquide (bulles, surpression) ; le liquide passe dans les cylindres à l’arrêt (fumée blanche au démarrage).</p>',
    [['Liquide dans l’huile : « mayonnaise », huile laiteuse, niveau d’huile qui monte', 'c_mayo'], ['Huile dans le liquide de refroidissement : film gras, boue dans le vase', 'c_he'], ['Perte de liquide sans fuite visible', 'c_perte'], ['Bulles dans le vase, durites dures, surpression, surchauffe', 'c_co2'], ['Fumée blanche persistante, odeur sucrée', 'c_co2']]);
  C.c_mayo = ch('D’où vient la « mayonnaise » ?', '<p>Une mayonnaise <b>uniquement sous le bouchon de remplissage</b>, niveau de liquide <b>stable</b>, en hiver ou sur trajets courts, est souvent de la <b>condensation</b> (le moteur ne chauffe pas assez longtemps). Une huile <b>laiteuse sur la jauge</b>, un niveau d’huile qui <b>monte</b> et un liquide qui <b>baisse</b> = vrai mélange.</p>',
    [['Seulement sous le bouchon, liquide stable, trajets courts', 'end_c_cond'], ['Huile laiteuse sur la jauge et / ou liquide qui baisse', 'c_co2']]);
  C.c_he = ch('Huile dans le liquide : quelle huile, quels autres signes ?', '<p>L’huile moteur est à plus forte pression que le liquide : si une paroi cède, elle passe dans le liquide. Suspects : l’<b>échangeur eau / huile</b> (très fréquent : huile dans le vase <b>sans</b> bulles ni fumée), le <b>joint de culasse</b>, une <b>culasse fissurée</b>. Une huile <b>rouge / rose</b> vient de la <b>boîte automatique</b> (refroidisseur de BVA dans le radiateur).</p>',
    [['Huile moteur dans le vase, pas de bulles ni fumée', 'c_ech'], ['Huile + bulles, fumée ou surchauffe', 'c_co2'], ['Huile rouge / rose (boîte automatique)', 'end_c_bva']]);
  C.c_ech = ch('Test de l’échangeur eau / huile', '<ul><li><b>Sur le véhicule</b> : débrancher les deux durites d’eau de l’échangeur et les relier entre elles (l’échangeur est isolé du circuit), rincer le circuit, rouler : si l’huile ne revient plus dans le vase, c’est l’échangeur.</li><li><b>Déposé</b> : obturer le côté eau, mettre de l’air comprimé côté huile (ou l’inverse) et plonger dans un bac d’eau : des bulles = échangeur percé.</li></ul>',
    [['L’échangeur fuit', 'end_c_ech'], ['L’échangeur est étanche', 'c_co2']]);
  C.c_perte = ch('Où part le liquide ?', '<p>Sans fuite visible, le liquide part soit <b>dans l’habitacle</b> (radiateur de chauffage), soit <b>dans la combustion</b> (joint de culasse, culasse, <b>refroidisseur EGR</b> sur diesel : il part à l’échappement), soit en vapeur par un bouchon défectueux. Regarde aussi le <b>trou témoin de la pompe à eau</b> (traces sèches).</p>',
    [['Tapis humide, buée grasse sur le pare-brise, odeur sucrée dans l’habitacle', 'end_c_chauff'], ['Traces sous la pompe à eau ou autour du bouchon', 'end_c_fuite'], ['Rien de visible / fumée blanche', 'c_co2']]);
  C.c_co2 = ch('Test CO₂ (gaz de combustion dans le liquide)', '<p>Testeur de gaz de combustion sur le vase d’expansion (moteur chaud, niveau un peu abaissé pour ne pas aspirer de liquide) : on aspire l’air du vase à travers un réactif <b>bleu</b> qui vire au <b>jaune / vert</b> en présence de gaz de combustion. Fais-le au ralenti puis en montant le régime : certaines fuites n’apparaissent qu’en charge.</p>',
    [['Positif : le réactif change de couleur', 'c_loc'], ['Négatif', 'c_press']]);
  C.c_press = ch('Mise sous pression du circuit', '<p>Moteur <b>froid</b>, pompe de test à la place du bouchon, à la <b>pression du bouchon</b> (≈ 1 à 1,5 bar, inscrite dessus). Attends plusieurs minutes : la pression doit <b>tenir</b>. Si elle chute sans fuite extérieure, le liquide part à l’intérieur (cylindres, huile, échangeur, refroidisseur EGR). Teste aussi le <b>bouchon</b> avec l’adaptateur.</p>',
    [['La pression tient', 'end_c_rien'], ['Elle chute sans fuite extérieure', 'c_loc'], ['Elle chute avec une fuite extérieure', 'end_c_fuite']]);
  C.c_loc = ch('Localiser le passage', '<ul><li><b>Test de compression</b> (module ⚙️) : deux cylindres voisins faibles = joint entre eux.</li><li><b>Test d’étanchéité des cylindres</b> (fuite cylindre) : air comprimé dans chaque cylindre au PMH ; <b>bulles dans le vase</b> = ce cylindre communique avec l’eau.</li><li><b>Bougies</b> (essence) : une bougie anormalement <b>propre</b> ou humide = liquide dans ce cylindre.</li><li>Après une nuit : démarrage avec forte fumée blanche = liquide accumulé dans un cylindre.</li><li><b>Diesel</b> : refroidisseur EGR (isoler ses durites d’eau et refaire le test), joint de <b>puits d’injecteur</b>.</li><li>Moteurs à <b>chemises humides</b> (PL, certains diesels) : joints de chemise (liquide dans le carter sans perte de compression).</li></ul>',
    [['Deux cylindres voisins faibles / bulles au test d’étanchéité', 'end_c_joint'], ['Refroidisseur EGR qui fuit (diesel)', 'end_c_egr'], ['Culasse fissurée ou voilée', 'end_c_culasse'], ['Puits ou joint d’injecteur (diesel)', 'end_c_puits'], ['Joints de chemise (moteur chemisé)', 'end_c_chemise']]);
  var DEPC = '<p><b>Ne pas rouler</b> : liquide dans l’huile = coussinets détruits ; liquide dans un cylindre = risque de casse (bielle). Remorquage.</p>';
  C.end_c_cond = end('ok', 'Condensation', '<p>Pas de vrai mélange : le moteur ne chauffe pas assez longtemps. Rouler régulièrement plus longtemps, nettoyer le bouchon ; contrôle le <b>thermostat</b> (bloqué ouvert ?). En cas de doute : test CO₂ et suivi des niveaux.</p>');
  C.end_c_bva = end('bad', 'Refroidisseur de boîte automatique', '<p>Le refroidisseur de BVA intégré au radiateur est percé : remplace le radiateur, <b>rince les deux circuits</b> et vidange la boîte (l’eau dans l’huile de BVA la détruit).</p>', '<p>Ne pas rouler : la boîte peut être détruite.</p>');
  C.end_c_ech = end('bad', 'Échangeur eau / huile', '<p>Remplace l’échangeur (joints neufs). <b>Rince</b> le circuit de refroidissement plusieurs fois (produit de rinçage) jusqu’à disparition de l’huile, liquide neuf, purge. Si du liquide est passé dans l’huile : vidange + filtre.</p>');
  C.end_c_chauff = end('bad', 'Radiateur de chauffage', '<p>Remplace le radiateur de chauffage (souvent sous la planche de bord), sèche la moquette, contrôle l’évacuation. En attendant, certains véhicules permettent de ponter ses durites.</p>', '<p>Ponter provisoirement les durites du radiateur de chauffage (plus de chauffage) et surveiller le niveau.</p>');
  C.end_c_fuite = end('bad', 'Fuite extérieure', '<p>Pompe à eau (trou témoin), durite, radiateur, bouchon (tarage), vase. Répare, remplis, <b>purge</b>, refais le test de pression.</p>');
  C.end_c_rien = end('warn', 'Pas de passage détecté', '<p>Tests négatifs : surveille les niveaux, refais le test CO₂ <b>à chaud et en charge</b> (certaines fuites n’apparaissent qu’à chaud), teste le <b>bouchon</b>, <b>purge</b> le circuit (de l’air donne des symptômes voisins), contrôle le thermostat et le ventilateur.</p>');
  C.end_c_joint = end('bad', 'Joint de culasse', '<ol><li>Chercher la <b>cause</b> (souvent une surchauffe : thermostat, ventilateur, pompe à eau, fuite).</li><li>Dépose de la culasse : <b>planéité</b> de la culasse et du bloc (règle et cales, tolérance constructeur), recherche de <b>fissures</b> (essai d’étanchéité de la culasse en atelier spécialisé), surfaçage dans les limites autorisées.</li><li>Joint de la <b>bonne épaisseur</b> (diesel : selon le dépassement des pistons), <b>vis de culasse neuves</b>, serrage selon la méthode constructeur (angulaire).</li><li>Vidange + filtre à huile, rinçage du circuit, liquide neuf, purge ; test CO₂ après quelques km.</li></ol>', DEPC);
  C.end_c_egr = end('bad', 'Refroidisseur EGR', '<p>Remplace le refroidisseur EGR, rince le circuit. Le liquide brûlé encrasse le FAP et le catalyseur : contrôle-les (module 🌫️).</p>' + lks(lk('anti', '🌫️ Antipollution')), DEPC);
  C.end_c_culasse = end('bad', 'Culasse fissurée ou voilée', '<p>Culasse voilée : surfaçage si la cote le permet ; fissurée : remplacement ou réparation spécialisée. Cherche la cause de la surchauffe.</p>', DEPC);
  C.end_c_puits = end('bad', 'Puits / joint d’injecteur', '<p>Dépose l’injecteur, joint (rondelle pare-flamme) neuf, contrôle du puits (fissure, corrosion) ; serrage de la bride au couple.</p>', DEPC);
  C.end_c_chemise = end('bad', 'Joints de chemise', '<p>Liquide dans le carter par les joints toriques du bas des chemises : dépose du moteur (chemises, joints, contrôle du dépassement des chemises). Vidange et rinçage du circuit d’huile.</p>', DEPC);

  /* ========================= FUMÉES ========================= */
  var F = {};
  F.start = ch('Quel moteur ?', '<p>La couleur de la fumée dit <b>ce qui brûle</b> : <b>blanche</b> = eau ou carburant non brûlé, <b>bleue</b> = huile, <b>noire</b> = trop de carburant pour l’air disponible. Les causes diffèrent entre essence et diesel. Note aussi <b>quand</b> elle apparaît (à froid, au ralenti, en accélération, en décélération).</p>',
    [['Moteur essence', 'f_ess'], ['Moteur diesel', 'f_die']]);
  F.f_ess = ch('Essence : quelle fumée ?', '', [['Blanche légère à froid, qui disparaît moteur chaud', 'fe_blf'], ['Blanche épaisse persistante, odeur sucrée', 'fx_bl'], ['Bleue', 'fe_bleu'], ['Noire', 'fe_noir']]);
  F.f_die = ch('Diesel : quelle fumée ?', '', [['Blanche / grise au démarrage à froid, qui pique les yeux', 'fd_blf'], ['Blanche épaisse persistante, odeur sucrée', 'fx_bl'], ['Bleue', 'fd_bleu'], ['Noire à l’accélération', 'fd_noir'], ['Noire en permanence, même au ralenti', 'fd_noir']]);
  F.fe_blf = end('ok', 'Vapeur de condensation (essence)', '<p>Normal par temps froid ou humide : l’eau produite par la combustion se condense dans l’échappement froid. Elle disparaît moteur chaud et <b>ne sent rien</b>. Si elle persiste moteur chaud ou sent sucré : liquide de refroidissement (module 💧).</p>' + lks(lk('culasse', '💧 Eau / huile, joint de culasse')));
  F.fx_bl = end('bad', 'Fumée blanche persistante : liquide de refroidissement', '<p><b>Causes</b> : joint de culasse, culasse fissurée, <b>refroidisseur EGR</b> (diesel), joint de puits d’injecteur (diesel), turbo refroidi par eau.</p><p><b>À vérifier</b> : niveau de liquide qui baisse, test CO₂, mise sous pression du circuit, compression / test d’étanchéité des cylindres, bougie trop propre (essence).</p>' + lks(lk('culasse', '💧 Recherche eau / huile, joint de culasse')), '<p>Ne pas rouler si le niveau baisse vite : remorquage.</p>');
  F.fe_bleu = end('bad', 'Fumée bleue (essence) : huile brûlée', '<p><b>Selon le moment</b> :</p><ul><li>Au <b>démarrage</b>, après un long <b>ralenti</b> ou en <b>décélération</b> (forte dépression) : <b>joints de queues de soupapes</b>, guides usés.</li><li>En <b>accélération</b>, en charge, permanente avec consommation : <b>segments</b> / cylindres usés, <b>turbo</b>.</li></ul><p><b>À vérifier</b> : niveau d’huile pas trop haut, <b>recyclage des vapeurs d’huile</b> (reniflard, membrane du décanteur : aspiration d’huile par l’admission), turbo (huile dans l’admission), compression + test à l’huile, bougies huileuses.</p>' + lks(lk('turbo', '🌀 Turbo'), lk('meca', '⚙️ Compression')));
  F.fe_noir = end('bad', 'Fumée noire (essence) : mélange trop riche', '<p><b>Causes</b> : sonde de température moteur (le calculateur croit le moteur froid), <b>débitmètre</b> ou capteur de pression d’admission, <b>pression d’essence</b> trop haute (régulateur), <b>injecteur qui fuit</b>, sonde lambda paresseuse, filtre à air colmaté.</p><p><b>À vérifier</b> : défauts et <b>corrections de richesse</b> (adaptations) à la valise, pression d’essence, capteurs (CTN, débitmètre, pression), injecteurs, sonde lambda. Un mélange riche détruit le <b>catalyseur</b>.</p>' + lks(lk('capteurs', '📡 Capteurs'), lk('anti', '🌫️ Sonde lambda')));
  F.fd_blf = end('warn', 'Fumée blanche à froid (diesel) : gazole mal brûlé', '<p>Le gazole ne brûle pas complètement (odeur de gazole, pique les yeux). <b>Causes</b> : <b>préchauffage</b> (bougies, boîtier), <b>compression</b> faible, <b>injecteur</b> qui pulvérise mal ou fuit, calage de l’injection (anciennes pompes) ou de la distribution, sonde de température moteur, thermostat bloqué ouvert, EGR ouverte à froid, gazole de mauvaise qualité.</p><p><b>À vérifier dans l’ordre</b> : bougies de préchauffage, température moteur lue, retours et corrections d’injecteurs, compression.</p>' + lks(lk('meca', '⚙️ Préchauffage / compression'), lk('cr', '⛽ Injecteurs')));
  F.fd_bleu = end('bad', 'Fumée bleue (diesel) : huile brûlée', '<p><b>Causes</b> : <b>turbo</b> (retour d’huile gêné, reniflard bouché, paliers usés), <b>segments / cylindres</b> usés (gaz de carter), guides et joints de queues de soupapes, <b>niveau d’huile trop haut</b> (dilution par le gazole sur les diesels à FAP).</p><p><b>À vérifier</b> : niveau et odeur de l’huile (gazole ?), huile dans l’admission et l’échangeur, retour d’huile du turbo, reniflard, compression. ⚠️ Si le moteur aspire beaucoup d’huile, il peut <b>s’emballer</b>.</p>' + lks(lk('turbo', '🌀 Turbo'), lk('meca', '⚙️ Compression')));
  F.fd_noir = end('bad', 'Fumée noire (diesel) : trop de gazole pour l’air', '<p><b>Manque d’air</b> : filtre à air, <b>fuite de suralimentation</b>, turbo (commande, géométrie grippée), débitmètre, <b>EGR bloquée ouverte</b>.</p><p><b>Trop de gazole</b> : injecteurs qui fuient ou pulvérisent mal (retours, corrections), pression de rail trop haute, reprogrammation ou boîtier additionnel.</p><p>⚠️ Un diesel <b>équipé d’un FAP</b> ne doit <b>jamais</b> fumer noir : une fumée noire visible = <b>FAP percé ou démonté</b> (pression différentielle quasi nulle).</p><p><b>À vérifier</b> : pression de suralimentation demandée / mesurée, débitmètre, EGR, retours injecteurs, pression de rail, FAP.</p>' + lks(lk('turbo', '🌀 Turbo'), lk('cr', '⛽ Injection'), lk('anti', '🌫️ EGR / FAP')));

  function add(id, icon, titre, sous, steps, comprendre) { D.MODULES[id] = { id: id, icon: icon, titre: titre, sous: sous, start: 'start', steps: steps, comprendre: comprendre }; }
  add('turbo', '🌀', 'Turbo', 'Suralimentation, fuites d’air, commande (capsule, géométrie, actionneur), huile, jeu, casse, emballement', T,
    '<h3>Contrôles du turbo</h3><div class="tw"><table><tr><th>Contrôle</th><th>Comment / valeur type</th></tr><tr><td>Capteur de suralimentation</td><td>Moteur arrêté = pression atmosphérique</td></tr><tr><td>Pression demandée / mesurée</td><td>Essai en charge, écart ≤ 10 %</td></tr><tr><td>Étanchéité de l’admission</td><td>Air comprimé détendu, 2 bar maxi, eau savonneuse</td></tr><tr><td>Commande pneumatique</td><td>Dépression pompe à vide ≈ 0,6 à 0,9 bar ; capsule qui tient ; tige libre</td></tr><tr><td>Actionneur électrique</td><td>Position demandée / mesurée, apprentissage</td></tr><tr><td>Jeu de l’axe</td><td>Axial quasi nul ; radial léger normal ; aucune touche dans le carter</td></tr></table></div>' +
    '<div class="box piege"><b>⚠️ À retenir</b><ul><li>Un turbo casse rarement seul : <b>huile</b> (qualité, pression, arrivée, retour) et <b>corps étrangers</b> d’abord.</li><li>Après remplacement : tuyau d’huile neuf, vidange, amorçage, ralenti sans accélérer.</li><li>Laisser tourner au ralenti quelques dizaines de secondes avant de couper un moteur chaud.</li></ul></div>');
  add('culasse', '💧', 'Eau / huile : joint de culasse', 'Mayonnaise, huile dans le liquide, perte de liquide, bulles, fumée blanche : échangeur, joint, culasse, EGR', C,
    '<h3>Qui passe où ?</h3><div class="tw"><table><tr><th>Constat</th><th>Suspects</th><th>Test</th></tr><tr><td>Huile dans le liquide, sans bulles</td><td>Échangeur eau / huile</td><td>Isoler l’échangeur</td></tr><tr><td>Bulles, surpression, surchauffe</td><td>Joint de culasse, culasse</td><td>Test CO₂</td></tr><tr><td>Liquide qui baisse, fumée blanche</td><td>Joint, culasse, refroidisseur EGR</td><td>Mise sous pression, test d’étanchéité des cylindres</td></tr><tr><td>Mayonnaise sous le bouchon seulement</td><td>Condensation</td><td>Niveaux stables, trajets longs</td></tr><tr><td>Huile rouge dans le liquide</td><td>Refroidisseur de BVA</td><td>Aspect / couleur</td></tr><tr><td>Liquide dans le carter, compression bonne</td><td>Joints de chemise (moteur chemisé)</td><td>Pression du circuit, analyse d’huile</td></tr></table></div>');
  add('fumee', '💨', 'Fumées : blanche, bleue, noire', 'Causes et contrôles selon essence ou diesel', F,
    '<h3>Tableau des fumées</h3><div class="tw"><table><tr><th>Fumée</th><th>Essence</th><th>Diesel</th></tr><tr><td>Blanche à froid, disparaît</td><td>Condensation (normal)</td><td>Gazole mal brûlé : préchauffage, compression, injecteurs</td></tr><tr><td>Blanche persistante, odeur sucrée</td><td>Liquide : joint de culasse, culasse</td><td>Liquide : joint, culasse, refroidisseur EGR, puits d’injecteur</td></tr><tr><td>Bleue</td><td>Huile : joints de queues de soupapes, segments, turbo, reniflard</td><td>Huile : turbo, segments, reniflard, niveau trop haut (dilution)</td></tr><tr><td>Noire</td><td>Mélange riche : capteurs, pression d’essence, injecteur</td><td>Manque d’air ou excès de gazole : turbo, fuite, EGR, débitmètre, injecteurs ; avec FAP = FAP HS</td></tr></table></div>');

  /* Liens depuis les modules existants */
  var ME = D.MODULES.meca.steps;
  ME.m_fumee_old = ME.m_fumee;
  ME.m_fumee = info('Fumées', '<p>Le module <b>💨 Fumées</b> détaille les causes et les contrôles selon <b>essence ou diesel</b>.</p>' + lks(lk('fumee', '💨 Ouvrir le module Fumées')), 'Rester ici (version courte)', 'm_fumee_old');
  ME.end_joint.html += lks(lk('culasse', '💧 Recherche complète eau / huile'));
  ME.m_cyl.why += '<p>Recherche complète (échangeur, refroidisseur EGR, chemises…) : module <a href="#/mod/culasse">💧 Eau / huile</a>.</p>';
  D.MODULES.cr.steps.end_turbo.html += lks(lk('turbo', '🌀 Diagnostic complet du turbo'));
  D.MODULES.cr.steps.turbo.why += '<p>Diagnostic complet (fuites, commande, jeu, huile) : module <a href="#/mod/turbo">🌀 Turbo</a>.</p>';

  var order = ['urgence', 'mux', 'capteurs', 'charge', 'meca', 'turbo', 'culasse', 'fumee', 'cr', 'anti', 'cles', 'dsft', 'frein', 'autres', 'pl'], old = D.MODULES, nm = {};
  order.forEach(function (k) { if (old[k]) nm[k] = old[k]; }); Object.keys(old).forEach(function (k) { if (!nm[k]) nm[k] = old[k]; });
  D.MODULES = nm;
})();
