/* Diagnostic — POIDS LOURDS (PL / SPL), CAPTEURS (alimentations et contrôles), méthodes de contrôle par marque.
   Sources cours : AGB 03 ind. c (équipement pneumatique : réglementation, code chiffré des orifices, VP, dessiccateur,
   VCR / harmonisation 0 à 1 bar, VRU desserrée au-delà de 2,8 bar, cylindres à verrou 2 à 3 s par phase, Tristop, VNAE,
   suspension pneumatique, performances : remplissage 6 à 11 min, 8 actionnements, 0,6 s, 5 m/s², pentes 18 % / 12 %,
   conduites 8 bar maxi) ; AGA 01 ind. c (batteries, 24 V, URT 28 à 29,5 V, contacteur de démarreur) ; GD 21 / GD 22
   (capteurs : régime inductif, phase Hall, CTN, pression piézo, pédale 2 pistes, relais double ; PL : 1 800 à 2 400 bar
   injecteurs-pompes). Valeurs web (TYPES) : pression de service 8 à 12 bar, étanchéité < 0,5 bar / 10 min. */
(function () {
  var D = window.DIAG, M = D.MEASURES;
  function mes(id, label, unit, min, max, note) { M[id] = { id: id, label: label, unit: unit, min: min, max: max, note: note || '' }; }
  function r1(n) { return String(Math.round(n * 10) / 10).replace('.', ','); }
  function end(v, title, html, dep) { var s = { type: 'end', v: v, title: title, html: html }; if (dep) s.dep = dep; return s; }
  function urg(title, html) { return { type: 'end', v: 'info', title: title, html: html, noApres: true }; }
  function info(title, html, bouton, next) { return { type: 'info', title: title, html: html, bouton: bouton, next: next }; }

  /* ========================= POIDS LOURDS ========================= */
  mes('p_coup', 'Pression de coupure du régulateur (manomètre sur prise d’épreuve ou tableau de bord)', 'bar', 8, 12.5, 'Valeur type : 8 à 12 bar selon constructeur (régulation vers 9,5 bar sur les anciens véhicules). Utilise la valeur constructeur.');
  mes('t_rempl', 'Temps de remplissage des réservoirs (de vides à la pression de coupure)', 'min', 0, 11, 'Cours AGB 03 : toutes les bouteilles remplies en 6 à 11 min. Au quotidien, la pression de roulage revient en 1 à 2 min au ralenti ; plus de 3 à 4 min = compresseur fatigué, fuite ou dessiccateur saturé.');
  mes('dp_10', 'Chute de pression en 10 min, moteur arrêté, freins desserrés', 'bar', 0, 0.5, 'Valeur type : moins de 0,5 bar en 10 min (ou moins de 1 bar en 30 min).');
  mes('u_b1', 'Tension batterie n°1 (au repos)', 'V', 12.4, 12.9, 'Deux batteries 12 V en série = 24 V. Mesure chacune séparément.');
  mes('u_b2', 'Tension batterie n°2 (au repos)', 'V', 12.4, 12.9, '');
  mes('u_chg24', 'Tension de charge 24 V (moteur à régime accéléré, aux bornes du 24 V)', 'V', 28, 29.5, 'Cours AGA 01 : régulation d’un circuit 24 V entre 28 et 29,5 V.');
  mes('u_crank24', 'Tension 24 V pendant le démarrage', 'V', 19, Infinity, 'Valeur type : environ le double du 12 V, ≈ 19 V mini.');
  mes('fAr2G', 'Banc : effort de freinage 2ᵉ essieu AR gauche (0 si absent)', 'daN', null, null);
  mes('fAr2D', 'Banc : effort de freinage 2ᵉ essieu AR droit (0 si absent)', 'daN', null, null);

  var P = {};
  P.start = { type: 'choice', title: 'Poids lourd : que veux-tu contrôler ?', why: '<p>Un PL (> 3,5 t) se distingue d’un VL par le <b>freinage pneumatique</b> (réglementation européenne, obligatoire en France depuis 1975), l’électricité en <b>24 V</b> (deux batteries 12 V en série), le multiplexage <b>SAE J1939</b> et souvent une <b>suspension pneumatique</b>. Les méthodes moteur (injection, antipollution, capteurs) restent celles des autres modules.</p>',
    choices: [['Freinage pneumatique', 'pl_frein'], ['Électricité 24 V : batteries, charge, démarrage', 'pl_24'], ['Multiplexage J1939, calculateurs', 'pl_can'], ['Suspension pneumatique', 'pl_susp'], ['Moteur, injection, AdBlue', 'pl_mot'], ['🆘 Dépannage d’urgence PL', 'pl_urg']] };
  P.pl_frein = { type: 'choice', title: 'Freinage pneumatique : quel symptôme ?', why: '<p>Le circuit se décompose en <b>alimentation</b> (compresseur, régulateur, dessiccateur, valve de protection, réservoirs), <b>distribution</b> (robinets, valves), <b>utilisation</b> (vases, cylindres à ressort ou à verrou) et <b>servitudes</b>. Principe d’<b>unicité de défaillance</b> : au moins deux circuits indépendants ; si l’un lâche, l’autre assure au moins 30 % de l’efficacité.</p>',
    choices: [['Pression d’air faible, remplissage long, fuite', 'pl_air'], ['Frein de parc : ne se desserre pas ou inefficace', 'pl_parc'], ['Remorque / attelage', 'pl_rem'], ['Analyser un passage au banc de freinage', 'pl_banc']] };
  P.pl_air = { type: 'measure', title: 'Production d’air et étanchéité', why: '<p>Le <b>compresseur</b> (entraîné par le moteur) remplit les réservoirs ; le <b>régulateur</b> coupe à la pression maxi et réenclenche plus bas ; le <b>dessiccateur</b> sèche l’air ; la <b>valve de protection</b> (4 circuits : orifices 21 à 24) alimente les circuits dans un ordre précis et isole un circuit qui fuit.</p>',
    how: '<ol><li>Réservoirs purgés (vides), moteur au ralenti accéléré : chronomètre jusqu’à la coupure du régulateur (bruit d’échappement du dessiccateur) et relève la pression de coupure.</li><li>Moteur arrêté, frein de parc desserré (véhicule calé) : note la chute de pression en 10 min.</li></ol>', measures: ['p_coup', 't_rempl', 'dp_10'],
    decide: function (m) {
      if (m('dp_10').st === 'bad') return { v: 'bad', msg: 'Fuite : ' + r1(m('dp_10').v) + ' bar perdus en 10 min. Recherche à l’eau savonneuse (raccords, valves, cylindres, soufflets de suspension).', next: 'end_fuite' };
      if (m('p_coup').st === 'bad' && m('p_coup').dir === 'high') return { v: 'bad', msg: 'Pression de coupure trop haute (' + r1(m('p_coup').v) + ' bar) : régulateur défectueux. Risque pour les réservoirs et les valves (soupape de sécurité).', next: 'end_regul' };
      if (m('p_coup').st === 'bad' || m('t_rempl').st === 'bad') return { v: 'bad', msg: 'Production d’air insuffisante : compresseur (usure, filtre à air, clapets, courroie ou embrayage de compresseur), régulateur qui ne coupe pas au bon niveau, dessiccateur colmaté.', next: 'pl_dess' };
      return { v: 'ok', msg: 'Production et étanchéité correctes. On contrôle quand même l’humidité (purge).', next: 'pl_dess' }; } };
  P.pl_dess = { type: 'choice', title: 'Purge des réservoirs : y a-t-il de l’eau ?', why: '<p>Le <b>dessiccateur</b> sèche l’air par <b>adsorption</b> sur un granulat, puis se <b>régénère</b> à chaque coupure du régulateur (échappement par l’orifice 3). Une cartouche saturée laisse passer l’eau : corrosion, gel des valves. La température d’entrée du dessiccateur ne doit pas dépasser 65 °C (cours).</p>',
    choices: [['Pas d’eau (ou quelques gouttes)', 'end_air_ok'], ['De l’eau, de l’huile ou une émulsion', 'end_dess']] };
  P.pl_parc = { type: 'choice', title: 'Frein de parc', why: '<p><b>Cylindre à ressort (Tristop)</b> : le frein de parc fonctionne par <b>absence d’air</b> — le ressort serre, l’air le desserre. Une <b>VNAE</b> (valve de non-addition des efforts) évite de cumuler frein de service et frein de parc. <b>Cylindre à verrou</b> : un verrou bloque mécaniquement la tige ; la commande se fait en 3 phases de <b>2 à 3 s</b> chacune (cours) — trop vite, on abîme la tige ou le verrou.</p>',
    choices: [['Tristop : le frein de parc ne se desserre pas', 'end_tristop'], ['Cylindre à verrou : blocage, témoin incohérent', 'end_verrou'], ['Frein de parc inefficace (le véhicule bouge)', 'end_parc_eff']] };
  P.pl_rem = { type: 'choice', title: 'Remorque / attelage', why: '<p>Deux conduites : <b>automatique</b> (main rouge : alimente la remorque en air) et <b>directe</b> (main jaune : transmet l’ordre de freinage). La <b>VCR</b> du tracteur commande la remorque, avec un dispositif d’<b>harmonisation</b> réglable de 0 à 1 bar (la remorque freine un peu plus que le tracteur pour garder l’ensemble aligné). La <b>VRU</b> de la remorque freine automatiquement si la conduite automatique chute (rupture d’attelage) : les freins restent serrés jusqu’à <b>2,8 bar</b> dans la conduite automatique.</p>',
    choices: [['La remorque ne se desserre pas', 'end_vru'], ['La remorque freine mal ou l’ensemble se met en portefeuille', 'end_vcr'], ['Freinage d’urgence de la remorque intempestif', 'end_rupture']] };
  P.pl_banc = { type: 'measure', title: 'Banc de freinage PL', why: '<p>Même principe que le VL : <b>déséquilibre</b> par essieu et <b>efficacité</b> = somme des efforts / poids. Cours AGB 03 : frein de service ≈ <b>5 m/s²</b> de décélération (≈ 50 % d’efficacité) ; frein de stationnement capable de tenir le véhicule en charge dans une pente de <b>18 %</b> (≈ 18 %).</p>',
    how: '<p>Efforts maxi en daN, essieu par essieu (0 pour un essieu absent), masse du véhicule pesée au banc (kg).</p>', measures: ['fAvG', 'fAvD', 'fArG', 'fArD', 'fAr2G', 'fAr2D', 'fPG', 'fPD', 'masse'],
    decide: function (m) {
      function des(a, b) { var mx = Math.max(a, b); return mx ? (mx - Math.min(a, b)) / mx * 100 : 0; }
      var v = 'ok', out = [], P0 = m('masse').v * 9.81 / 10;
      [['Essieu AV', 'fAvG', 'fAvD'], ['Essieu AR 1', 'fArG', 'fArD'], ['Essieu AR 2', 'fAr2G', 'fAr2D']].forEach(function (e) {
        if (!m(e[1]).v && !m(e[2]).v) return; var d = des(m(e[1]).v, m(e[2]).v);
        if (d > 30) { v = 'bad'; out.push(e[0] + ' : déséquilibre ' + r1(d) + ' % ❌.'); } else if (d > 20) { if (v === 'ok') v = 'warn'; out.push(e[0] + ' : déséquilibre ' + r1(d) + ' % ⚠️.'); } else out.push(e[0] + ' : déséquilibre ' + r1(d) + ' % ✅.'); });
      if (P0) { var eS = (m('fAvG').v + m('fAvD').v + m('fArG').v + m('fArD').v + m('fAr2G').v + m('fAr2D').v) / P0 * 100, eP = (m('fPG').v + m('fPD').v) / P0 * 100;
        out.push('Efficacité frein de service : ' + r1(eS) + ' % ' + (eS >= 50 ? '✅' : '❌ (≈ 50 % mini)') + '.'); if (eS < 50) v = 'bad';
        if (m('fPG').v + m('fPD').v > 0) { out.push('Efficacité frein de stationnement : ' + r1(eP) + ' % ' + (eP >= 18 ? '✅' : '❌ (18 % mini)') + '.'); if (eP < 18) v = 'bad'; } }
      return { v: v, msg: out.join(' '), next: v === 'ok' ? 'end_banc_ok' : 'end_banc' }; } };
  P.pl_24 = { type: 'measure', title: 'Électricité 24 V', why: '<p>Deux batteries 12 V <b>en série</b> (le + de l’une relié au – de l’autre) donnent 24 V. Une batterie faible déséquilibre l’ensemble : l’alternateur charge les deux « en bloc », la faible se dégrade encore. Cours AGA 01 : régulation d’un circuit 24 V entre <b>28 et 29,5 V</b>.</p>',
    how: '<ol><li>Au repos (coupe-batterie fermé, moteur arrêté depuis un moment) : tension de <b>chaque</b> batterie.</li><li>Pendant le démarrage : tension aux bornes du 24 V.</li><li>Moteur à régime accéléré : tension de charge.</li></ol>', measures: ['u_b1', 'u_b2', 'u_crank24', 'u_chg24'],
    decide: function (m) { var e = Math.abs(m('u_b1').v - m('u_b2').v);
      if (m('u_chg24').st === 'bad') return { v: 'bad', msg: m('u_chg24').dir === 'high' ? 'Surcharge (' + r1(m('u_chg24').v) + ' V) : régulateur.' : 'Charge insuffisante (' + r1(m('u_chg24').v) + ' V) : courroie, alternateur, câbles (chute de tension, module 🔋).', next: 'end_alt24' };
      if (e > 0.3 || m('u_b1').st === 'bad' || m('u_b2').st === 'bad' || m('u_crank24').st === 'bad') return { v: 'bad', msg: 'Batteries déséquilibrées (écart ' + r1(e) + ' V) ou faibles : recharge-les séparément et teste-les ; remplace-les par paire.', next: 'end_bat24' };
      return { v: 'ok', msg: 'Batteries équilibrées et charge correcte.', next: 'end_24_ok' }; } };
  P.pl_can = info('Multiplexage PL : J1939', '<ul><li><b>SAE J1939</b> : CAN haute vitesse à <b>250 kbit/s</b> (souvent 500 kbit/s sur les véhicules récents), deux fils torsadés, <b>deux résistances de 120 Ω</b> → 60 Ω entre CAN H et CAN L, comme sur un VL. Les niveaux de tension CAN sont identiques (≈ 2,5 V au repos) même sur un véhicule 24 V.</li><li>Plusieurs réseaux : moteur / transmission, véhicule, freinage (EBS), carrosserie / superstructure, reliés par un <b>calculateur véhicule</b> (passerelle, nom selon la marque).</li><li><b>Prise de diagnostic</b> : 16 broches type OBD sur les véhicules récents (brochage selon marque), ou ancienne prise ronde <b>9 broches (Deutsch)</b> : A masse, B + batterie, C CAN H, D CAN L (à vérifier sur le schéma).</li><li>Mesures : mêmes méthodes que le module <b>🔌 Multiplexage</b> (60 Ω contact coupé, isolement, tensions contact mis).</li></ul>', 'Conclusion', 'end_can');
  P.pl_susp = { type: 'choice', title: 'Suspension pneumatique', why: '<p>Des <b>soufflets</b> remplacent les ressorts ; une <b>valve de nivellement</b> (tige reliée à l’essieu) gonfle ou dégonfle pour garder la hauteur constante ; une <b>valve de barrage</b> isole la suspension du freinage (si un soufflet crève, la pression de freinage est conservée) ; un robinet <b>monte / baisse</b> et une <b>valve de coupure</b> (limitation de course). Sur les systèmes électroniques (ECAS), capteurs de hauteur et calculateur.</p>',
    choices: [['Le châssis s’affaisse à l’arrêt', 'end_susp_fuite'], ['Hauteur incorrecte en roulant ou penché d’un côté', 'end_susp_niv'], ['Ne monte / ne baisse pas à la commande', 'end_susp_cde']] };
  P.pl_mot = info('Moteur PL', '<ul><li>Même démarche que les modules <b>⛽ Common rail</b>, <b>🌫️ Antipollution</b> (SCR / AdBlue, conditions d’activation du cours) et <b>📡 Capteurs</b>.</li><li>Systèmes PL : common rail, <b>injecteurs-pompes</b> ou pompes unitaires (≈ 1 800 à 2 400 bar, cours GD 22), anciennes <b>pompes en ligne</b> (alimentation 1 à 2,5 bar).</li><li>Les capteurs restent alimentés en <b>5 V</b> par le calculateur ; les actionneurs et relais sont en <b>24 V</b> : ne jamais brancher un appareil 12 V.</li><li>Ralentisseur, frein moteur, boîte robotisée : défauts et apprentissages à la valise constructeur.</li></ul>', 'Terminer', 'end_mot');
  P.pl_urg = { type: 'choice', title: 'Dépannage d’urgence PL', choices: [['Démarrer en 24 V (batteries à plat)', 'u_24'], ['Frein de parc bloqué (plus d’air) : desserrage mécanique', 'u_tristop'], ['Remorquer un PL', 'u_rem'], ['Pression d’air qui ne monte pas, gel', 'u_air'], ['Crevaison / pneu PL', 'u_pneu']] };
  P.u_24 = urg('Démarrer un PL en 24 V', '<ol><li>Source <b>24 V</b> uniquement (autre PL, booster 24 V). Jamais 24 V sur un véhicule 12 V.</li><li>Repère le <b>+ libre</b> (sortie 24 V) et le <b>– libre</b> (masse) des deux batteries en série ; ne touche pas au pont entre les deux.</li><li>Rouge : + 24 V → + 24 V. Noir : – de la source → masse châssis / moteur du PL en panne.</li><li>Coupe-batterie fermé, démarrer par essais de 10 à 15 s, débrancher dans l’ordre inverse.</li><li>Ensuite : recharger chaque batterie, contrôler la charge (28 à 29,5 V).</li></ol>');
  P.u_tristop = urg('Desserrage mécanique d’un cylindre à ressort (Tristop)', '<ol><li><b>Caler le véhicule</b> : une fois desserré, il n’a plus de frein de parc sur cet essieu.</li><li>La plupart des cylindres à ressort ont une <b>vis (boulon) de desserrage de secours</b> à l’arrière du cylindre : la visser / dévisser selon le modèle comprime le ressort et libère le frein.</li><li>⚠️ <b>Ne jamais démonter un cylindre à ressort</b> : le ressort est très puissant (danger mortel).</li><li>Mieux : rendre de l’air au circuit (autre véhicule par la main d’accouplement, compresseur) pour desserrer normalement.</li><li>Après : revisser la vis en position route avant de rouler, sinon plus de frein de parc.</li></ol>');
  P.u_rem = urg('Remorquer un PL', '<ul><li>Par un dépanneur adapté ; barre rigide.</li><li>Certains véhicules militaires ont des <b>mains d’accouplement à l’avant</b> (cours) : la <b>rouge</b> (automatique) remplit les réservoirs du véhicule remorqué — on peut alors desserrer le frein de parc au robinet ; la <b>jaune</b> (directe) commande ses freins. Selon le véhicule, seules les roues arrière sont freinées (ex. GBC 180).</li><li>Sinon : desserrage mécanique des cylindres à ressort (voir ce dépannage).</li><li>Roues motrices au sol sur une longue distance : <b>désaccoupler l’arbre de transmission</b> ou déposer les arbres de roue selon la notice (protection de la boîte).</li><li>Moteur arrêté : plus d’assistance de direction ni de production d’air.</li></ul>');
  P.u_air = urg('La pression d’air ne monte pas / gel', '<ul><li>Compresseur : courroie, embrayage de compresseur (selon moteur), régulateur bloqué en position de coupure.</li><li>Grosse fuite : bruit, vase ou soufflet percé ; la valve de protection isole le circuit défaillant, les autres restent alimentés à sa pression de tarage.</li><li><b>Gel</b> : purger, utiliser le <b>dispositif antigel</b> s’il existe ; dessiccateur : réchauffeur électrique ; mettre le véhicule à l’abri.</li><li>Alimenter depuis un autre véhicule par la main d’accouplement ou un compresseur par la prise de gonflage / d’épreuve.</li></ul>');
  P.u_pneu = urg('Pneu de poids lourd', '<ul><li>Pression élevée et roue très lourde : utiliser un <b>cric et des chandelles adaptés</b>, jamais le travail sous un véhicule uniquement sur cric.</li><li>Ne <b>jamais regonfler</b> un pneu qui a roulé à plat ou très dégonflé sans contrôle (risque d’éclatement).</li><li>Après intervention sur la jante : gonflage en <b>cage de sécurité</b>, à distance.</li><li>Jumelage : un pneu à plat surcharge son voisin ; rouler le moins possible.</li><li>Serrage des écrous au couple constructeur, contrôle après quelques dizaines de km.</li></ul>');
  P.end_fuite = end('bad', 'Fuite d’air', '<p>Pulvérise de l’eau savonneuse sur les raccords, canalisations, valves, cylindres et soufflets ; écoute moteur arrêté (le compresseur ne masque plus le bruit). Fais aussi le test <b>pédale enfoncée</b> (fuites du circuit de freinage de service) et <b>frein de parc desserré</b> (chambres ressort). Remplace l’élément fuyard.</p>', '<p>Petite fuite : rouler en surveillant les manomètres ; si la pression tombe sous la pression mini (voyant, alarme), <b>s’arrêter</b> : le frein de parc se serre tout seul par manque d’air.</p>');
  P.end_regul = end('bad', 'Régulateur de pression', '<p>Remplace ou règle le régulateur (ou le dessiccateur à régulateur intégré). Contrôle la soupape de sécurité.</p>');
  P.end_air_ok = end('ok', 'Circuit d’alimentation correct', '<p>Production d’air, étanchéité et séchage conformes. Remplace la cartouche du dessiccateur à la périodicité constructeur.</p>');
  P.end_dess = end('bad', 'Dessiccateur / compresseur', '<p><b>Eau</b> : cartouche du dessiccateur saturée (à remplacer), régénération inopérante (clapet d’échappement, réservoir de régénération, minuterie). <b>Huile</b> : le compresseur <b>pompe de l’huile</b> (segments, culasse) : il faut le réparer, sinon la cartouche neuve sera détruite. Purger tous les réservoirs après réparation.</p>');
  P.end_tristop = end('bad', 'Tristop qui ne se desserre pas', '<p>Pression des réservoirs (le frein de parc ne se desserre pas sous la pression mini) ; robinet de frein de parc ; <b>VNAE</b> / valve relais ; fuite de la chambre ressort (échappement d’air au desserrage) ; vis de desserrage de secours restée dévissée ; mécanisme de frein grippé (cames, leviers).</p>', '<p>Voir <b>🆘 Dépannage d’urgence PL → desserrage mécanique</b>.</p>');
  P.end_verrou = end('bad', 'Cylindre à verrou', '<p>Respecter les <b>3 phases de 2 à 3 s</b> (cours) : chambre arrière, chambre à verrou, vidange. Contrôler l’alimentation de chaque chambre au manomètre, le témoin, la double valve d’arrêt ; remplacer le cylindre si la tige ou le verrou est abîmé.</p>');
  P.end_parc_eff = end('bad', 'Frein de parc inefficace', '<p>Réglage des leviers (rattrapage automatique grippé), garnitures et tambours / disques usés ou gras, ressort de Tristop fatigué. Contrôle au banc : stationnement ≥ 18 % (tenue en pente de 18 % en solo, 12 % pour un ensemble, tracteur seul freiné).</p>');
  P.end_vru = end('bad', 'Remorque qui ne se desserre pas', '<p>La conduite <b>automatique</b> (rouge) doit dépasser <b>2,8 bar</b> pour que la VRU desserre. Contrôle : mains bien accouplées (rouge sur rouge), pression à la main automatique, <b>valve de desserrage</b> (poussoir) en position route, réservoir de la remorque, VRU.</p>');
  P.end_vcr = end('bad', 'Freinage de la remorque / harmonisation', '<p>Contrôle au manomètre la pression à la main <b>directe</b> (jaune) pendant un freinage : la différence avec le pilotage doit correspondre au réglage d’<b>harmonisation</b> (0 à 1 bar). Après échange de la VCR, <b>toujours contrôler et régler</b> ce dispositif (la même VCR se monte sur des véhicules aux réglages différents). Contrôle aussi le correcteur de la remorque et ses freins au banc.</p>');
  P.end_rupture = end('bad', 'Freinage d’urgence de la remorque', '<p>Fuite sur la conduite <b>directe</b> + freinage = la fonction <b>rupture</b> de la VCR fait chuter la conduite automatique et la VRU serre la remorque. Fuite ou mauvais accouplement de la conduite automatique : même effet. Cherche la fuite (flexibles, mains, joints).</p>');
  P.end_banc_ok = end('ok', 'Freinage conforme au banc', '<p>Contrôle aussi l’état des garnitures, tambours / disques, la course des tiges de vases et le réglage des leviers.</p>');
  P.end_banc = end('bad', 'Freinage PL à reprendre', '<p>Côté faible : réglage des leviers (rattrapage), cames grippées, garnitures grasses ou usées, vase / cylindre, valve relais, correcteur (réglage selon la charge), pression délivrée (manomètre sur la prise d’épreuve pendant le freinage).</p>');
  P.end_alt24 = end('bad', 'Charge 24 V', '<p>Courroie, alternateur (régulateur, diodes), câbles et masses (chutes de tension sous courant). Voyant de charge, tension 28 à 29,5 V après réparation.</p>');
  P.end_bat24 = end('bad', 'Batteries 24 V', '<p>Recharge chaque batterie séparément, teste-les ; remplace-les <b>par paire</b> (même référence, même âge). Contrôle le pont entre les deux, les cosses et le coupe-batterie.</p>', '<p>Démarrage avec une source 24 V : voir <b>🆘 Dépannage d’urgence PL</b>.</p>');
  P.end_24_ok = end('ok', 'Électricité 24 V correcte', '<p>Si le démarreur ne tourne pas : contacteur (cours AGA 01 : enroulement d’appel, enroulement de maintien — bruit de « mitraillette » = maintien coupé), commande, chutes de tension (module 🔋, valeurs à doubler).</p>');
  P.end_can = end('warn', 'Réseau J1939', '<p>Localise le calculateur muet avec l’outil constructeur, puis mesure le réseau comme sur un VL (module 🔌 Multiplexage).</p>');
  P.end_susp_fuite = end('bad', 'Fuite de suspension', '<p>Soufflets (fissures, frottements), raccords, valve de nivellement ; eau savonneuse. La <b>valve de barrage</b> doit conserver la pression de freinage.</p>');
  P.end_susp_niv = end('bad', 'Nivellement', '<p>Tige de la valve de nivellement (déformée, déréglée, rotule), réglage de la hauteur de travail (doc constructeur), soufflet percé d’un côté ; ECAS : capteurs de hauteur et calibrage à la valise. Pense au <b>correcteur de freinage pneumatique</b> qui dépend de la pression des soufflets : à régler selon la plaque.</p>');
  P.end_susp_cde = end('bad', 'Commande monte / baisse', '<p>Robinet distributeur rotatif, <b>valve de coupure</b> (limitation de course), pression disponible (valve de barrage), commande électronique (défauts à la valise).</p>');
  P.end_mot = end('warn', 'Moteur PL', '<p>Suis le module correspondant ; lis les défauts avec l’outil constructeur PL (voir la fiche de la marque).</p>');

  /* ========================= CAPTEURS ========================= */
  mes('u_12', 'Tension d’alimentation 12 V au connecteur (contact mis ou moteur tournant)', 'V', 11, 14.8, 'Alimentation par relais (souvent le relais double / principal) : tension batterie. Sur PL : 24 V pour les éléments alimentés en direct.');
  mes('u_ref_ctn', 'Tension au connecteur débranché, côté faisceau (contact mis)', 'V', 4.5, 5.2, 'Le calculateur alimente la sonde à travers une résistance de tirage : ≈ 5 V à vide.');
  mes('u_mc', 'Chute de tension de la masse capteur (broche de masse → borne – batterie, contact mis)', 'V', 0, 0.2, 'La masse capteur passe souvent par le calculateur : moins de 0,2 V.');
  mes('u_sig_h', 'Signal au niveau haut (capteur Hall)', 'V', null, null);
  function capStep(title, why, how, ms, okMsg) { return { type: 'measure', title: title, why: why, how: how, measures: ms,
    decide: function (m) { var msg = [];
      ms.forEach(function (k) { var r = m(k); if (r.st === 'ok') return; var t = {
        u_5v: r.dir === 'low' ? '5 V absent ou faible : fil d’alimentation ou calculateur — ou un autre capteur sur la même alimentation 5 V en court-circuit (débranche-les un par un : si le 5 V revient, c’est lui).' : '5 V trop haut : court-circuit au + ou masse capteur coupée.',
        u_12: 'Alimentation 12 V absente ou faible : fusible, relais (relais double / principal), fil.',
        u_mc: 'Masse capteur résistante : fil, connecteur, calculateur.',
        u_ref_ctn: 'Pas de tension de tirage : fil coupé ou calculateur.',
        u_sig_lo: 'Le signal ne descend pas au niveau bas : capteur ou court-circuit au +.',
        r_ind: 'Résistance du bobinage hors tolérance : capteur HS.', r_iso: 'Défaut d’isolement : capteur HS.', u_ac: 'Pas assez de tension générée : entrefer, cible, capteur.',
        u_sig_p: 'Signal au repos hors plage : capteur ou alimentation.', u_pot_lo: 'Signal au repos incorrect.', u_pot_hi: 'Signal à fond incorrect.',
        r_ctn20: 'Résistance à froid hors tolérance : sonde HS (compare à sa courbe).', r_ctn80: 'Résistance à chaud hors tolérance : sonde HS.', r_chauf: 'Chauffage de sonde HS.' }[k] || (D.MEASURES[k].label + ' hors tolérance.');
        msg.push(t); });
      if (ms.indexOf('u_sig_h') >= 0 && m('u_sig_h').v < 3.5) msg.push('Niveau haut trop faible (' + r1(m('u_sig_h').v) + ' V) : le signal doit monter vers 5 V (ou la tension d’alimentation selon le montage) — capteur, fil de signal à la masse.');
      if (msg.length) return { v: 'bad', msg: msg.join(' '), next: 'end_cap_bad' };
      return { v: 'ok', msg: okMsg, next: 'end_cap_ok' }; } }; }
  var C = {};
  C.start = { type: 'choice', title: 'Quel type de capteur ?', why: '<p>Chaque famille de capteur a sa <b>façon d’être alimentée</b> et son <b>signal</b>. La démarche est toujours la même : <b>alimentation</b>, <b>masse</b>, <b>signal</b>, puis le capteur lui-même. Les valeurs sont des valeurs types : la tension exacte d’un capteur se lit sur le <b>schéma</b> du véhicule.</p>',
    choices: [['Inductif (régime / PMH, ABS passif) — 2 fils, sans alimentation', 'c_ind'], ['Effet Hall (phase, vitesse) — 3 fils', 'c_hall'], ['Pression (admission, rail, FAP, clim) — 3 fils, 5 V', 'c_pres'], ['Potentiomètre (pédale, papillon, recopie EGR) — 5 V', 'c_pot'], ['Sonde de température CTN — 2 fils', 'c_ctn'], ['Débitmètre d’air à film chaud', 'c_deb'], ['Sonde lambda', 'c_lam'], ['Capteur « intelligent » sur bus (NOx, batterie, pluie, angle volant)', 'c_bus']] };
  C.c_ind = capStep('Capteur inductif', '<p><b>Pas d’alimentation</b> : un aimant et une bobine produisent une tension <b>alternative</b> au passage des dents (cours GD 22 : capteur de régime inductif sur le volant moteur, 2 fausses dents pour le PMH). Blindage relié d’un seul côté.</p>', '<p>Capteur débranché : résistance du bobinage et isolement ; puis tension alternative au démarreur.</p>', ['r_ind', 'r_iso', 'u_ac'], 'Capteur inductif correct : contrôle l’entrefer, la cible et le faisceau (continuité, blindage).');
  C.c_hall = { type: 'choice', title: 'Capteur Hall : quelle alimentation sur le schéma ?', why: '<p>Le capteur Hall contient une électronique : il faut l’<b>alimenter</b>. Selon le calculateur, l’alimentation est de <b>5 V</b> (régulée par le calculateur, très courant sur les capteurs moteur) ou de <b>12 V</b> (tension batterie via relais). Le signal est <b>carré</b> : le calculateur tire souvent le fil de signal à 5 V et le capteur le met à la masse au passage de la cible. ABS actif à 2 fils : signal en courant (≈ 7 / 14 mA, module 🛑).</p>',
    choices: [['5 V', 'c_hall5'], ['12 V (ou 24 V sur PL)', 'c_hall12'], ['Je ne sais pas : je mesure', 'c_hall5']] };
  C.c_hall5 = capStep('Capteur Hall alimenté en 5 V', '<p>Connecteur branché (piquer par l’arrière), contact mis.</p>', '<ol><li>Tension entre l’alimentation et la masse du capteur.</li><li>Masse capteur → borne – batterie.</li><li>Signal en tournant lentement le moteur (ou la roue) : niveau bas et niveau haut (ou oscilloscope).</li></ol>', ['u_5v', 'u_mc', 'u_sig_lo', 'u_sig_h'], 'Alimentation, masse et signal corrects : contrôle le fil de signal jusqu’au calculateur et l’entrefer (certains sont réglables).');
  C.c_hall12 = capStep('Capteur Hall alimenté en 12 V', '<p>Connecteur branché, contact mis.</p>', '<ol><li>Tension d’alimentation 12 V.</li><li>Masse capteur.</li><li>Signal niveau bas / haut en tournant lentement.</li></ol>', ['u_12', 'u_mc', 'u_sig_lo', 'u_sig_h'], 'Alimentation, masse et signal corrects : contrôle le fil de signal et la cible.');
  C.c_pres = capStep('Capteur de pression (piézo-résistif)', '<p>3 fils : <b>5 V de référence</b>, masse capteur, signal <b>proportionnel à la pression</b> (≈ 0,5 à 4,5 V). Cours GD 21 : signal compris entre 0 et 5 V. Plusieurs capteurs partagent souvent la même alimentation 5 V.</p>', '<p>Connecteur branché, contact mis, moteur arrêté (pression nulle ou atmosphérique).</p>', ['u_5v', 'u_mc', 'u_sig_p'], 'Capteur correct au repos : compare ensuite le signal à la valise avec la pression réelle (manomètre) moteur tournant.');
  C.c_pot = capStep('Potentiomètre', '<p>3 fils : <b>5 V</b>, masse, curseur. Pédale d’accélérateur : <b>2 pistes</b> (2 alimentations 5 V séparées) comparées en permanence ; cours GD 22 : une piste HS = mode dégradé (2 500 tr/min maxi), deux pistes HS = régime fixe 1 300 tr/min.</p>', '<p>Connecteur branché, contact mis : alimentation, masse, signal pédale relâchée puis enfoncée lentement (sans trou).</p>', ['u_5v', 'u_mc', 'u_pot_lo', 'u_pot_hi'], 'Piste correcte : contrôle la 2ᵉ piste de la même façon (souvent la moitié de la 1ʳᵉ ou en sens inverse).');
  C.c_ctn = capStep('Sonde CTN', '<p>2 fils, pas d’alimentation séparée : le calculateur envoie ≈ <b>5 V à travers une résistance de tirage</b> ; la sonde fait chuter cette tension quand la température monte (résistance qui baisse).</p>', '<ol><li>Sonde débranchée, contact mis : tension côté faisceau.</li><li>Résistance de la sonde à froid et moteur chaud.</li></ol>', ['u_ref_ctn', 'r_ctn20', 'r_ctn80'], 'Sonde et tirage corrects : compare la température lue à la valise avec la réalité.');
  C.c_deb = capStep('Débitmètre à film chaud', '<p>L’élément chauffé est refroidi par l’air : le courant de chauffage donne la masse d’air. Alimentation <b>12 V</b> (via relais), masse, signal (tension 0 à 5 V sur les anciens, <b>fréquence</b> sur les récents) ; certains ont aussi un <b>5 V</b> de référence et une sonde de température d’air CTN intégrée (cours GD 22).</p>', '<p>Connecteur branché, moteur tournant : alimentation et masse. Signal : comparer à la valise (kg/h ou mg/cp) avec la valeur attendue.</p>', ['u_12', 'u_mc'], 'Alimentation et masse correctes : si la valeur lue est incohérente (trop faible en accélération), débitmètre encrassé ou prise d’air.');
  C.c_lam = capStep('Sonde lambda', '<p><b>Chauffage</b> : 12 V (via relais) et masse pilotée en RCO par le calculateur. <b>Signal</b> (sonde à oxyde de zirconium) : la sonde produit elle-même 0,1 à 0,9 V. Sonde <b>large bande</b> (5 ou 6 fils) : courant de pompage géré par le calculateur, se contrôle à la valise.</p>', '<p>Contact mis : alimentation du chauffage ; sonde débranchée : résistance de chauffage.</p>', ['u_12', 'r_chauf'], 'Chauffage correct : contrôle le signal moteur chaud (module 🌫️ Antipollution → sonde lambda).');
  C.c_bus = capStep('Capteur sur bus (CAN / LIN)', '<p>Capteurs NOx, capteur de batterie (IBS), capteur de pluie, angle volant… : alimentés en <b>12 V</b> (24 V sur certains PL) avec une masse, et ils envoient leur valeur par un <b>bus</b> (CAN ou LIN). On ne mesure pas le signal au multimètre : on contrôle alimentation, masse et communication.</p>', '<p>Connecteur branché, contact mis.</p>', ['u_12', 'u_mc'], 'Alimentation et masse correctes : contrôle la ligne CAN / LIN (module 🔌 Multiplexage) puis le capteur (valeur plausible à la valise).');
  C.end_cap_ok = end('ok', 'Capteur : alimentation et masse correctes', '<p>Si la valeur lue reste fausse : capteur (dérive), connecteur (broches desserrées, oxydation), fil de signal. Compare toujours la valeur à la valise avec une <b>mesure de référence</b> (manomètre, thermomètre).</p>');
  C.end_cap_bad = end('bad', 'Capteur ou son circuit', '<p>Répare l’élément trouvé (voir le verdict), puis relis les défauts et la valeur du capteur à la valise.</p>');

  function add(id, icon, titre, sous, steps, comprendre) { D.MODULES[id] = { id: id, icon: icon, titre: titre, sous: sous, start: 'start', steps: steps, comprendre: comprendre }; }
  add('pl', '🚛', 'Poids lourds (PL / SPL)', 'Freinage pneumatique, frein de parc, remorque, banc, 24 V, J1939, suspension pneumatique, dépannage', P,
    '<h3>Réglementation (cours AGB 03)</h3><ul><li>Au moins <b>2 commandes</b> et <b>2 circuits</b> indépendants (un défaillant : l’autre ≥ 30 % de l’efficacité).</li><li>Frein de stationnement à action <b>purement mécanique</b> : pente de <b>18 %</b> en solo, <b>12 %</b> en ensemble.</li><li>Remplissage des réservoirs en <b>6 à 11 min</b> ; après <b>8 actionnements</b> sans réalimentation, encore l’efficacité du frein de secours ; temps de réponse ≤ <b>0,6 s</b>.</li><li>Conduites automatique et directe : 8 bar maxi.</li></ul>' +
    '<h3>Code chiffré des orifices</h3><div class="tw"><table><tr><th>Chiffre</th><th>Rôle</th></tr><tr><td>0</td><td>Aspiration</td></tr><tr><td>1 (11, 12…)</td><td>Alimentation (entrée)</td></tr><tr><td>2 (21, 22…)</td><td>Utilisation (sortie)</td></tr><tr><td>3</td><td>Échappement (mise à l’air)</td></tr><tr><td>4 (41, 42…)</td><td>Pilotage</td></tr><tr><td>7</td><td>Antigel</td></tr><tr><td>81 / 82</td><td>Huile arrivée / retour</td></tr><tr><td>91 / 92</td><td>Eau arrivée / retour</td></tr></table></div>' +
    '<h3>Mains d’accouplement</h3><p><b>Rouge</b> = automatique (alimentation de la remorque) ; <b>jaune</b> = directe (commande de freinage).</p>' +
    '<div class="box piege"><b>⚠️ Sécurité</b><ul><li>Toujours <b>caler</b> un PL avant toute intervention sur le frein de parc.</li><li>Ne jamais démonter un cylindre à ressort.</li><li>Purger les réservoirs avant d’ouvrir un circuit (air sous pression).</li><li>Électricité 24 V : pas d’appareil 12 V.</li></ul></div>');
  add('capteurs', '📡', 'Capteurs : alimentations et contrôles', 'Inductif, Hall 5 V / 12 V, pression, potentiomètre, CTN, débitmètre, lambda, capteurs sur bus', C,
    '<h3>Alimentation par famille (valeurs types)</h3><div class="tw"><table><tr><th>Capteur</th><th>Alimentation</th><th>Signal</th></tr>' +
    '<tr><td>Inductif (régime, ABS passif)</td><td>Aucune</td><td>Tension alternative, augmente avec la vitesse</td></tr>' +
    '<tr><td>Hall (phase, vitesse)</td><td>5 V (calculateur) ou 12 V selon montage</td><td>Carré 0 / 5 V (ou 0 / 12 V)</td></tr>' +
    '<tr><td>ABS actif (2 fils)</td><td>Par le calculateur ABS</td><td>Courant ≈ 7 / 14 mA</td></tr>' +
    '<tr><td>Pression (admission, rail, FAP, clim)</td><td>5 V de référence</td><td>≈ 0,5 à 4,5 V proportionnel</td></tr>' +
    '<tr><td>Potentiomètre (pédale 2 pistes, papillon)</td><td>5 V (une alim par piste sur la pédale)</td><td>≈ 0,5 à 4,5 V</td></tr>' +
    '<tr><td>CTN (eau, air, carburant, huile)</td><td>≈ 5 V par résistance de tirage du calculateur</td><td>Tension qui baisse quand T° monte</td></tr>' +
    '<tr><td>Débitmètre film chaud</td><td>12 V (+ parfois 5 V de référence)</td><td>0 à 5 V ou fréquence</td></tr>' +
    '<tr><td>Sonde lambda</td><td>Chauffage 12 V (masse pilotée)</td><td>0,1 à 0,9 V (zircone) ; large bande : courant</td></tr>' +
    '<tr><td>Cliquetis (piézo)</td><td>Aucune</td><td>Tension alternative ; couple de serrage important</td></tr>' +
    '<tr><td>Capteurs sur bus (NOx, IBS, pluie…)</td><td>12 V (24 V sur certains PL)</td><td>Message CAN / LIN</td></tr></table></div>' +
    '<div class="box explic"><b>💡 Astuce</b><p>Plusieurs capteurs partagent souvent la <b>même alimentation 5 V</b> : si le 5 V manque sur plusieurs capteurs à la fois, un seul capteur en court-circuit peut en être la cause. Débranche-les un par un.</p></div>' +
    '<p class="small muted">Sur PL, les capteurs restent en 5 V ; les actionneurs sont en 24 V. Le schéma du véhicule fait toujours foi.</p>');

  var order = ['urgence', 'mux', 'capteurs', 'charge', 'meca', 'cr', 'anti', 'cles', 'dsft', 'frein', 'autres', 'pl'], old = D.MODULES, nm = {};
  order.forEach(function (k) { if (old[k]) nm[k] = old[k]; }); Object.keys(old).forEach(function (k) { if (!nm[k]) nm[k] = old[k]; });
  D.MODULES = nm;

  /* ========================= MARQUES PL + MÉTHODES DE CONTRÔLE ========================= */
  D.ARCHI.pl_j1939 = { nom: 'Poids lourd — SAE J1939', passerelle: 'Calculateur véhicule (nom selon la marque)',
    reseaux: [['CAN J1939 moteur / transmission (250 ou 500 kbit/s)', 'canhs'], ['CAN véhicule', 'canhs'], ['CAN freinage / châssis (EBS)', 'canhs'], ['CAN carrosserie / superstructure', 'canhs'], ['LIN (commandes, capteurs)', 'lin']],
    ecus: [['Calculateur moteur', 'CAN J1939 moteur / transmission (250 ou 500 kbit/s)', true], ['Boîte de vitesses robotisée', 'CAN J1939 moteur / transmission (250 ou 500 kbit/s)', false], ['Ralentisseur', 'CAN J1939 moteur / transmission (250 ou 500 kbit/s)', false], ['Calculateur véhicule (passerelle)', 'CAN véhicule', true], ['Tableau de bord', 'CAN véhicule', false], ['Tachygraphe', 'CAN véhicule', false], ['EBS / ABS', 'CAN freinage / châssis (EBS)', true], ['Suspension pneumatique (ECAS)', 'CAN freinage / châssis (EBS)', false], ['Module carrosserie / superstructure', 'CAN carrosserie / superstructure', true]],
    note: 'Architecture type d’un PL : réseaux J1939 séparés reliés par un calculateur véhicule. 24 V. Prise 16 broches ou ancienne prise 9 broches (A masse, B + batterie, C CAN H, D CAN L).' };
  var PLG = '🚛 Poids lourds (PL / SPL)';
  [['Renault Trucks', 'France', 'Gammes T, C, K, D ; anciens Premium, Kerax, Magnum, Midlum', 'Groupe Volvo : moteurs, calculateurs et outil de diagnostic communs avec Volvo Trucks.', 'Tech Tool (Groupe Volvo)'],
    ['Volvo Trucks', 'Suède', 'FH, FM, FMX, FL, FE', 'Groupe Volvo : base commune avec Renault Trucks.', 'Tech Tool (Groupe Volvo)'],
    ['Scania', 'Suède', 'Séries R, S, G, P, L', 'Groupe Traton (Volkswagen) avec MAN.', 'SDP3'],
    ['MAN', 'Allemagne', 'TGX, TGS, TGM, TGL', 'Groupe Traton (Volkswagen) avec Scania.', 'MAN-cats III'],
    ['DAF', 'Pays-Bas', 'XF, XG, XG+, XD, XB, CF, LF', 'Groupe Paccar : moteurs Paccar MX / PX.', 'DAVIE'],
    ['Iveco', 'Italie', 'S-Way, X-Way, T-Way, Eurocargo ; anciens Stralis, Trakker', 'Iveco Group : moteurs FPT (Cursor, Tector), communs avec d’autres engins.', 'E.A.SY'],
    ['Mercedes-Benz Trucks', 'Allemagne', 'Actros, Arocs, Atego, Econic, Unimog', 'Daimler Truck.', 'Xentry Truck']].forEach(function (b, i) {
    D.MARQUES.push({ id: 'pl' + i, nom: b[0], pays: b[1], groupe: PLG, archi: 'pl_j1939', boitier: 'Calculateur véhicule / passerelle (nom selon la marque)', sgw: 'Fonctions protégées par l’outil constructeur (accès atelier agréé)', modeles: b[2], partages: b[3], outil: b[4], pl: true });
  });

  var OUT = { 'Renault': 'CLIP ; documentation et arbres de diagnostic (ALP) : Dialogys', 'Dacia': 'CLIP ; documentation : Dialogys', 'Alpine': 'CLIP',
    'Peugeot': 'Diagbox (ex-PP2000)', 'Citroën': 'Diagbox (ex-Lexia)', 'DS': 'Diagbox', 'Opel': 'Modèles GM : GDS2 / Tech2 ; modèles sur base PSA : Diagbox',
    'Fiat': 'wiTECH 2 (anciens : Examiner)', 'Abarth': 'wiTECH 2', 'Alfa Romeo': 'wiTECH 2 (anciens : Examiner)', 'Lancia': 'wiTECH 2 / Examiner', 'Jeep': 'wiTECH 2', 'Maserati': 'Outil constructeur (groupe Stellantis)',
    'Volkswagen': 'ODIS (interface VAS) ; multimarque très répandu : VCDS', 'Audi': 'ODIS ; VCDS', 'Seat': 'ODIS ; VCDS', 'Cupra': 'ODIS', 'Skoda': 'ODIS ; VCDS', 'Porsche': 'PIWIS', 'Bentley': 'ODIS (groupe Volkswagen)', 'Lamborghini': 'Outil du groupe Volkswagen',
    'Toyota': 'Techstream (GTS sur les récents)', 'Lexus': 'Techstream / GTS', 'Daihatsu': 'Outil Toyota / Daihatsu', 'Nissan': 'Consult III plus', 'Mitsubishi': 'MUT-III', 'Honda': 'HDS (i-HDS)', 'Mazda': 'IDS / MDARS', 'Subaru': 'SSM4', 'Suzuki': 'SDT-II',
    'Hyundai': 'GDS / GDS Smart', 'Kia': 'KDS / GDS', 'Ford': 'IDS puis FDRS', 'Mercedes-Benz': 'Xentry (anciens : DAS)', 'Smart': 'Xentry', 'BMW': 'ISTA (codage : E-Sys)', 'Mini': 'ISTA', 'Rolls-Royce': 'ISTA',
    'Volvo': 'VIDA', 'Jaguar': 'SDD puis Pathfinder', 'Land Rover': 'SDD puis Pathfinder', 'Tesla': 'Toolbox (abonnement)', 'Saab': 'Tech2', 'Chevrolet (ex-Daewoo)': 'Tech2 / GDS2' };
  var MET = {
    'Renault Group': '<ul><li>Écrans <b>états et paramètres</b> et <b>commandes</b> (tests actionneurs).</li><li>Configurations et apprentissages : codage injecteurs, réinitialisation FAP, clés / carte avec code.</li><li>Méthode de réparation : arbres de localisation de panne (ALP).</li></ul>',
    'Stellantis': '<ul><li>Paramètres, tests actionneurs, <b>télécodage</b> du BSI après remplacement.</li><li>Apprentissages : codage injecteurs, additif FAP, déclaration de la batterie.</li><li>Récents : passerelle sécurisée (compte en ligne) pour effacer et écrire.</li></ul>',
    'Volkswagen Group': '<ul><li><b>Blocs de valeurs de mesure</b> et tests actionneurs.</li><li>Nombreuses <b>adaptations / codages</b> (papillon, EGR, batterie, <b>mode service</b> du frein de parc électrique).</li><li>Récents : diagnostic protégé (SFD) — accès en ligne pour certaines fonctions.</li></ul>',
    'BMW Group': '<ul><li>Test automatique des calculateurs, plans de contrôle guidés.</li><li><b>Déclaration de batterie</b> obligatoire après remplacement, programmation / codage des calculateurs.</li></ul>',
    'Mercedes-Benz Group': '<ul><li>Test rapide de tous les calculateurs, recherche de panne guidée.</li><li>Récents : fonctions protégées (compte en ligne).</li></ul>' };
  var GEN = '<p class="small">Pour toutes les marques : prise <b>OBD 16 broches</b> (CAN sur 6 / 14, K-Line sur 7), valise multimarque (Bosch, Texa, Autel, Launch, Delphi…) ou <b>pass-thru</b> avec le logiciel constructeur. La <b>documentation technique</b> (valeurs, schémas, méthodes) est accessible aux réparateurs sur le site d’information du constructeur (accès payant à la durée, obligation européenne).</p>';
  var CAP = '<p>Valeurs par famille de capteur (5 V de référence pour pression et position ; Hall en 5 V ou 12 V selon le calculateur ; inductif et cliquetis sans alimentation ; débitmètre et chauffage de sonde en 12 V) : voir le module <a href="#/mod/capteurs">📡 Capteurs</a>. La tension exacte d’un capteur se lit sur le <b>schéma électrique</b> du véhicule.</p>';
  var CAP_PL = '<p>Sur PL : capteurs moteur en <b>5 V</b> fournis par le calculateur ; actionneurs, relais et certains capteurs sur bus en <b>24 V</b>. Voir <a href="#/mod/capteurs">📡 Capteurs</a> et le schéma du véhicule.</p>';
  var MET_PL = '<ul><li>Lecture des défauts de tous les calculateurs J1939, paramètres, tests actionneurs.</li><li>Paramétrage (vitesse maxi, prises de force, superstructure), étalonnages (tachygraphe par un atelier agréé, suspension, EBS).</li><li>Contrôles pneumatiques au <b>manomètre sur les prises d’épreuve</b> (module 🚛).</li></ul>';
  D.MARQUES.forEach(function (m) {
    if (m.pl) { m.methode = MET_PL + GEN; m.capteurs = CAP_PL; return; }
    m.outil = OUT[m.nom] || 'Outil du constructeur (via son site d’information technique) ou valise multimarque récente';
    m.methode = (MET[m.groupe] || MET[(m.groupe || '').split(' ')[0]] || '<ul><li>Lecture des défauts et paramètres, tests actionneurs, apprentissages après remplacement (valise constructeur ou multimarque).</li></ul>') + GEN;
    m.capteurs = CAP;
  });
})();
