/* Diagnostic — modules CLÉS / ANTIDÉMARRAGE, MOTEUR (mécanique, allumage, préchauffage, refroidissement, lubrification),
   AUTRES SYSTÈMES, DÉPANNAGE D’URGENCE, et partie « après le diagnostic » (dépannage provisoire + remise en service).
   Valeurs = valeurs TYPES (la valeur constructeur prime). Frein de parking électrique : procédure de desserrage d’urgence
   ZF Aftermarket (ne jamais alimenter directement l’actionneur). Programmation de clés : accès réservé aux professionnels
   certifiés SERMI (obligatoire en France depuis novembre 2024). */
(function () {
  var D = window.DIAG, M = D.MEASURES;
  function mes(id, label, unit, min, max, note) { M[id] = { id: id, label: label, unit: unit, min: min, max: max, note: note || '' }; }
  function r1(n) { return String(Math.round(n * 10) / 10).replace('.', ','); }
  function end(v, title, html, dep) { var s = { type: 'end', v: v, title: title, html: html }; if (dep) s.dep = dep; return s; }
  function urg(title, html) { return { type: 'end', v: 'info', title: title, html: html, noApres: true }; }
  function info(title, html, bouton, next) { return { type: 'info', title: title, html: html, bouton: bouton, next: next }; }

  /* ---------- Après le diagnostic (affiché sur chaque conclusion) ---------- */
  D.APRES = '<ol><li><b>Réparer</b> : pièce de qualité équivalente, couples de serrage constructeur, joints et vis à usage unique neufs.</li><li><b>Effacer les défauts</b> à la valise.</li><li>Faire les <b>apprentissages, codages ou initialisations</b> demandés (valise ou notice).</li><li><b>Recontrôler la mesure</b> qui était hors tolérance : elle doit être revenue dans les valeurs.</li><li><b>Essai routier</b> dans les conditions où la panne apparaissait (à froid, à chaud, en charge…).</li><li><b>Relire les défauts</b> après l’essai.</li><li><b>Enregistrer</b> le diagnostic dans l’historique du véhicule (bouton ci-dessous) en notant la pièce changée.</li></ol>';
  var AP = {
    mux: '<p><b>Spécifique multiplexage</b> : après remplacement d’un calculateur, <b>téléchargement / codage</b> et appairage (antidémarrage) ; contrôle que tous les calculateurs répondent à la valise.</p>',
    cr: '<p><b>Spécifique common rail</b> : purge du circuit basse pression, <b>codage des injecteurs</b> remplacés, contrôle d’étanchéité moteur tournant <b>en restant à distance</b> des raccords HP, pression de rail consigne / mesurée à nouveau.</p>',
    anti: '<p><b>Spécifique antipollution</b> : apprentissage de la vanne EGR, réinitialisation de l’additif FAP (PSA), régénération forcée, apprentissages SCR demandés par la valise.</p>',
    dsft: '<p><b>Spécifique DSFT</b> : nouveau relevé de géométrie après réglage (à imprimer), volant droit, essai routier ; calibrage du capteur d’angle volant et des aides à la conduite (caméra) si le constructeur le demande.</p>',
    frein: '<p><b>Spécifique freinage</b> : purge, pédale ferme moteur arrêté et tournant, <b>rodage</b> des plaquettes et disques neufs (éviter les freinages violents les premières centaines de km), passage au banc.</p>',
    charge: '<p><b>Spécifique charge / démarrage</b> : déclarer la batterie neuve à la valise si le véhicule a un capteur de batterie, recontrôler la tension de charge et le courant de fuite.</p>'
  };
  Object.keys(AP).forEach(function (k) { if (D.MODULES[k]) D.MODULES[k].apres = AP[k]; });

  /* ---------- Dépannage provisoire sur les conclusions existantes ---------- */
  function dep(mod, id, html) { var s = D.MODULES[mod] && D.MODULES[mod].steps[id]; if (s) s.dep = html; }
  dep('mux', 'end_wire', '<ul><li>Fil coupé : épissure <b>soudée</b> et gaine thermorétractable (pas de domino).</li><li>Fils CAN : garder la <b>torsade</b>, détorsader le moins possible, réparer les deux fils au même endroit.</li><li>Masse oxydée : nettoyer, resserrer, graisse de protection.</li></ul>');
  dep('cr', 'end_elec', '<p>Démarrage avec câbles ou booster : voir le module <b>🆘 Dépannage d’urgence</b>.</p>');
  dep('cr', 'end_air', '<ul><li>Resserrer les raccords et colliers accessibles, contrôler le joint du filtre.</li><li>Purger avec la pompe d’amorçage (poire) jusqu’à ce qu’elle devienne dure, ou contact mis plusieurs fois (pompe électrique).</li></ul>');
  dep('cr', 'end_bp', '<ul><li>Gazole figé (paraffinage, grand froid) : mettre le véhicule au chaud ; ne pas ajouter d’essence dans le gazole d’un moteur moderne.</li><li>Filtre colmaté : le remplacer et purger.</li></ul>');
  dep('cr', 'end_turbo', '<ul><li>Durite déboîtée : la remettre en place et serrer le collier.</li><li>Sinon, rouler doucement en mode dégradé jusqu’à l’atelier (surveiller la fumée et la température).</li></ul>');
  dep('cr', 'end_inj', '<p>Pas de dépannage fiable : un injecteur qui fuit fortement peut empêcher le démarrage ou abîmer le moteur. Remorquage si le moteur ne tourne pas rond.</p>');
  dep('anti', 'end_fap_trajet', '<p>Si le voyant l’autorise (notice) : rouler 20 à 30 min sur voie rapide à régime soutenu, sur un rapport inférieur, pour déclencher la régénération. Voyant rouge ou mode dégradé fort : ne pas insister, atelier.</p>');
  dep('anti', 'end_egr', '<p>Rouler doucement en mode dégradé jusqu’à l’atelier. <b>Supprimer ou neutraliser un système antipollution est interdit</b> (et refusé au contrôle technique).</p>');
  dep('anti', 'end_scr', '<p>Surveille le <b>compteur de démarrages / km restants</b> affiché : à zéro, le moteur ne redémarre plus après un arrêt. Faire le plein d’AdBlue neuf et réparer avant.</p>');
  dep('dsft', 'u_sousg', '<p>Regonfler à la pression constructeur (à froid) et rechercher la fuite ; crevaison : voir <b>🆘 Dépannage d’urgence</b>.</p>');
  dep('frein', 'end_fuite', '<p><b>Ne pas rouler</b> avec une pédale longue ou un niveau sous le mini : remorquage.</p>');
  dep('frein', 'end_mc', '<p><b>Ne pas rouler</b> : risque de perte de freinage. Remorquage.</p>');
  dep('frein', 'end_parc_elec', '<p>Frein de parking électrique bloqué ou véhicule sans batterie : voir <b>🆘 Dépannage d’urgence → frein de parking électrique</b>.</p>');
  dep('charge', 'end_bat', '<p>Démarrer avec des câbles ou un booster (<b>🆘 Dépannage d’urgence</b>), puis recharger au chargeur.</p>');
  dep('charge', 'end_alt', '<p>Batterie chargée, <b>couper tous les consommateurs</b> (clim, dégivrage, sièges chauffants, radio) et rouler directement jusqu’à l’atelier : l’autonomie est limitée. Courroie cassée : si elle entraîne aussi la pompe à eau, surveiller la température et s’arrêter.</p>');
  dep('charge', 'end_cable', '<p>Nettoyer les cosses (brosse ; eau chaude + bicarbonate sur le sulfate), resserrer, protéger à la graisse.</p>');
  dep('charge', 'end_cmd', '<ul><li>Boîte auto : démarrer en <b>N</b>, bouger le levier.</li><li>Boîte manuelle : pédale d’embrayage enfoncée à fond.</li><li>Voyant antidémarrage : voir le module <b>🔑 Clés et antidémarrage</b>.</li></ul>');
  dep('charge', 'end_dem', '<ul><li>En dépannage seulement : quelques petits coups sur le démarreur pendant qu’un aide actionne la clé (balais collés).</li><li>Démarrage « à la poussette » : <b>boîte manuelle uniquement</b> (2ᵉ rapport, embrayer d’un coup) ; jamais en boîte auto, hybride ou électrique.</li></ul>');

  /* ========================= CLÉS ET ANTIDÉMARRAGE ========================= */
  mes('u_pile', 'Tension de la pile de la clé', 'V', 2.8, 3.4, 'Pile lithium 3 V (CR2032, CR2025, CR1620… : référence gravée) : neuve ≈ 3,0 à 3,3 V ; sous ≈ 2,8 V, portée réduite et clé mains libres mal détectée.');
  function pileStep(next) { return { type: 'measure', title: 'Pile de la clé', why: '<p>La pile alimente uniquement la <b>télécommande</b> (émetteur radio) et la détection <b>mains libres</b>. Le <b>transpondeur</b> d’antidémarrage, lui, fonctionne <b>sans pile</b> (il est alimenté par le champ de l’antenne du véhicule).</p>',
    how: '<p>Ouvre la clé (petit tournevis dans la fente), voltmètre sur la pile. Vérifie aussi les contacts du support (oxydation) et le sens de la pile.</p>', measures: ['u_pile'],
    decide: function (m) { if (m('u_pile').st === 'bad' && m('u_pile').dir === 'low') return { v: 'bad', msg: 'Pile faible (' + r1(m('u_pile').v) + ' V) : remplace-la.', next: 'end_pile' }; return { v: 'ok', msg: 'Pile correcte : on continue.', next: next }; } }; }
  var K = {};
  K.start = { type: 'choice', title: 'Quel est le problème ?', why: '<p>Une clé moderne contient <b>deux systèmes indépendants</b> : la <b>télécommande</b> (radio UHF, ≈ 433 MHz en Europe, code tournant) qui ouvre / ferme, et le <b>transpondeur</b> (puce passive) lu par l’<b>antidémarrage</b>. Une clé peut donc ouvrir mais ne pas démarrer, ou l’inverse.</p>',
    choices: [['La télécommande n’ouvre plus / ne ferme plus', 'k_pile_tel'], ['Clé non reconnue : voyant antidémarrage, pas de démarrage ou le moteur cale après 1 à 2 s', 'k_2e'], ['Clé mains libres / carte non détectée', 'k_pile_ml'], ['Antivol de direction bloqué / défaut antivol de direction', 'end_elv'], ['Après coupure de batterie : télécommande, lève-vitres ou autres fonctions déréglés', 'k_batt'], ['Ajouter ou remplacer une clé, clé perdue', 'end_prog']] };
  K.k_pile_tel = pileStep('k_tel');
  K.k_pile_ml = pileStep('k_ml');
  K.k_tel = { type: 'choice', title: 'Pile bonne : que se passe-t-il ?', why: '<p>À chaque appui, la télécommande envoie un <b>code tournant</b> (qui change à chaque fois) au récepteur du véhicule (BSI / UCH / module de confort). Trop d’appuis hors de portée = télécommande <b>désynchronisée</b>. Si <b>aucune</b> clé ne marche, c’est le véhicule (récepteur, alimentation) ou une <b>perturbation radio</b> locale.</p>',
    choices: [['La 2ᵉ clé fonctionne, pas celle-ci', 'k_resync'], ['Aucune clé ne fonctionne', 'end_recept'], ['Le témoin (LED) de la clé ne s’allume plus', 'end_cle_hs']] };
  K.k_resync = info('Resynchroniser la télécommande', '<p>La procédure dépend du constructeur : <b>suis celle de la notice</b>. Exemple courant chez PSA : couper le contact, remettre le contact, appuyer aussitôt quelques secondes sur le bouton de verrouillage, couper le contact et retirer la clé. Beaucoup de véhicules récents se resynchronisent seuls après un appui près du véhicule ou demandent la valise.</p>', 'J’ai fait la procédure', 'k_res2');
  K.k_res2 = { type: 'choice', title: 'Résultat de la resynchronisation', choices: [['La télécommande fonctionne', 'end_ok'], ['Toujours pas', 'end_cle_hs']] };
  K.k_batt = info('Réinitialisations après coupure de batterie', '<ul><li><b>Lève-vitres séquentiels</b> (anti-pincement) : descendre complètement, remonter et <b>maintenir</b> la commande quelques secondes en butée haute, pour chaque vitre.</li><li><b>Toit ouvrant</b>, rétroviseurs à mémoire : procédure de la notice.</li><li><b>Télécommande</b> : resynchronisation (étape précédente) si besoin.</li><li><b>Code autoradio</b>, horloge.</li><li><b>Direction électrique / ESP</b> : sur certains véhicules, tourner le volant de butée à butée ou rouler quelques mètres pour réapprendre l’angle volant.</li><li>Moteur : laisser le contact mis quelques secondes puis le ralenti se stabiliser (apprentissage du papillon).</li></ul>', 'Terminer', 'end_ok');
  K.k_2e = { type: 'choice', title: 'Essai avec une autre clé', why: '<p>À la mise du contact, l’<b>antenne</b> (bague autour du barillet, lecteur de carte ou antennes mains libres) alimente et lit le <b>transpondeur</b>. Le BSI / UCH vérifie le code puis <b>autorise le calculateur moteur</b> par un échange codé sur le CAN. En cas de refus : voyant antidémarrage (clé) qui clignote, démarreur bloqué ou injection coupée juste après le démarrage.</p>',
    choices: [['La 2ᵉ clé démarre le véhicule', 'end_transp'], ['Aucune clé ne démarre', 'k_ant'], ['Je n’ai qu’une clé', 'k_ant']] };
  K.k_ant = info('Aucune clé reconnue : contrôles', '<ol><li><b>Batterie</b> ≥ 12,4 V : une tension faible perturbe la lecture (module 🔋).</li><li><b>Valise</b> : défauts du BSI / UCH et du calculateur moteur (« antidémarrage », « code non reçu », « clé non reconnue »).</li><li><b>Antenne de transpondeur</b> : connecteur, faisceau, fixation autour du barillet.</li><li><b>Communication</b> entre le BSI / UCH et le calculateur moteur : module <b>🔌 Multiplexage</b>.</li><li>Calculateur moteur ou BSI <b>remplacé / reprogrammé</b> : il doit être appairé (apprentissage).</li></ol>', 'Conclusion', 'end_antid');
  K.k_ml = { type: 'choice', title: 'Mains libres : que se passe-t-il ?', why: '<p>Quand on touche la poignée ou appuie sur Start, des <b>antennes basse fréquence</b> (≈ 125 kHz, portes, habitacle, coffre) interrogent la clé, qui répond par radio. Pile faible, perturbations (téléphone ou objet métallique contre la clé) ou antenne HS empêchent la détection.</p>',
    choices: [['Ne marche pas à une seule porte ou au coffre', 'end_ant_ml'], ['Démarrage refusé : « clé non détectée »', 'k_secours'], ['Ne marche nulle part', 'k_2e']] };
  K.k_secours = info('Démarrage de secours', '<p>Le transpondeur fonctionne sans pile : <b>pose la clé contre la zone de secours</b> indiquée dans la notice (colonne de direction, console, dessous du volant, ou bouton Start directement avec la clé), ou <b>insère la carte</b> dans son lecteur (Renault), puis démarre. Si ça démarre : pile ou antennes mains libres ; sinon : antidémarrage.</p>', 'Suite', 'k_2e');
  K.end_pile = end('warn', 'Pile de clé à remplacer', '<p>Même référence (gravée sur la pile), bon sens (+ visible en général), contacts propres. Pas besoin de reprogrammer la clé dans la grande majorité des cas.</p>', '<p>En attendant : ouvrir avec la <b>lame mécanique</b> et démarrer en <b>position de secours</b> (clé contre la zone indiquée).</p>');
  K.end_cle_hs = end('bad', 'Télécommande de la clé HS', '<p>Contrôle l’intérieur de la clé : soudures du support de pile, contacts des boutons, oxydation (clé tombée dans l’eau). Sinon, <b>boîtier neuf</b> (on garde souvent le transpondeur) ou clé neuve à programmer.</p>', '<p>Ouvrir avec la <b>lame mécanique</b> (barillet parfois caché sous un cache de la poignée conducteur), démarrer normalement (le transpondeur ne dépend pas de la télécommande).</p>');
  K.end_recept = end('bad', 'Récepteur ou perturbation radio', '<p>Essaie <b>ailleurs</b> (certains lieux sont brouillés : antennes, parkings). Sinon : fusible et alimentation du récepteur / BSI / UCH, antenne de réception, défauts à la valise.</p>');
  K.end_transp = end('bad', 'Transpondeur de la clé', '<p>La clé en cause a un transpondeur HS ou <b>non appris</b> (clé effacée) : réapprentissage ou clé neuve programmée par un professionnel équipé.</p>', '<p>Utiliser la 2ᵉ clé.</p>');
  K.end_antid = end('bad', 'Défaut d’antidémarrage (véhicule)', '<p>Répare l’élément trouvé (antenne, faisceau, communication, appairage). Les opérations d’apprentissage touchent à la <b>sécurité du véhicule</b> : elles demandent la valise et le code d’accès, réservés aux professionnels accrédités (certification <b>SERMI</b>, obligatoire en France).</p>', '<p>Pas de contournement possible (c’est le principe de l’antidémarrage) : <b>remorquage</b>.</p>');
  K.end_ant_ml = end('bad', 'Antenne ou capteur de poignée', '<p>Antenne / capteur de la poignée concernée, faisceau dans le <b>soufflet de porte</b> (fils cassés à force d’ouvertures), connecteur. Contrôle à la valise (test des antennes si disponible).</p>', '<p>Ouvrir avec la télécommande ou la lame mécanique.</p>');
  K.end_elv = end('bad', 'Antivol de direction (électrique ou mécanique)', '<ul><li>Volant contraint (roues braquées contre un trottoir) : <b>tourner légèrement le volant</b> à gauche / droite en même temps qu’on tourne la clé ou appuie sur Start.</li><li>Antivol électrique (ELV) : batterie bien chargée, défauts à la valise ; c’est une pièce de sécurité, son remplacement demande un <b>appairage</b>.</li></ul>', '<p>Volant manœuvré pendant le démarrage ; batterie rechargée ou booster.</p>');
  K.end_prog = urg('Ajouter ou remplacer une clé', '<ul><li>Une clé neuve = <b>lame taillée</b> au code du véhicule + <b>transpondeur appris</b> par le véhicule + parfois <b>télécommande</b> apprise séparément.</li><li>L’apprentissage demande une valise avec fonctions de sécurité et le <b>code d’accès</b> (carte code / code PIN). Depuis novembre 2024, en France, l’accès à ces fonctions est réservé aux professionnels <b>certifiés SERMI</b> (concession ou réparateur accrédité), sur justificatif de propriété.</li><li>Clé perdue : faire <b>effacer la clé perdue</b> de la mémoire du véhicule (sinon elle démarre toujours la voiture).</li><li>Après l’opération, <b>tester toutes les clés</b> : ouverture, fermeture, démarrage.</li></ul>');
  K.end_ok = end('ok', 'Clés fonctionnelles', '<p>Teste toutes les clés (ouverture, fermeture, démarrage) et remplace les piles faibles en même temps.</p>');

  /* ========================= MOTEUR : MÉCANIQUE ET AUXILIAIRES ========================= */
  mes('r_bob_p', 'Bobine : résistance du primaire', 'Ω', 0.3, 1.5, 'Valeur type 0,3 à 1,5 Ω. Bobines à électronique intégrée (3 ou 4 broches) : non mesurables à l’ohmmètre.');
  mes('r_bob_s', 'Bobine : résistance du secondaire (entre sortie HT et primaire, en kΩ)', 'kΩ', 5, 15, 'Valeur type 5 à 15 kΩ. Entre la valeur en kΩ (ex. 8,5).');
  mes('pre1', 'Bougie de préchauffage n°1', 'Ω', 0.1, 2.5, 'Valeur type : quelques dixièmes d’ohm à ≈ 2 Ω selon le type. OL = bougie coupée. Compare les bougies entre elles.');
  mes('pre2', 'Bougie de préchauffage n°2', 'Ω', 0.1, 2.5, ''); mes('pre3', 'Bougie de préchauffage n°3', 'Ω', 0.1, 2.5, ''); mes('pre4', 'Bougie de préchauffage n°4', 'Ω', 0.1, 2.5, '');
  mes('p_huile_ral', 'Pression d’huile au ralenti, moteur chaud', 'bar', 0.8, Infinity, 'Valeur type : au moins ≈ 1 bar au ralenti chaud. Utilise la valeur constructeur.');
  mes('p_huile_2k', 'Pression d’huile à ≈ 2 000 à 3 000 tr/min, moteur chaud', 'bar', 2, Infinity, 'Valeur type : ≈ 2 à 4 bar. Utilise la valeur constructeur.');
  mes('comp1', 'Compression cylindre 1', 'bar', null, null); mes('comp2', 'Compression cylindre 2', 'bar', null, null);
  mes('comp3', 'Compression cylindre 3', 'bar', null, null); mes('comp4', 'Compression cylindre 4', 'bar', null, null);

  var E = {};
  E.start = { type: 'choice', title: 'Quel est le symptôme ?', why: '<p>Ce module couvre la partie <b>mécanique et les auxiliaires</b> du moteur : allumage (essence), préchauffage (diesel), refroidissement, lubrification et compression. L’injection diesel est dans <b>⛽ Common rail</b>, les capteurs dans <b>🔌 Multiplexage</b>.</p>',
    choices: [['Ratés, moteur qui broute (essence)', 'm_rat'], ['Diesel : démarrage difficile à froid, fumée blanche au démarrage', 'm_pre'], ['Surchauffe, perte de liquide, chauffage froid', 'm_ref'], ['Voyant de pression d’huile, bruit du bas moteur', 'm_huile'], ['Consommation d’huile, perte de puissance, compression', 'm_comp'], ['Je vois de la fumée : quelle couleur ?', 'm_fumee']] };
  E.m_fumee = { type: 'choice', title: 'Couleur de la fumée', why: '<p><b>Bleue</b> = huile brûlée. <b>Blanche épaisse persistante</b>, odeur sucrée = liquide de refroidissement brûlé. <b>Noire</b> = trop de carburant ou manque d’air. <b>Blanche au démarrage à froid</b> qui disparaît (diesel) = combustion incomplète (préchauffage) ; une légère vapeur par temps froid est normale.</p>',
    choices: [['Bleue', 'm_comp'], ['Blanche épaisse persistante, odeur sucrée', 'm_cyl'], ['Noire', 'end_fumee_noire'], ['Blanche au démarrage à froid, disparaît (diesel)', 'm_pre']] };
  E.m_rat = { type: 'choice', title: 'Localiser le raté', why: '<p>Chaque cylindre a sa <b>bobine crayon</b>, commandée par le calculateur. Le calculateur détecte les ratés par les variations de vitesse du vilebrequin : à la valise, lis les <b>compteurs de ratés par cylindre</b>. Puis <b>permute</b> la bobine du cylindre en défaut avec celle d’un cylindre voisin.</p><p>Voyant moteur qui <b>clignote</b> = ratés importants : le carburant imbrûlé détruit le catalyseur, roule le moins possible.</p>',
    choices: [['Le raté suit la bobine', 'm_bob'], ['Le raté reste sur le même cylindre', 'm_bougie'], ['Ratés sur tous les cylindres', 'end_rat_all']] };
  E.m_bob = { type: 'measure', title: 'Contrôle de la bobine', why: '<p>Une bobine est un transformateur : un <b>primaire</b> (peu de spires, faible résistance) et un <b>secondaire</b> (beaucoup de spires, plusieurs kΩ) qui produit la haute tension. Un défaut peut n’apparaître <b>qu’à chaud ou sous charge</b> (fuite haute tension par une fissure).</p>',
    how: '<p>Bobine débranchée : ohmmètre entre les 2 broches du primaire, puis entre la sortie haute tension et une broche du primaire.</p>', measures: ['r_bob_p', 'r_bob_s'],
    decide: function (m) { if (m('r_bob_p').st === 'bad' || m('r_bob_s').st === 'bad') return { v: 'bad', msg: 'Résistance hors tolérance : bobine HS.', next: 'end_bobine' }; return { v: 'warn', msg: 'Valeurs correctes à froid, mais le raté suit la bobine : défaut sous charge (fuite HT, électronique). Bobine à remplacer.', next: 'end_bobine' }; } };
  E.m_bougie = { type: 'choice', title: 'État de la bougie du cylindre', why: '<p>Démonte la bougie et observe : électrodes usées ou <b>écartement</b> trop grand (valeur constructeur, souvent ≈ 0,7 à 1,1 mm), porcelaine fêlée, dépôts. Noire et sèche = mélange riche ; huileuse = remontée d’huile ; blanche / grise claire = mélange pauvre ou surchauffe.</p>',
    choices: [['Usée, encrassée ou fêlée', 'end_bougie'], ['Huileuse', 'm_comp'], ['Bonne', 'end_rat_cyl']] };
  E.m_pre = { type: 'measure', title: 'Bougies de préchauffage', why: '<p>La bougie est une <b>résistance chauffante</b> qui porte la chambre de combustion à haute température pour démarrer à froid. Le <b>boîtier de préchauffage</b> (relais ou calculateur) l’alimente <b>avant</b>, <b>pendant</b> et <b>après</b> le démarrage (post-chauffage : moins de fumée blanche et de bruit). Une bougie coupée = démarrage difficile à froid, fumée blanche.</p>',
    how: '<p>Débranche le connecteur (ou la barrette) de chaque bougie. Ohmmètre entre la borne de la bougie et la masse (culasse). Entre <b>OL</b> si le circuit est ouvert. Moteur 3 cylindres : recopie la valeur d’une autre bougie pour la 4ᵉ.</p>', measures: ['pre1', 'pre2', 'pre3', 'pre4'],
    decide: function (m) { var bad = ['pre1', 'pre2', 'pre3', 'pre4'].filter(function (k) { return m(k).st === 'bad'; }).map(function (k) { return k.slice(3); }); if (bad.length) return { v: 'bad', msg: 'Bougie(s) n°' + bad.join(', ') + ' hors tolérance (coupée si OL).', next: 'end_bougie_pre' }; return { v: 'ok', msg: 'Bougies bonnes : on contrôle leur alimentation.', next: 'm_pre_alim' }; } };
  E.m_pre_alim = { type: 'choice', title: 'Alimentation des bougies', why: '<p>Contact mis (moteur froid) : voltmètre ou lampe témoin entre le fil d’une bougie et la masse. On doit avoir la tension batterie, ou une tension <b>hachée</b> (RCO) sur les boîtiers pilotés. Pense au <b>fusible de forte intensité</b> du préchauffage.</p>',
    choices: [['Tension présente, voyant de préchauffage normal', 'end_pre_ok'], ['Pas de tension aux bougies', 'end_pre_alim']] };
  E.m_ref = { type: 'choice', title: 'Refroidissement : quel symptôme ?', why: '<p>La <b>pompe à eau</b> fait circuler le liquide (eau + antigel). Le <b>thermostat</b> reste fermé à froid (le moteur chauffe vite) et s’ouvre vers 80 à 90 °C pour envoyer le liquide au <b>radiateur</b>. Le <b>motoventilateur</b> est piloté selon la température. Le <b>bouchon taré</b> (≈ 1 à 1,5 bar) met le circuit sous pression pour relever le point d’ébullition.</p><p>⚠️ <b>Ne jamais ouvrir le bouchon moteur chaud.</b></p>',
    choices: [['Le niveau baisse, fuite visible', 'end_fuite_ref'], ['Le niveau baisse sans fuite visible', 'm_cyl'], ['Surchauffe, niveau correct', 'm_therm'], ['Le moteur ne chauffe pas / chauffage froid', 'end_therm_ouv']] };
  E.m_cyl = { type: 'choice', title: 'Le liquide passe-t-il dans le moteur ?', why: '<p>Un <b>joint de culasse</b> défectueux ou une culasse fissurée fait passer les gaz dans le liquide (bulles au vase, durites dures, surchauffe) ou le liquide dans les cylindres (fumée blanche, odeur sucrée) ou dans l’huile (<b>mayonnaise</b> sous le bouchon).</p><ul><li><b>Test CO₂</b> : testeur de gaz de combustion sur le vase d’expansion ; le réactif bleu vire au jaune = gaz de combustion dans le liquide.</li><li><b>Test de pression</b> : pompe à la place du bouchon, à la pression du bouchon, moteur froid : la pression ne doit pas chuter.</li></ul>',
    choices: [['Test CO₂ positif, bulles ou mayonnaise', 'end_joint'], ['La pression chute sans fuite visible', 'end_joint'], ['Tests bons', 'end_fuite_ref']] };
  E.m_therm = { type: 'choice', title: 'Surchauffe avec niveau correct', why: '<p>Moteur chaud : touche prudemment (ou thermomètre infrarouge) la <b>durite supérieure du radiateur</b> : elle doit être chaude. Contrôle que le <b>motoventilateur</b> se déclenche (vers 95 à 105 °C selon véhicule, ou test actionneur à la valise). Compare la température affichée à la réalité (sonde CTN).</p>',
    choices: [['Durite du radiateur froide, moteur chaud', 'end_therm'], ['Le motoventilateur ne se déclenche pas', 'end_ventilo'], ['Température affichée incohérente', 'end_sonde'], ['Tout fonctionne mais ça chauffe en charge', 'end_radiat']] };
  E.m_huile = { type: 'measure', title: 'Pression d’huile', why: '<p>La <b>pompe à huile</b> aspire par la <b>crépine</b>, passe par le <b>filtre</b> et alimente les paliers, l’arbre à cames, le turbo ; un <b>clapet de décharge</b> limite la pression. Le <b>manocontact</b> allume le voyant quand la pression devient trop faible. Avant tout : <b>niveau et qualité de l’huile</b> (viscosité conforme).</p>',
    how: '<p>Dépose le manocontact, visse un <b>manomètre</b> à sa place, moteur chaud (huile ≈ 80 °C). Relève au ralenti puis à 2 000 à 3 000 tr/min.</p>', measures: ['p_huile_ral', 'p_huile_2k'],
    decide: function (m) { if (m('p_huile_ral').st === 'bad' || m('p_huile_2k').st === 'bad') return { v: 'bad', msg: 'Pression d’huile insuffisante : ne roule pas avec, risque de casse moteur.', next: 'end_huile_basse' }; return { v: 'ok', msg: 'Pression d’huile correcte : si le voyant s’allume, le manocontact ou son fil est en cause.', next: 'end_manocontact' }; } };
  E.m_comp = { type: 'measure', title: 'Compression des cylindres', why: '<p>La compression montre l’<b>étanchéité</b> de chaque cylindre : segments, soupapes, joint de culasse. Valeurs types : essence ≈ 10 à 14 bar, diesel ≈ 20 à 30 bar (selon moteur) ; le plus important est l’<b>écart entre cylindres</b>.</p>',
    how: '<ol><li>Moteur chaud, batterie chargée, <b>injection coupée</b> (connecteurs d’injecteurs ou fusible de pompe) et, en essence, toutes les bougies démontées, papillon ouvert à fond.</li><li>Compressiomètre à la place de la bougie (diesel : de l’injecteur ou de la bougie de préchauffage selon l’adaptateur).</li><li>4 à 6 compressions au démarreur par cylindre. Entre 0 pour un cylindre inexistant.</li></ol>', measures: ['comp1', 'comp2', 'comp3', 'comp4'],
    decide: function (m) { var ks = ['comp1', 'comp2', 'comp3', 'comp4'].filter(function (k) { return m(k).v > 0; }), mx = Math.max.apply(null, ks.map(function (k) { return m(k).v; }));
      var low = ks.filter(function (k) { return m(k).v < mx * 0.9; }).map(function (k) { return +k.slice(4); });
      if (!ks.length) return { v: 'warn', msg: 'Aucune valeur saisie.', next: 'm_comp' };
      if (low.length === 2 && Math.abs(low[0] - low[1]) === 1) return { v: 'bad', msg: 'Cylindres voisins n°' + low.join(' et ') + ' faibles : joint de culasse entre ces deux cylindres probable.', next: 'end_joint' };
      if (low.length) return { v: 'bad', msg: 'Cylindre(s) n°' + low.join(', ') + ' à plus de 10 % sous le meilleur (' + r1(mx) + ' bar) : on fait le test à l’huile.', next: 'm_comp_huile' };
      if (low.length === 0 && ks.length > 1 && mx < 8) return { v: 'bad', msg: 'Compression faible et identique partout : calage de distribution (courroie ou chaîne sautée) ou usure générale.', next: 'end_distri' };
      return { v: 'ok', msg: 'Compressions homogènes (maxi ' + r1(mx) + ' bar) : compare à la valeur constructeur.', next: 'end_comp_ok' }; } };
  E.m_comp_huile = { type: 'choice', title: 'Test « humide » (essence)', why: '<p>Verse quelques ml d’huile moteur dans le cylindre faible et refais la mesure. L’huile améliore provisoirement l’étanchéité des <b>segments</b>, pas celle des <b>soupapes</b>.</p>',
    choices: [['La compression remonte nettement', 'end_segments'], ['Elle ne remonte pas', 'end_soupapes']] };
  E.end_bobine = end('bad', 'Bobine d’allumage', '<p>Remplace la bobine (et contrôle la bougie du même cylindre). Efface les compteurs de ratés.</p>', '<p>En dépannage, rouler doucement jusqu’à l’atelier ; voyant moteur <b>clignotant</b> : arrêter (catalyseur).</p>');
  E.end_bougie = end('bad', 'Bougie d’allumage', '<p>Remplace <b>toutes</b> les bougies (même référence, écartement et couple constructeur). Cherche la cause d’un encrassement (mélange riche, huile).</p>');
  E.end_rat_cyl = end('bad', 'Raté sur un cylindre, bobine et bougie bonnes', '<p>Contrôle l’<b>injecteur</b> de ce cylindre (module 🔌 → injecteur essence, permutation), puis la <b>compression</b> (soupape, joint de culasse), puis le jeu aux soupapes.</p>');
  E.end_rat_all = end('bad', 'Ratés sur tous les cylindres', '<p>Cause commune : <b>pression d’essence</b> (pompe, filtre, régulateur), prise d’air à l’admission, alimentation des bobines, capteur (débitmètre, PMH), carburant pollué, <b>calage de distribution</b> (défaut de corrélation arbre à cames / vilebrequin à la valise).</p>');
  E.end_bougie_pre = end('bad', 'Bougie(s) de préchauffage', '<p>Remplace les bougies HS (idéalement toutes). Attention : elles se grippent dans la culasse — dégrippant, moteur tiède, couple faible ; une bougie cassée demande un outillage d’extraction.</p>', '<p>Démarrer à froid : plusieurs cycles de préchauffage, pédale d’accélérateur relâchée ; stationner à l’abri.</p>');
  E.end_pre_ok = end('ok', 'Préchauffage correct', '<p>Si le démarrage à froid reste difficile : compression (module ⚙️), pression de rail au démarreur et retours injecteurs (⛽), capteur de température moteur (🔌 CTN).</p>');
  E.end_pre_alim = end('bad', 'Alimentation du préchauffage', '<p>Contrôle le fusible de forte intensité, le boîtier / relais de préchauffage (alimentation, masse, commande du calculateur moteur), le faisceau jusqu’aux bougies, les défauts à la valise.</p>');
  E.end_fuite_ref = end('bad', 'Fuite de liquide de refroidissement', '<p>Cherche la fuite moteur froid, circuit sous pression (pompe de test) : durites et colliers, radiateur, <b>pompe à eau</b> (trou témoin), radiateur de chauffage (tapis humide, buée grasse), vase et bouchon, bouchons de culasse. Répare puis <b>purge</b> le circuit (vis de purge, chauffage ouvert).</p>', '<p>Compléter avec du liquide ou, en dépannage, de l’eau (refaire le mélange antigel ensuite). <b>Bouchon ouvert seulement moteur froid.</b> Surveiller la température.</p>');
  E.end_joint = end('bad', 'Joint de culasse / culasse', '<p>Dépose de la culasse : contrôle de <b>planéité</b> (et fissures), joint neuf, <b>vis de culasse neuves</b> serrées selon la méthode constructeur (angulaire). Vidange et rinçage si l’huile est polluée.</p>', '<p><b>Ne pas rouler</b> : risque de casse (eau dans les cylindres, surchauffe). Remorquage.</p>');
  E.end_therm = end('bad', 'Thermostat bloqué fermé', '<p>Remplace le thermostat (et son joint), purge le circuit.</p>', '<p>Rouler doucement, <b>chauffage à fond</b> (le radiateur de chauffage évacue de la chaleur), s’arrêter si la température monte encore.</p>');
  E.end_therm_ouv = end('warn', 'Le moteur ne chauffe pas', '<p>Thermostat <b>bloqué ouvert</b> (le plus fréquent) : consommation en hausse, chauffage faible. Contrôle aussi la sonde de température (valeur valise cohérente ?). Remplace le thermostat et purge.</p>');
  E.end_ventilo = end('bad', 'Motoventilateur', '<p>Test actionneur à la valise ; sinon fusible, relais ou module de commande, moteur du ventilateur (alimentation directe), sonde de température. Module 🔌 pour les mesures.</p>', '<p>Éviter les bouchons ; rouler à allure régulière (l’air de la route refroidit), chauffage à fond si besoin.</p>');
  E.end_sonde = end('warn', 'Sonde de température moteur', '<p>Contrôle la sonde CTN (module 🔌 → sonde CTN) et son connecteur. Elle sert aussi à l’injection, au ventilateur et au préchauffage.</p>');
  E.end_radiat = end('bad', 'Échange de chaleur insuffisant', '<p>Radiateur colmaté (intérieur ou ailettes), pompe à eau (turbine usée), air dans le circuit (purge), courroie qui patine, bouchon taré défectueux, début de joint de culasse (test CO₂).</p>');
  E.end_huile_basse = end('bad', 'Pression d’huile insuffisante', '<p>Causes : niveau bas, huile de mauvaise viscosité ou diluée par le carburant, <b>crépine colmatée</b>, pompe usée, clapet de décharge bloqué ouvert, <b>coussinets usés</b> (bruit du bas moteur).</p>', '<p><b>Ne pas rouler</b> si le voyant de pression reste allumé niveau correct : remorquage.</p>');
  E.end_manocontact = end('warn', 'Manocontact ou faisceau', '<p>Remplace le manocontact (joint neuf) et contrôle son fil (fil à la masse = voyant allumé en permanence).</p>');
  E.end_segments = end('bad', 'Segments / cylindre usés', '<p>Réfection du bas moteur (segmentation, alésage) ou échange moteur selon le coût. Contrôle aussi le reniflard (surpression du carter).</p>');
  E.end_soupapes = end('bad', 'Soupape non étanche', '<p>Soupape brûlée, jeu aux soupapes nul, siège abîmé, ou joint de culasse : dépose de la culasse, rodage ou remplacement des soupapes.</p>');
  E.end_distri = end('bad', 'Calage de distribution', '<p>Contrôle le calage (piges constructeur), l’état de la courroie ou de la chaîne et du tendeur. Si la courroie a sauté ou cassé sur un moteur <b>à interférence</b>, les soupapes peuvent être tordues (compression nulle).</p>', '<p>Ne pas insister au démarreur : remorquage.</p>');
  E.end_comp_ok = end('ok', 'Compression correcte', '<p>L’étanchéité des cylindres est bonne : cherche du côté de l’injection, de l’allumage ou de l’air.</p>');
  E.end_fumee_noire = end('warn', 'Fumée noire', '<p>Trop de carburant pour l’air disponible : filtre à air, débitmètre, <b>suralimentation</b>, EGR bloquée ouverte, injecteur qui fuit. Suis le module <b>⛽ Common rail → fumée noire</b>.</p>');

  /* ========================= AUTRES SYSTÈMES ========================= */
  var A = {};
  A.start = { type: 'choice', title: 'Quel système ?', why: '<p>Pour un diagnostic complet du véhicule, ces systèmes complètent les autres modules. Méthode identique : défauts à la valise, alimentation / masse / commande, puis l’élément.</p>',
    choices: [['Éclairage, signalisation', 'a_ecl'], ['Direction assistée', 'a_da'], ['Embrayage, boîte de vitesses', 'a_emb'], ['Climatisation', 'a_clim'], ['Voyant airbag', 'end_airbag'], ['Pression des pneus (TPMS), aides à la conduite (ADAS)', 'a_tpms'], ['Lève-vitres, condamnation des portes', 'a_confort']] };
  A.a_ecl = { type: 'choice', title: 'Éclairage : quel symptôme ?', choices: [['Une seule lampe ne marche pas', 'end_lampe'], ['Plusieurs lampes d’un même circuit', 'end_ecl_circ'], ['Les clignotants battent trop vite', 'end_cligno'], ['Feux qui restent allumés, fonctions incohérentes', 'end_ecl_bsi']] };
  A.a_da = { type: 'choice', title: 'Direction assistée', why: '<p>Trois technologies : <b>hydraulique</b> (pompe entraînée par la courroie), <b>électro-hydraulique</b> (motopompe électrique) et <b>électrique</b> (moteur sur la colonne ou la crémaillère, capteur de couple, calculateur qui a besoin de la vitesse du véhicule par le CAN et d’une bonne tension batterie).</p>',
    choices: [['Direction dure en permanence (hydraulique)', 'end_da_hyd'], ['Direction dure + voyant (électrique)', 'end_da_el'], ['Volant pas droit / voyant ESP après géométrie ou batterie', 'end_angle'], ['Bruit, jeu dans la direction', 'end_da_jeu']] };
  A.a_emb = { type: 'choice', title: 'Embrayage / boîte', choices: [['Patinage : le régime monte mais pas la vitesse', 'end_emb_pat'], ['Les vitesses passent mal ou craquent', 'end_emb_deb'], ['Pédale dure, point de patinage très haut', 'end_emb_usure'], ['Broutement, claquements au ralenti (volant bimasse)', 'end_volant'], ['Boîte automatique / robotisée : à-coups, mode secours', 'end_bva']] };
  A.a_clim = { type: 'choice', title: 'Climatisation', why: '<p>Circuit fermé : <b>compresseur</b> → <b>condenseur</b> (face avant) → détendeur → <b>évaporateur</b> (habitacle). Gaz <b>R134a</b> (anciens véhicules) ou <b>R1234yf</b> (récents). La manipulation du fluide est réservée aux titulaires de l’<b>attestation d’aptitude</b> (fluides frigorigènes), avec une station de charge.</p>',
    choices: [['Ne refroidit pas du tout', 'end_clim_rien'], ['Refroidit peu', 'end_clim_peu'], ['Mauvaise odeur', 'end_clim_odeur']] };
  A.a_tpms = { type: 'choice', title: 'TPMS / ADAS', choices: [['Voyant de pression des pneus', 'end_tpms'], ['Caméra / radar en défaut, ou après pare-brise / géométrie / choc', 'end_adas']] };
  A.a_confort = { type: 'choice', title: 'Confort', choices: [['Lève-vitre', 'end_lv'], ['Condamnation centralisée / serrure', 'end_cond']] };
  A.end_lampe = end('warn', 'Une lampe', '<p>Lampe (filament, bon type), douille oxydée, connecteur, <b>masse</b> du feu. LED : souvent bloc complet. Xénon : ballast et ampoule — <b>plusieurs milliers de volts à l’allumage</b>, débrancher avant d’intervenir.</p>');
  A.end_ecl_circ = end('bad', 'Circuit d’éclairage', '<p>Fusible, relais, commodo, masse commune, module de commande (BSI / module de feux). Mesure la tension au connecteur du feu, commande activée (module 🔌 alimentation / masse).</p>');
  A.end_cligno = end('warn', 'Clignotants rapides', '<p>Une lampe grillée du côté concerné (le calculateur détecte la baisse de courant). Avec des LED de remplacement : résistance de charge ou codage.</p>');
  A.end_ecl_bsi = end('bad', 'Commande de l’éclairage', '<p>Défauts du BSI / module de carrosserie, commodo, capteur de luminosité / pluie, réseau (module 🔌 Multiplexage). Paramétrage (télécodage) après remplacement.</p>');
  A.end_da_hyd = end('bad', 'Direction hydraulique', '<p>Niveau et fuite de liquide, courroie, pompe (bruit, pression), crémaillère. Purge après intervention (braquer de butée à butée moteur tournant, sans rester en butée).</p>');
  A.end_da_el = end('bad', 'Direction électrique', '<p>Lire les défauts ; contrôler la <b>tension batterie</b> et la charge (l’assistance se réduit en cas de sous-tension), la vitesse véhicule reçue (CAN), la protection thermique (manœuvres répétées à l’arrêt). Ensuite : capteur de couple, moteur, colonne ou crémaillère.</p>', '<p>La direction reste manœuvrable sans assistance (plus dure) : rouler prudemment jusqu’à l’atelier.</p>');
  A.end_angle = end('warn', 'Capteur d’angle volant', '<p>Initialisation / calibrage du capteur d’angle volant à la valise (après géométrie, batterie, remplacement de colonne). Le volant doit être droit <b>avant</b> (réglage de la répartition du parallélisme).</p>');
  A.end_da_jeu = end('bad', 'Jeu dans la direction', '<p>Rotules de direction et axiales (biellettes), crémaillère, cardan de colonne, silentblocs, roulements. Contrôle sur <b>plaques à jeu</b> ou roues levées.</p>');
  A.end_emb_pat = end('bad', 'Embrayage qui patine', '<p>Test : 4ᵉ ou 5ᵉ rapport à bas régime, accélération franche : si le régime monte sans que la vitesse suive, le disque est usé ou gras (fuite du joint spi vilebrequin ou de boîte). Remplacer le kit (disque, mécanisme, butée) et contrôler le volant moteur.</p>', '<p>Rouler en douceur, sans accélération franche, rapports bas.</p>');
  A.end_emb_deb = end('bad', 'Débrayage incomplet', '<p>Commande hydraulique : niveau (souvent commun aux freins), <b>purge</b>, émetteur / récepteur ou butée hydraulique qui fuit ; câble : réglage. Sinon disque qui colle, cannelures, synchros de boîte.</p>', '<p>En dépannage : passer les rapports moteur arrêté puis démarrer en 1ʳᵉ, ou passer les rapports en douceur en accordant les régimes.</p>');
  A.end_emb_usure = end('warn', 'Embrayage en fin de vie', '<p>Point de patinage haut et pédale dure : disque usé, mécanisme fatigué, butée ou câble grippé. Prévoir le remplacement du kit.</p>');
  A.end_volant = end('bad', 'Volant moteur bimasse', '<p>Contrôle du jeu angulaire et du basculement (valeurs constructeur), bruits au démarrage / à l’arrêt. Remplacement avec l’embrayage.</p>');
  A.end_bva = end('bad', 'Boîte automatique / robotisée', '<p>Lire les défauts, <b>niveau et état de l’huile</b> (méthode constructeur, à température), vidange si prévue, apprentissages / adaptations à la valise. Mode secours = rapport bloqué pour protéger la boîte.</p>', '<p>Mode secours : rouler doucement jusqu’à l’atelier ; couper puis redémarrer peut rétablir provisoirement.</p>');
  A.end_clim_rien = end('bad', 'La climatisation ne refroidit pas', '<p>Le compresseur s’enclenche-t-il ? Fusible, relais, commande (valise), <b>pressostat / capteur de pression</b> qui bloque si la charge est insuffisante. Contrôle de la charge et recherche de fuite (traceur UV, azote) à la station par une personne habilitée.</p>');
  A.end_clim_peu = end('warn', 'Climatisation peu efficace', '<p>Charge insuffisante (fuite lente), condenseur encrassé, motoventilateur, filtre d’habitacle colmaté, volets de mixage (valise).</p>');
  A.end_clim_odeur = end('warn', 'Mauvaise odeur', '<p>Remplacer le <b>filtre d’habitacle</b>, traiter l’évaporateur, contrôler l’évacuation des condensats (bouchée = eau au plancher).</p>');
  A.end_airbag = end('bad', 'Voyant airbag', '<ul><li>⚠️ <b>Ne jamais mesurer</b> un airbag ou un prétensionneur au multimètre ou à la lampe témoin : risque de déclenchement.</li><li>Avant de débrancher un élément : contact coupé, <b>batterie débranchée</b>, attendre le temps indiqué par le constructeur (réserve d’énergie du calculateur).</li><li>Lire les défauts à la valise : résistance de ligne trop élevée = souvent <b>contacteur tournant</b> (sous le volant) ou <b>connecteur sous un siège</b> (siège déplacé).</li><li>Un élément déclenché se remplace (et parfois le calculateur).</li></ul>');
  A.end_tpms = end('warn', 'Pression des pneus (TPMS)', '<p><b>Système direct</b> : capteur dans chaque valve (pile de plusieurs années) ; après remplacement ou permutation : apprentissage avec un outil TPMS ou procédure de la notice. <b>Système indirect</b> : il utilise les capteurs ABS ; <b>réinitialiser</b> depuis le menu après chaque réglage des pressions.</p>', '<p>Contrôler et régler les pressions à froid, puis réinitialiser.</p>');
  A.end_adas = end('warn', 'Aides à la conduite (ADAS)', '<p>Caméra de pare-brise et radar doivent être <b>calibrés</b> après remplacement du pare-brise, d’un pare-chocs / support, un choc ou un réglage de géométrie : calibrage statique (cibles) ou dynamique (roulage) à la valise.</p>');
  A.end_lv = end('warn', 'Lève-vitre', '<p>Initialisation (séquentiel) ; commande : tension au moteur <b>pendant l’appui</b> (les deux sens) ; présente = moteur ou mécanisme (câble, patins) ; absente = interrupteur, fusible, module de porte, faisceau du soufflet.</p>', '<p>Vitre tombée : la remonter à la main et la caler (ruban adhésif fort) jusqu’à l’atelier.</p>');
  A.end_cond = end('warn', 'Condamnation', '<p>Moteur de serrure (commande à la valise), fils cassés dans le <b>soufflet de porte</b>, commande BSI / UCH, contacteur de porte (signale une porte ouverte).</p>', '<p>Porte bloquée : ouvrir par l’intérieur, utiliser la lame mécanique côté conducteur.</p>');

  /* ========================= DÉPANNAGE D’URGENCE ========================= */
  var U = {};
  U.start = { type: 'choice', title: 'Quelle situation ?', why: '<p><b>Sécurité d’abord</b> : feux de détresse, <b>gilet</b>, <b>triangle</b> à au moins 30 m, passagers derrière la glissière. Sur autoroute, appeler depuis une borne ou le 112 : le remorquage y est réservé aux dépanneurs agréés.</p>',
    choices: [['Le véhicule ne démarre pas', 'u_nd'], ['Le véhicule est bloqué / ne peut pas rouler', 'u_bloque'], ['Un voyant s’allume en roulant', 'u_voy'], ['Erreur de carburant', 'u_carbu'], ['Un équipement ne marche plus (fusible)', 'u_fus'], ['Véhicule hybride ou électrique', 'u_ev']] };
  U.u_nd = { type: 'choice', title: 'Ne démarre pas', choices: [['Rien ne s’allume ou le démarreur ne tourne pas / tourne lentement', 'u_batt'], ['Clé non reconnue, pile de clé HS, porte à ouvrir', 'u_cle'], ['Panne sèche / diesel à réamorcer', 'u_amorce'], ['Le démarreur tourne bien mais le moteur ne part pas', 'u_nd2']] };
  U.u_bloque = { type: 'choice', title: 'Bloqué', choices: [['Frein de parking électrique serré (plus de batterie)', 'u_epb'], ['Boîte automatique bloquée sur P', 'u_bva'], ['Crevaison', 'u_crev'], ['Remorquer / faire remorquer le véhicule', 'u_remorq']] };
  U.u_voy = { type: 'choice', title: 'Quel voyant ?', why: '<p><b>Rouge</b> = s’arrêter dès que possible en sécurité. <b>Orange</b> = anomalie, rouler prudemment jusqu’à l’atelier.</p>',
    choices: [['Température moteur (rouge) / surchauffe', 'u_temp'], ['Pression d’huile (rouge)', 'u_huile'], ['Batterie / charge (rouge)', 'u_charge'], ['Freinage (rouge)', 'u_frein'], ['Moteur / antipollution (orange), mode dégradé', 'u_moteur']] };
  U.u_batt = urg('Démarrer avec des câbles ou un booster', '<ol><li>Même tension : <b>12 V sur 12 V</b>. Attention, beaucoup de poids lourds et de véhicules militaires sont en <b>24 V</b> : ne jamais mélanger.</li><li>Contacts coupés, consommateurs éteints, les véhicules ne se touchent pas.</li><li><b>Rouge</b> : + de la batterie à plat → + de la batterie de secours.</li><li><b>Noir</b> : – de la batterie de secours → <b>point de masse</b> du véhicule en panne (masse moteur ou point prévu, loin de la batterie), <b>pas</b> sur la borne – (étincelle / hydrogène, capteur de batterie).</li><li>Batterie dans le coffre ou sous un siège : utiliser les <b>bornes de démarrage</b> déportées sous le capot.</li><li>Démarrer le véhicule donneur, attendre quelques minutes, puis démarrer (essais de 10 à 15 s maxi, pause entre deux).</li><li>Allumer le dégivrage arrière, puis débrancher dans l’<b>ordre inverse</b> : noir d’abord, rouge ensuite.</li><li>Rouler au moins 30 min ou recharger au chargeur, puis tester la batterie (module 🔋).</li></ol><p>⚠️ Batterie <b>gelée, gonflée ou qui fuit</b> : ne pas la ponter (risque d’explosion). Booster : mêmes règles, sélecteur sur 12 V.</p>');
  U.u_cle = urg('Problème de clé', '<ul><li><b>Ouvrir sans télécommande</b> : lame mécanique cachée dans la clé (bouton ou tiroir) ; barillet côté conducteur parfois sous un <b>cache de poignée</b> (petite fente pour faire levier).</li><li><b>Démarrer avec la pile HS</b> (mains libres) : poser la clé contre la <b>zone de secours</b> (colonne, console, bouton Start avec la clé) ou insérer la carte dans son lecteur ; le transpondeur marche sans pile.</li><li><b>Changer la pile</b> : référence gravée (CR2032 la plus courante).</li><li><b>Volant bloqué</b> : tourner le volant à gauche / à droite en même temps que la clé ou le bouton Start.</li><li><b>Voyant antidémarrage</b> avec la bonne clé : essayer le double ; sinon diagnostic <b>🔑 Clés et antidémarrage</b>.</li></ul>');
  U.u_amorce = urg('Panne sèche / réamorçage', '<ol><li>Mettre au moins 5 L de carburant.</li><li><b>Diesel, pompe d’amorçage manuelle (poire)</b> : pomper jusqu’à ce qu’elle devienne dure.</li><li><b>Pompe de gavage électrique</b> : mettre le contact 10 à 15 s sans démarrer, 3 ou 4 fois de suite.</li><li>Démarrer par essais courts (10 s), pause entre deux.</li><li><b>Ne jamais desserrer un raccord haute pression</b> pour purger.</li></ol>');
  U.u_nd2 = urg('Le moteur tourne mais ne démarre pas', '<ul><li>Voyant antidémarrage (clé) allumé ou clignotant ? → 🔑 Clés.</li><li>Carburant : jauge, panne sèche, erreur de carburant.</li><li>Diesel par grand froid : cycles de préchauffage, gazole figé (véhicule au chaud).</li><li>Tension au démarrage sous 9,6 V : les calculateurs décrochent → câbles / booster.</li><li>Inertie (coupure après un choc) : certains véhicules coupent la pompe à essence ; réarmement selon la notice.</li><li>Sinon : diagnostic ⛽ Common rail ou ⚙️ Moteur, remorquage.</li></ul>');
  U.u_epb = urg('Frein de parking électrique bloqué', '<ol><li><b>Caler les roues</b> (cales, rapport engagé ou P) avant tout desserrage : une fois libéré, le véhicule n’est plus retenu.</li><li><b>Rendre du courant au véhicule</b> : booster ou câbles sur la batterie / les bornes de démarrage, contact mis, <b>pied sur le frein</b>, commande de desserrage. C’est la solution la plus simple.</li><li><b>Commande de secours</b> : certains véhicules à <b>actionneur central à câbles</b> (par exemple certaines Renault Scénic / Grand Scénic) ont une tirette ou manette de desserrage de secours (dans le coffre sous le tapis ou sous une trappe au plancher selon la génération) : son emplacement est dans la <b>notice</b>.</li><li><b>Étriers à moteur intégré</b> (la plupart des véhicules récents), à l’atelier : débrancher le connecteur, déposer le moteur de l’étrier (vis Torx), tourner la broche dans le sens indiqué par la <b>flèche</b> jusqu’à libérer la roue, reposer le moteur (joint en place, vis engagées à la main puis couple constructeur).</li><li>⚠️ <b>Ne jamais alimenter directement le moteur de l’étrier</b> avec des fils : risque de destruction de l’actionneur.</li><li>Ensuite : défauts à la valise, <b>apprentissage / étalonnage</b> du frein de parking, essai.</li></ol><p>Remorquage frein serré : plateau ou roues arrière levées.</p>');
  U.u_bva = urg('Boîte automatique bloquée sur P', '<ul><li><b>Levier mécanique</b> : sans batterie, le verrouillage du levier (shift lock) empêche de quitter P. Une petite trappe près du levier donne accès au <b>déverrouillage</b> : enfoncer un outil (clé, tournevis), pied sur le frein, passer en <b>N</b>.</li><li><b>Sélecteur électronique</b> (bouton, molette, commodo) : pas de déverrouillage au levier ; <b>rendre du courant</b> (booster), ou procédure de secours de la notice.</li><li>Remorquer une boîte auto roues motrices au sol : seulement dans les limites de la notice (vitesse et distance réduites) ; sinon <b>plateau</b>.</li></ul>');
  U.u_crev = urg('Crevaison', '<ul><li><b>Sécurité</b> : sol plat et dur, frein de parking, 1ʳᵉ ou P, passagers dehors derrière la glissière, triangle.</li><li><b>Roue de secours</b> : débloquer les écrous roue au sol, cric au <b>point de levage</b>, déposer, reposer, serrer en croix, reposer au sol, serrer au couple ; contrôler la pression. <b>Galette</b> : vitesse maxi indiquée sur la roue (souvent 80 km/h).</li><li><b>Kit anti-crevaison</b> (produit + compresseur) : seulement pour une petite perforation de la bande de roulement (pas le flanc) ; rouler quelques km puis recontrôler la pression ; prévenir le réparateur (produit dans le pneu, capteur TPMS).</li><li><b>Pneus « runflat »</b> : on peut rouler dégonflé à vitesse et distance limitées (notice).</li><li>Après : resserrer les écrous au couple après quelques dizaines de km, réparer ou remplacer le pneu, réinitialiser le TPMS.</li></ul>');
  U.u_remorq = urg('Remorquage', '<ul><li><b>Anneau de remorquage</b> vissé dans le logement du pare-chocs (anneau dans le kit de roue).</li><li>Véhicule remorqué : <b>contact mis</b> (direction débloquée, feux stop), feux de détresse, point mort. Moteur arrêté : <b>plus d’assistance</b> de freinage ni de direction (plus dur).</li><li><b>Barre rigide</b> de préférence ; sangle : la tenir tendue.</li><li><b>Boîte auto</b> : limites de la notice, sinon plateau. <b>4×4 intégral</b> : plateau. <b>Hybride / électrique</b> : <b>plateau</b> (les roues entraînent le moteur électrique qui produit du courant).</li><li>Sur autoroute, le remorquage est réservé aux dépanneurs agréés.</li></ul>');
  U.u_temp = urg('Surchauffe moteur', '<ol><li>Couper la climatisation, mettre le <b>chauffage à fond</b> et la ventilation au maxi (évacue de la chaleur).</li><li>S’arrêter dès que possible. Laisser tourner au ralenti si le ventilateur fonctionne et que la température baisse ; sinon couper le moteur.</li><li>⚠️ <b>Ne jamais ouvrir le bouchon</b> moteur chaud (liquide bouillant sous pression).</li><li>Moteur froid : niveau, fuite visible, ventilateur, courroie. Compléter avec du liquide (ou de l’eau en dépannage).</li><li>Perte importante, fumée blanche, mayonnaise dans l’huile : <b>ne pas rouler</b> (joint de culasse), remorquage. Diagnostic ⚙️ Moteur → refroidissement.</li></ol>');
  U.u_huile = urg('Voyant de pression d’huile', '<ol><li><b>S’arrêter immédiatement</b> et couper le moteur : sans pression d’huile, le moteur peut casser en très peu de temps.</li><li>Attendre quelques minutes, véhicule à plat, contrôler le <b>niveau</b> (jauge).</li><li>Niveau bas : compléter avec une huile à la <b>norme constructeur</b> ; si le voyant s’éteint, rouler prudemment et chercher la fuite ou la consommation.</li><li>Niveau correct et voyant allumé : <b>ne pas rouler</b>, remorquage.</li></ol><p>Ne pas confondre avec le voyant <b>orange de niveau mini</b> : compléter le niveau.</p>');
  U.u_charge = urg('Voyant de charge', '<ul><li>L’alternateur ne recharge plus : le véhicule roule sur la batterie, <b>autonomie limitée</b>.</li><li>Couper tous les consommateurs (clim, dégivrage, sièges chauffants, radio ; phares seulement si nécessaire) et rouler directement vers l’atelier, sans couper le moteur.</li><li>Regarder la <b>courroie</b> : si elle est cassée et entraîne aussi la pompe à eau, surveiller la température et s’arrêter.</li><li>Diagnostic : 🔋 Batterie, charge et démarrage.</li></ul>');
  U.u_frein = urg('Voyant de freinage rouge', '<ul><li>Frein de parking encore serré ? Le desserrer.</li><li>Sinon : <b>niveau de liquide de frein</b>. Niveau bas ou pédale qui s’enfonce : <b>ne pas rouler</b>, remorquage.</li><li>Voyant ABS / ESP orange seul : le freinage de base fonctionne, sans l’anti-blocage : rouler prudemment jusqu’à l’atelier (module 🛑).</li></ul>');
  U.u_moteur = urg('Voyant moteur / mode dégradé', '<ul><li><b>Fixe</b> : anomalie, puissance souvent limitée : rouler prudemment jusqu’à l’atelier, lire les défauts.</li><li><b>Clignotant</b> (essence) : ratés importants, le catalyseur peut être détruit : rouler le moins possible, doucement.</li><li>Couper puis redémarrer peut rétablir provisoirement la puissance.</li><li>Voyant FAP / antipollution : voir 🌫️ ; AdBlue : ne pas laisser le compteur arriver à zéro (le moteur ne redémarre plus).</li></ul>');
  U.u_carbu = urg('Erreur de carburant', '<ul><li><b>Ne pas démarrer, ne pas mettre le contact</b> (la pompe électrique ferait circuler le mauvais carburant) : faire vidanger le réservoir par un dépanneur.</li><li>Déjà roulé : s’arrêter immédiatement, couper le moteur. Vidange, rinçage, filtre neuf. L’essence dans un diesel common rail peut abîmer la <b>pompe haute pression</b> et les injecteurs.</li><li>AdBlue dans le réservoir de carburant ou carburant dans le réservoir d’AdBlue : ne pas démarrer, remorquage (nettoyage du circuit).</li></ul>');
  U.u_fus = urg('Remplacer un fusible', '<ol><li>Boîtes à fusibles : habitacle (planche de bord), compartiment moteur, parfois coffre. Le <b>plan</b> est dans la notice ou sous le couvercle.</li><li>Contact coupé. Retirer avec la pince fournie, contrôler (filament coupé, ou deux points de test à 12 V contact mis = bon).</li><li>Remplacer par <b>le même calibre</b> (mini-fusibles : 10 A rouge, 15 A bleu, 20 A jaune, 30 A vert).</li><li>Il refond aussitôt : <b>court-circuit</b>. <b>Jamais un calibre supérieur</b> ni un fil à la place (risque d’incendie).</li></ol>');
  U.u_ev = urg('Hybride ou électrique', '<ul><li><b>Câbles orange = haute tension</b> (plusieurs centaines de volts) : ne jamais les toucher, les débrancher ni les couper. Les interventions HT sont réservées aux personnes <b>habilitées</b> (habilitation électrique véhicules, NF C 18-550).</li><li>Le véhicule est <b>silencieux</b> même prêt à rouler (READY) : P, frein de parking, contact coupé et clé éloignée avant d’intervenir.</li><li>Il ne s’allume plus : c’est souvent la <b>batterie 12 V</b> (auxiliaire) ; elle se ponte comme une batterie classique aux points prévus. Ne pas utiliser un véhicule électrique comme donneur sauf si la notice l’autorise.</li><li>Accident, fumée, odeur ou bruit de la batterie HT : s’éloigner, appeler le 18 / 112 en précisant que le véhicule est électrique (risque d’emballement thermique, parfois retardé).</li><li>Remorquage sur <b>plateau</b>.</li></ul>');

  function add(id, icon, titre, sous, steps, comprendre, apres) { D.MODULES[id] = { id: id, icon: icon, titre: titre, sous: sous, start: 'start', steps: steps, comprendre: comprendre, apres: apres || '' }; }
  add('cles', '🔑', 'Clés, télécommande et antidémarrage', 'Pile, resynchronisation, transpondeur, mains libres, antivol, programmation', K,
    '<h3>Deux systèmes dans une clé</h3><div class="tw"><table><tr><th></th><th>Télécommande</th><th>Transpondeur (antidémarrage)</th></tr><tr><td>Rôle</td><td>Ouvrir / fermer</td><td>Autoriser le démarrage</td></tr><tr><td>Énergie</td><td>Pile de la clé</td><td>Champ de l’antenne du véhicule (sans pile)</td></tr><tr><td>Liaison</td><td>Radio UHF (≈ 433 MHz), code tournant</td><td>Antenne autour du barillet / lecteur / antennes mains libres</td></tr><tr><td>Panne typique</td><td>Pile, désynchronisation</td><td>Clé non apprise, antenne, appairage calculateur</td></tr></table></div>' +
    '<p>L’<b>antidémarrage</b> : le BSI / UCH lit le transpondeur, puis autorise le calculateur moteur par un code échangé sur le CAN. Remplacer un BSI, un calculateur moteur ou ajouter une clé demande un <b>appairage</b>, réservé aux professionnels accrédités (<b>SERMI</b>).</p>',
    '<p><b>Spécifique clés</b> : tester <b>toutes</b> les clés (ouverture, fermeture, démarrage), noter le nombre de clés apprises, faire effacer les clés perdues.</p>');
  add('meca', '⚙️', 'Moteur : mécanique et auxiliaires', 'Allumage, préchauffage, refroidissement, pression d’huile, compression, fumées', E,
    '<h3>Repères</h3><div class="tw"><table><tr><th>Contrôle</th><th>Valeur type</th></tr><tr><td>Compression essence / diesel</td><td>≈ 10 à 14 bar / ≈ 20 à 30 bar ; écart entre cylindres ≤ 10 %</td></tr><tr><td>Pression d’huile chaude</td><td>≥ ≈ 1 bar au ralenti ; ≈ 2 à 4 bar à 2 000 à 3 000 tr/min</td></tr><tr><td>Thermostat</td><td>Ouverture vers 80 à 90 °C</td></tr><tr><td>Bouchon de circuit</td><td>≈ 1 à 1,5 bar</td></tr><tr><td>Bobine crayon</td><td>Primaire 0,3 à 1,5 Ω ; secondaire 5 à 15 kΩ</td></tr></table></div>' +
    '<h3>Couleur des fumées</h3><ul><li><b>Bleue</b> : huile (segments, guides de soupapes, turbo).</li><li><b>Blanche persistante</b>, odeur sucrée : liquide de refroidissement (joint de culasse).</li><li><b>Noire</b> : excès de carburant / manque d’air.</li><li><b>Blanche au démarrage à froid</b> (diesel) : préchauffage, combustion incomplète.</li></ul>' +
    '<div class="box piege"><b>⚠️ Sécurité</b><ul><li>Ne jamais ouvrir le bouchon de refroidissement moteur chaud.</li><li>Distribution : courroie remplacée à la périodicité constructeur ; sur un moteur à interférence, une casse tord les soupapes.</li></ul></div>',
    '<p><b>Spécifique moteur</b> : purge du circuit de refroidissement, contrôle des niveaux, pas de fuite à chaud, compteurs de ratés à zéro, vidange si l’huile a été polluée.</p>');
  add('autres', '🧰', 'Autres systèmes', 'Éclairage, direction assistée, embrayage et boîte, climatisation, airbag, TPMS, ADAS, confort', A,
    '<h3>Pour un diagnostic complet</h3><p>Ces systèmes complètent les autres modules. Même méthode partout : <b>lire les défauts</b>, contrôler <b>alimentation, masse, commande</b> (module 🔌), puis l’élément. Après remplacement, beaucoup demandent un <b>apprentissage ou un calibrage</b> (capteur d’angle volant, ADAS, TPMS, boîte auto).</p><div class="box piege"><b>⚠️ Sécurité</b><ul><li>Airbags : jamais de mesure au multimètre ; batterie débranchée et temps d’attente constructeur.</li><li>Xénon : très haute tension à l’allumage.</li><li>Climatisation : fluide réservé aux personnes titulaires de l’attestation d’aptitude.</li></ul></div>');
  add('urgence', '🆘', 'Dépannage d’urgence', 'Batterie à plat, clé, frein de parking électrique, boîte auto sur P, crevaison, voyants, remorquage', U,
    '<h3>Les réflexes</h3><ol><li><b>Sécurité</b> : feux de détresse, gilet, triangle à 30 m au moins, passagers à l’abri derrière la glissière.</li><li><b>Voyant rouge</b> : s’arrêter ; <b>orange</b> : rouler prudemment jusqu’à l’atelier.</li><li>Ne jamais : ouvrir le circuit de refroidissement chaud, desserrer un raccord HP diesel, toucher un câble orange (HT), alimenter directement un actionneur de frein de parking, mettre un fusible plus gros.</li><li>Après un dépannage : faire le <b>diagnostic</b> avec le module correspondant, puis la réparation définitive.</li></ol>' +
    '<h3>Dans le coffre</h3><ul><li>Câbles de démarrage ou booster, gilet et triangle.</li><li>Cales, lampe, gants.</li><li>Anneau de remorquage, fusibles de rechange.</li><li>Pile de clé de rechange.</li><li>Kit anti-crevaison ou roue de secours et cric.</li></ul>');

  /* Ordre d’affichage sur l’accueil : urgence d’abord */
  var order = ['urgence', 'mux', 'charge', 'meca', 'cr', 'anti', 'cles', 'dsft', 'frein', 'autres'], old = D.MODULES, nm = {};
  order.forEach(function (k) { if (old[k]) nm[k] = old[k]; }); Object.keys(old).forEach(function (k) { if (!nm[k]) nm[k] = old[k]; });
  D.MODULES = nm;
})();
