/* Diagnostic — module BATTERIE, CHARGE, DÉMARRAGE.
   Valeurs de référence (TYPES, 12 V, la valeur constructeur prime) : batterie au repos 12,4 à 12,8 V (12,6 V ≈ chargée) ;
   tension pendant le démarrage ≥ 9,6 V ; courant de fuite après mise en veille ≤ 50 mA ; tension de charge 13,5 à 14,8 V
   (alternateur piloté : elle peut varier davantage) ; ondulation alternative ≤ 0,5 V ; chutes de tension ≤ 0,5 V côté +,
   ≤ 0,2 à 0,3 V côté masse. */
(function () {
  var D = window.DIAG, M = D.MEASURES;
  function mes(id, label, unit, min, max, note) { M[id] = { id: id, label: label, unit: unit, min: min, max: max, note: note || '' }; }
  function r1(n) { return String(Math.round(n * 10) / 10).replace('.', ','); }
  function end(v, title, html) { return { type: 'end', v: v, title: title, html: html }; }

  mes('cca_nom', 'Courant de démarrage NOMINAL (étiquette de la batterie, norme EN)', 'A', null, null);
  mes('cca_mes', 'Courant de démarrage MESURÉ (testeur de batterie)', 'A', null, null);
  mes('u_crank', 'Tension batterie PENDANT le démarrage', 'V', 9.6, Infinity, 'Valeur type : ne doit pas descendre sous 9,6 V (batterie 12 V, moteur tiède).');
  mes('i_fuite', 'Courant de fuite (consommation, véhicule en veille)', 'mA', 0, 50, 'Valeur type : 20 à 50 mA une fois tous les calculateurs en veille.');
  mes('u_chg', 'Tension de charge, 2 000 tr/min, SANS consommateurs', 'V', 13.5, 14.8, 'Valeur type : 13,5 à 14,8 V. Alternateur piloté (charge intelligente) : la tension peut baisser batterie chargée — allume les consommateurs pour la faire monter.');
  mes('u_chg_c', 'Tension de charge, 2 000 tr/min, AVEC consommateurs (phares, dégivrage, ventilation maxi)', 'V', 13.2, 14.8, 'Valeur type : reste au-dessus d’environ 13,2 V.');
  mes('u_ond', 'Ondulation : tension ALTERNATIVE aux bornes de la batterie, moteur tournant (V AC)', 'V', 0, 0.5, 'Valeur type : quelques dixièmes de volt maxi. Plus = diode du pont redresseur HS.');
  mes('dt_alt_p', 'Chute de tension câble + : borne B+ alternateur → borne + batterie (2 000 tr/min, consommateurs)', 'V', 0, 0.5, 'Valeur type : ≤ 0,5 V.');
  mes('dt_alt_m', 'Chute de tension masse : carter alternateur → borne – batterie (2 000 tr/min, consommateurs)', 'V', 0, 0.2, 'Valeur type : ≤ 0,2 V.');
  mes('u_50', 'Tension de commande du démarreur (borne 50 / solénoïde) pendant l’action sur la clé', 'V', 8, Infinity, 'Valeur type : proche de la tension batterie pendant le démarrage (au moins 8 V).');
  mes('dt_dem_p', 'Chute de tension câble + : borne + batterie → borne 30 du démarreur (pendant le démarrage)', 'V', 0, 0.5, 'Valeur type : ≤ 0,5 V.');
  mes('dt_dem_m', 'Chute de tension masse : carter démarreur → borne – batterie (pendant le démarrage)', 'V', 0, 0.3, 'Valeur type : ≤ 0,3 V.');

  var B = {};
  B.start = { type: 'choice', title: 'Quel est le symptôme ?', why: '<p>La <b>batterie</b> stocke l’énergie, le <b>démarreur</b> en consomme beaucoup (plusieurs centaines d’ampères), l’<b>alternateur</b> la recharge et alimente le véhicule moteur tournant. On commence <b>toujours par la batterie</b> : une batterie faible fausse tous les autres contrôles.</p>',
    choices: [['La batterie se décharge (panne le matin, après quelques jours)', 'bat'], ['Voyant de charge allumé / la batterie ne se recharge pas', 'bat'], ['Le démarreur ne tourne pas ou tourne lentement', 'bat'], ['Le démarreur tourne mais le moteur ne démarre pas', 'nodem'], ['Contrôle complet (entretien, entraînement)', 'bat']] };
  B.nodem = { type: 'info', title: 'Le moteur est entraîné mais ne démarre pas', html: '<p>Le circuit de démarrage fait son travail : le problème vient de l’<b>injection</b>, de l’<b>allumage</b> (essence), du <b>préchauffage</b> (diesel), de l’<b>antidémarrage</b> ou du <b>capteur de régime</b>. Contrôle quand même la tension pendant le démarrage (sous 9,6 V, les calculateurs peuvent décrocher), puis passe au module <b>⛽ Moteur diesel common rail</b> ou <b>🔌 Multiplexage → capteur</b>.</p>', bouton: 'Contrôler la batterie quand même', next: 'bat' };
  B.bat = { type: 'measure', title: 'Tension de la batterie au repos', why: '<p>La tension au repos donne l’<b>état de charge</b> : ≈ 12,6 V et plus = chargée ; ≈ 12,4 V = 75 % ; ≈ 12,2 V = 50 % ; sous 12 V = déchargée. Elle ne dit <b>pas</b> si la batterie est usée : pour cela, il faut le testeur (étape suivante). Une batterie déchargée doit être <b>rechargée avant d’être testée</b>.</p>',
    how: '<p>Moteur arrêté depuis au moins quelques minutes (idéalement plusieurs heures), consommateurs coupés. Voltmètre en V continu directement sur les bornes (pas sur les cosses).</p>', measures: ['ubat'],
    decide: function (m) { var b = m('ubat'); if (b.st === 'ok' || b.dir === 'high') return { v: 'ok', msg: 'Batterie chargée (' + r1(b.v) + ' V) : on peut la tester.', next: 'bat_test' }; return { v: b.st, msg: 'Batterie ' + (b.v < 12 ? 'déchargée' : 'insuffisamment chargée') + ' (' + r1(b.v) + ' V) : recharge-la au chargeur avant le test, sinon le testeur la déclarera HS à tort.', next: 'bat_chg' }; } };
  B.bat_chg = { type: 'info', title: 'Recharger la batterie', html: '<ol><li>Chargeur adapté à la technologie (plomb classique, EFB ou <b>AGM</b> pour les véhicules Stop & Start).</li><li>Local ventilé (dégagement d’hydrogène), pas d’étincelle près de la batterie.</li><li>Laisse reposer après la charge avant de mesurer.</li></ol><p>Une batterie qui <b>se décharge sans raison</b> : pense au courant de fuite (étape de contrôle plus loin).</p>', bouton: 'La batterie est rechargée', next: 'bat_test' };
  B.bat_test = { type: 'measure', title: 'Test de la batterie : capacité de démarrage', why: '<p>Le testeur de batterie (conductance) estime le <b>courant de démarrage</b> qu’elle peut encore fournir, à comparer au courant nominal inscrit sur l’étiquette (ex. « 680 A EN »). On contrôle aussi la <b>tension pendant le démarrage</b> : une batterie usée s’écroule sous la charge du démarreur.</p>',
    how: '<ol><li>Testeur sur les bornes, règle la norme (EN) et le courant nominal de l’étiquette, lance le test.</li><li>Voltmètre sur les bornes, fais tourner le démarreur 5 s (diesel : sans démarrer si possible, en débranchant l’injection selon la méthode constructeur) et relève la tension la plus basse.</li></ol>', measures: ['cca_nom', 'cca_mes', 'u_crank'],
    decide: function (m) { var n = m('cca_nom').v, x = m('cca_mes').v, p = n ? x / n * 100 : 100;
      if (p < 60 || m('u_crank').st === 'bad') return { v: 'bad', msg: 'Batterie usée : ' + Math.round(p) + ' % du courant nominal' + (m('u_crank').st === 'bad' ? ', tension au démarrage ' + r1(m('u_crank').v) + ' V' : '') + '. Remplace-la (même technologie, même capacité), puis contrôle la charge pour savoir pourquoi elle a souffert.', next: 'end_bat' };
      if (p < 75) return { v: 'warn', msg: 'Batterie fatiguée : ' + Math.round(p) + ' % du courant nominal. Elle peut encore servir mais risque de lâcher au premier froid. Suis le verdict de ton testeur.', next: 'suite' };
      return { v: 'ok', msg: 'Batterie en bon état : ' + Math.round(p) + ' % du courant nominal, tension au démarrage ' + r1(m('u_crank').v) + ' V.', next: 'suite' }; } };
  B.suite = { type: 'choice', title: 'Que contrôler maintenant ?', why: '<p>La batterie est bonne : on cherche ce qui la vide (<b>courant de fuite</b>), ce qui ne la recharge pas (<b>circuit de charge</b>) ou ce qui empêche de démarrer (<b>circuit de démarrage</b>).</p>',
    choices: [['La batterie se vide à l’arrêt : courant de fuite', 'fuite'], ['Circuit de charge (alternateur)', 'chg'], ['Circuit de démarrage (démarreur)', 'dem'], ['Rien de plus, terminer', 'end_ok']] };
  B.fuite = { type: 'measure', title: 'Courant de fuite (consommation à l’arrêt)', why: '<p>Véhicule fermé, les calculateurs se mettent <b>en veille</b> et ne consomment presque plus rien. Un calculateur qui ne s’endort pas, un plafonnier, un accessoire (autoradio, alarme, traceur) ou un relais collé vide la batterie en quelques jours.</p>',
    how: '<ol><li>Pince ampèremétrique de précision (mA) sur le câble de masse, ou ampèremètre en série avec un <b>shunt / interrupteur</b> pour ne pas couper l’alimentation (ce qui réveillerait les calculateurs).</li><li>Capot : condamne le contacteur de capot ; portes : verrouille le véhicule (ou trompe les contacteurs de porte).</li><li>Attends la <b>mise en veille</b> complète (souvent 5 à 30 min, parfois plus) avant de lire la valeur.</li></ol>', measures: ['i_fuite'],
    decide: function (m) { if (m('i_fuite').st === 'ok') return { v: 'ok', msg: 'Consommation à l’arrêt normale (' + r1(m('i_fuite').v) + ' mA) : la batterie ne se vide pas par une fuite. Contrôle la charge.', next: 'chg' }; return { v: 'bad', msg: 'Consommation à l’arrêt trop élevée (' + r1(m('i_fuite').v) + ' mA) : un consommateur reste alimenté ou un calculateur ne s’endort pas.', next: 'end_fuite' }; } };
  B.chg = { type: 'measure', title: 'Circuit de charge : tension et ondulation', why: '<p>L’alternateur produit du courant alternatif, <b>redressé</b> par un pont de diodes, et le <b>régulateur</b> limite la tension (≈ 14 V). Sur les véhicules récents, l’alternateur est <b>piloté</b> par le calculateur moteur (fil de commande ou LIN) selon l’état de la batterie : la tension peut varier plus.</p>',
    how: '<ol><li>Moteur tournant à ≈ 2 000 tr/min, tous consommateurs coupés : tension aux bornes de la batterie.</li><li>Même régime, phares + dégivrage + ventilation maxi : tension.</li><li>Voltmètre en <b>V alternatif</b> sur les bornes de la batterie : ondulation.</li></ol><p>Vérifie aussi la <b>courroie</b> (tension, état, glissement) et le témoin de charge.</p>', measures: ['u_chg', 'u_chg_c', 'u_ond'],
    decide: function (m) {
      if (m('u_chg').st === 'bad' && m('u_chg').dir === 'high') return { v: 'bad', msg: 'Surcharge (' + r1(m('u_chg').v) + ' V) : régulateur défectueux (ou pilotage de l’alternateur). Risque pour la batterie et les calculateurs.', next: 'end_reg' };
      if (m('u_ond').st === 'bad') return { v: 'bad', msg: 'Ondulation trop forte (' + r1(m('u_ond').v) + ' V AC) : diode du pont redresseur HS. L’alternateur débite moins et perturbe les calculateurs.', next: 'end_alt' };
      if (m('u_chg').st === 'bad' || m('u_chg_c').st === 'bad') return { v: 'bad', msg: 'Charge insuffisante : avant d’accuser l’alternateur, on mesure les chutes de tension des câbles.', next: 'chg_dt' };
      return { v: 'ok', msg: 'Circuit de charge correct.', next: 'suite2' }; } };
  B.chg_dt = { type: 'measure', title: 'Chutes de tension du circuit de charge', why: '<p>Un câble ou une cosse oxydé(e) crée une <b>résistance</b> : l’alternateur produit bien, mais la tension n’arrive pas à la batterie. On la mesure <b>en fonctionnement</b> (sous courant) : un ohmmètre ne voit pas ce défaut.</p>',
    how: '<p>Moteur à 2 000 tr/min, consommateurs allumés. Voltmètre entre les deux extrémités du même câble (pointe sur la borne, pas sur la cosse).</p>', measures: ['dt_alt_p', 'dt_alt_m'],
    decide: function (m) { if (m('dt_alt_p').st === 'bad' || m('dt_alt_m').st === 'bad') return { v: 'bad', msg: 'Chute de tension trop forte sur ' + (m('dt_alt_p').st === 'bad' ? 'le câble +' : 'la masse') + ' : nettoie, resserre ou remplace le câble / la tresse de masse.', next: 'end_cable' }; return { v: 'bad', msg: 'Câbles bons : la courroie (glissement) ou l’alternateur (régulateur, charbons, pilotage) est en cause.', next: 'end_alt' }; } };
  B.suite2 = { type: 'choice', title: 'Contrôler aussi le démarrage ?', choices: [['Oui, circuit de démarrage', 'dem'], ['Non, terminer', 'end_ok']] };
  B.dem = { type: 'measure', title: 'Circuit de démarrage', why: '<p>Le démarreur reçoit sa <b>puissance</b> par le gros câble (borne 30) et sa <b>commande</b> par la borne 50 (solénoïde / relais de démarreur). La commande passe par le contacteur (ou le bouton Start), l’<b>antidémarrage</b>, le contacteur d’<b>embrayage</b> ou la position <b>P / N</b> en boîte auto. On mesure les chutes de tension <b>pendant</b> le démarrage.</p>',
    how: '<ol><li>Batterie chargée et bonne (étapes précédentes).</li><li>Pendant l’action sur la clé : tension à la borne 50, puis chute de tension borne + batterie → borne 30, puis carter démarreur → borne – batterie.</li><li>Si le moteur démarre, empêche-le de démarrer selon la méthode constructeur.</li></ol>', measures: ['u_50', 'dt_dem_p', 'dt_dem_m'],
    decide: function (m) {
      if (m('u_50').st === 'bad') return { v: 'bad', msg: 'Pas (ou pas assez) de commande à la borne 50 (' + r1(m('u_50').v) + ' V) : le démarreur n’est pas en cause, c’est sa commande.', next: 'end_cmd' };
      if (m('dt_dem_p').st === 'bad' || m('dt_dem_m').st === 'bad') return { v: 'bad', msg: 'Chute de tension trop forte sur ' + (m('dt_dem_p').st === 'bad' ? 'le câble + (' + r1(m('dt_dem_p').v) + ' V)' : 'la masse (' + r1(m('dt_dem_m').v) + ' V)') + ' : le démarreur ne reçoit pas assez de courant.', next: 'end_cable' };
      return { v: 'bad', msg: 'Commande et câbles bons, batterie bonne : si le démarreur ne tourne pas ou tourne lentement, il est en cause (solénoïde, charbons, induit, lanceur) — ou le moteur est dur à entraîner (vérifie qu’il tourne à la main).', next: 'end_dem' }; } };
  B.end_ok = end('ok', 'Batterie, charge et démarrage conformes', '<p>Si la panne revient, pense au courant de fuite (mesure après mise en veille complète) et à l’usage (trajets très courts : la batterie ne se recharge jamais complètement).</p>');
  B.end_bat = end('bad', 'Batterie à remplacer', '<p>Remplace-la par la <b>même technologie</b> (AGM / EFB sur Stop & Start) et la même capacité. Sur beaucoup de véhicules récents, il faut <b>déclarer la nouvelle batterie</b> à la valise (capteur de batterie IBS / gestion de charge). Contrôle ensuite la charge.</p>');
  B.end_fuite = end('bad', 'Rechercher le consommateur', '<ol><li>Sans ouvrir le véhicule ni réveiller les calculateurs : mesure la <b>chute de tension aux bornes de chaque fusible</b> (quelques mV = du courant passe dans ce circuit).</li><li>Ou retire les fusibles un par un en surveillant la pince ampèremétrique.</li><li>Suspects fréquents : plafonnier / boîte à gants / coffre, accessoire rajouté, relais collé, calculateur qui ne s’endort pas (lire les défauts, réseau qui reste réveillé : module Multiplexage).</li></ol>');
  B.end_reg = end('bad', 'Régulation de charge', '<p>Régulateur intégré à l’alternateur : remplace le régulateur ou l’alternateur. Alternateur piloté : lis les défauts du calculateur moteur, contrôle le fil / la ligne LIN de pilotage et le capteur de batterie avant de remplacer.</p>');
  B.end_alt = end('bad', 'Alternateur ou courroie', '<p>Contrôle la courroie (tension, glissement, galet tendeur, poulie débrayable), puis remplace l’alternateur (ou pont de diodes, régulateur, charbons). Refais les mesures de charge après réparation.</p>');
  B.end_cable = end('bad', 'Câble ou masse', '<p>Nettoie et resserre les cosses, remplace le câble ou la tresse de masse (moteur / caisse). Refais la mesure de chute de tension sous courant.</p>');
  B.end_cmd = end('bad', 'Commande du démarreur', '<p>Remonte la commande : contacteur ou bouton Start, <b>antidémarrage</b> (voyant, défauts à la valise), contacteur de pédale d’embrayage, position P / N (boîte auto), relais et fusible de démarreur, fil jusqu’à la borne 50.</p>');
  B.end_dem = end('bad', 'Démarreur', '<p>Dépose et remplace le démarreur (ou le solénoïde). Vérifie la couronne du volant moteur (dents abîmées) et le serrage des fixations (elles servent de masse).</p>');

  D.MODULES.charge = { id: 'charge', icon: '🔋', titre: 'Batterie, charge et démarrage', sous: 'Batterie, courant de fuite, alternateur, démarreur', start: 'start', steps: B,
    comprendre: '<h3>Le circuit</h3><p>La <b>batterie</b> (12 V, 6 éléments de 2,1 V) alimente le <b>démarreur</b> (moteur électrique très puissant, commandé par un solénoïde qui pousse le lanceur). Moteur tournant, l’<b>alternateur</b> (entraîné par la courroie) produit du courant alternatif, redressé par les diodes, et le régulateur limite la tension autour de 14 V.</p>' +
      '<div class="tw"><table><tr><th>Contrôle</th><th>Valeur type (12 V)</th></tr><tr><td>Batterie au repos</td><td>12,6 V chargée ; 12,4 V ≈ 75 % ; &lt; 12 V déchargée</td></tr><tr><td>Tension pendant le démarrage</td><td>≥ 9,6 V</td></tr><tr><td>Courant de fuite en veille</td><td>≤ 50 mA</td></tr><tr><td>Tension de charge</td><td>13,5 à 14,8 V</td></tr><tr><td>Ondulation (V AC)</td><td>≤ 0,5 V</td></tr><tr><td>Chute de tension câble + / masse</td><td>≤ 0,5 V / ≤ 0,2 à 0,3 V</td></tr></table></div>' +
      '<div class="box piege"><b>⚠️ Pièges</b><ul><li>Une batterie déchargée se <b>recharge avant d’être testée</b>.</li><li>Les chutes de tension se mesurent <b>sous courant</b> : un ohmmètre ne voit pas une cosse oxydée.</li><li>Débrancher la batterie : d’abord la borne –, rebrancher en dernier la borne – ; certains véhicules demandent des réinitialisations (lève-vitres, toit, direction).</li><li>Stop & Start : batterie AGM / EFB et déclaration à la valise.</li></ul></div>' };
})();
