/* Diagnostic — modules COMMON RAIL, ANTIPOLLUTION, DSFT / BANC DE FREINAGE, FREINAGE.
   Valeurs de référence (TYPES, la valeur constructeur prime) :
   - Cours du site : pompe HP ≈ 200 bar au démarrage → 1 350 bar et plus ; capteur de rail 0,5 V contact mis,
     1 à 1,5 V au démarreur ; conditions SCR (T° moteur > 40 °C, T° cata > 180 °C, régime > 400 tr/min, couple > 5 %) ;
     DSFT : tableau ALFA (parallélisme −1 ± 1 mm, carrossage −0°10′ ± 30′, chasse 3°20′ ± 30′, pivot 10°30′ ± 30′),
     angle inclus, usure rugueuse / lisse, « tire du côté du carrossage le plus positif et de la chasse la plus faible ».
   - Contrôle technique : efficacité frein de service ≥ 50 %, frein de stationnement ≥ 18 %, déséquilibre > 30 % =
     défaillance majeure (au-delà de 20 % : à surveiller).
   - FAP : pression différentielle ≈ 5 à 20 mbar au ralenti, ≤ 150 à 180 mbar vers 3 000 tr/min sur un FAP sain.
   - Retours injecteurs common rail : ≈ 22 ml en 3 min au ralenti moteur chaud (valeur type Bosch) ; surtout, comparer
     les injecteurs entre eux.
   - Basse pression : pompe de gavage électrique ≈ 3 à 8 bar selon système. */
(function () {
  var D = window.DIAG, M = D.MEASURES;
  function mes(id, label, unit, min, max, note) { M[id] = { id: id, label: label, unit: unit, min: min, max: max, note: note || '' }; }
  var free = null;
  function r1(n) { return String(Math.round(n * 10) / 10).replace('.', ','); }
  function end(v, title, html) { return { type: 'end', v: v, title: title, html: html }; }

  /* ========================= COMMON RAIL ========================= */
  mes('n_dem', 'Régime au démarreur (valise ou compte-tours)', 'tr/min', 150, 400, 'Un diesel a besoin d’environ 150 à 200 tr/min pour démarrer.');
  mes('p_rail_dem', 'Pression de rail au démarreur (valise)', 'bar', 150, 400, 'Cours : ≈ 200 bar au démarrage. L’injection n’est autorisée qu’au-delà d’une pression mini (selon moteur et température).');
  mes('u_rail_dem', 'Tension du capteur de pression de rail au démarreur', 'V', 1, 1.5, 'Cours : 0,5 V contact mis, 1 à 1,5 V au démarreur.');
  mes('p_gav', 'Pression de la pompe de gavage électrique (manomètre avant filtre / pompe HP)', 'bar', 2.5, 8, 'Valeur type : 3 à 8 bar selon système. Utilise la valeur constructeur.');
  mes('dep_hp', 'Dépression en entrée de pompe HP (vacuomètre, ralenti)', 'bar', -0.35, -0.02, 'Valeur type : légère dépression (quelques centaines de mbar). Trop forte = colmatage ; proche de 0 = prise d’air.');
  mes('p_cons', 'Pression de rail DEMANDÉE (consigne, valise)', 'bar', free, free);
  mes('p_mes', 'Pression de rail MESURÉE (valise)', 'bar', free, free);
  mes('ret1', 'Retour injecteur n°1', 'ml', free, free); mes('ret2', 'Retour injecteur n°2', 'ml', free, free);
  mes('ret3', 'Retour injecteur n°3', 'ml', free, free); mes('ret4', 'Retour injecteur n°4', 'ml', free, free);
  mes('corr1', 'Correction de débit cylindre 1', 'mg/cp', -3, 3, 'Valeur type : utilise la limite affichée par ta valise (souvent autour de ±2 à ±3 mg/cp).');
  mes('corr2', 'Correction de débit cylindre 2', 'mg/cp', -3, 3, ''); mes('corr3', 'Correction de débit cylindre 3', 'mg/cp', -3, 3, ''); mes('corr4', 'Correction de débit cylindre 4', 'mg/cp', -3, 3, '');
  mes('ps_cons', 'Pression de suralimentation DEMANDÉE (valise, pleine charge)', 'mbar', free, free);
  mes('ps_mes', 'Pression de suralimentation MESURÉE (valise, pleine charge)', 'mbar', free, free);

  var C = {};
  C.start = { type: 'choice', title: 'Quel est le symptôme ?', why: '<p>Sur un common rail, le calculateur n’injecte que si la <b>pression de rail</b> est suffisante. On remonte donc la chaîne : <b>alimentation basse pression → haute pression (pompe, régulateurs, capteur) → injecteurs</b>, sans oublier l’air (turbo, EGR, débitmètre).</p>',
    choices: [['Ne démarre pas / démarre difficilement', 'start_c'], ['Manque de puissance / mode dégradé', 'hp'], ['Fumée noire', 'turbo'], ['Ralenti instable, claquements, fumée au démarrage', 'corr'], ['Défaut sur un capteur ou un actionneur', 'capt']] };
  C.capt = { type: 'info', title: 'Capteur ou actionneur en défaut', html: '<p>Les contrôles électriques (capteur PMH inductif, capteur de phase Hall, capteur de pression de rail, pédale, régulateurs en RCO, injecteurs) sont dans le module <b>🔌 Multiplexage → « Un seul équipement ne marche pas »</b>. Ici, on continue par la partie hydraulique.</p>', bouton: 'Contrôler la pression de rail', next: 'hp' };
  C.start_c = { type: 'measure', title: 'Démarrage : batterie, régime et pression de rail', why: '<p>Trois conditions pour démarrer : un <b>régime suffisant</b> (sinon la pompe HP ne monte pas en pression), une <b>pression de rail mini</b> (sinon le calculateur n’injecte pas) et les <b>informations régime / phase</b>.</p>',
    how: '<ol><li>Valise branchée, paramètres « régime » et « pression de rail » (ou tension du capteur au multimètre).</li><li>Actionne le démarreur 5 à 10 s.</li></ol>', measures: ['ubat', 'n_dem', 'p_rail_dem'],
    decide: function (m) {
      if (m('ubat').st === 'bad' && m('ubat').dir === 'low') return { v: 'bad', msg: 'Batterie faible : charge-la ou remplace-la avant tout.', next: 'end_elec' };
      if (m('n_dem').st === 'bad' && m('n_dem').dir === 'low') return { v: 'bad', msg: 'Régime de démarreur trop faible : batterie, câbles, masses ou démarreur.', next: 'end_elec' };
      if (m('n_dem').v === 0) return { v: 'bad', msg: 'Pas de régime lu : capteur PMH (régime) ou son faisceau — contrôle-le dans le module Multiplexage.', next: 'end_capt' };
      if (m('p_rail_dem').st === 'ok') return { v: 'ok', msg: 'Pression de rail suffisante : le problème vient plutôt des injecteurs (fuite, blocage), de la compression ou du préchauffage.', next: 'ret' };
      return { v: 'bad', msg: 'Pression de rail trop faible au démarreur : on contrôle la basse pression, puis les fuites (retours injecteurs) et la pompe HP.', next: 'bp' };
    } };
  C.bp = { type: 'choice', title: 'Quel type d’alimentation basse pression ?', why: '<p>La pompe HP doit être alimentée en gazole <b>sans air</b>. Soit une <b>pompe de gavage électrique</b> (dans le réservoir) pousse le gazole, soit une <b>pompe de gavage mécanique</b> intégrée à la pompe HP l’aspire (circuit en dépression). Attention : une prise d’air côté dépression n’entraîne pas de fuite, mais aspire de l’air.</p>',
    choices: [['Pompe de gavage électrique (circuit sous pression)', 'bp_el'], ['Pompe de gavage mécanique (circuit en dépression)', 'bp_dep']] };
  C.bp_el = { type: 'measure', title: 'Pression de gavage', why: '<p>Une pression de gavage faible prive la pompe HP de gazole : pression de rail trop basse, surtout en charge.</p>', how: '<p>Manomètre en T sur l’arrivée gazole (avant la pompe HP), contact mis ou moteur tournant selon le système.</p>', measures: ['p_gav'],
    decide: function (m) { var g = m('p_gav'); if (g.st === 'ok') return { v: 'ok', msg: 'Gavage correct : vérifie l’absence d’air (durite transparente), puis la haute pression.', next: 'air' }; if (g.dir === 'low') return { v: 'bad', msg: 'Gavage trop faible : filtre à gazole colmaté, crépine de réservoir encrassée, pompe de gavage (alimentation, relais) ou fuite.', next: 'end_bp' }; return { v: 'warn', msg: 'Pression trop haute : régulateur de basse pression ou retour obstrué.', next: 'end_bp' }; } };
  C.bp_dep = { type: 'measure', title: 'Dépression en entrée de pompe HP', why: '<p>La pompe de gavage mécanique aspire le gazole : on mesure la <b>dépression</b>. Trop forte = elle aspire contre un obstacle (filtre, crépine, tuyau pincé) ; presque nulle = de l’air entre (raccord, joint de filtre, pompe d’amorçage).</p>', how: '<p>Vacuomètre en T avant la pompe HP, moteur au ralenti. Entre une valeur négative (ex. −0,2).</p>', measures: ['dep_hp'],
    decide: function (m) { var d = m('dep_hp'); if (d.st === 'ok') return { v: 'ok', msg: 'Dépression normale : vérifie l’absence de bulles, puis la haute pression.', next: 'air' }; if (d.dir === 'low') return { v: 'bad', msg: 'Dépression trop forte : filtre colmaté, crépine encrassée, tuyau pincé ou paraffinage (grand froid).', next: 'end_bp' }; return { v: 'bad', msg: 'Dépression trop faible : prise d’air (raccords, joint de filtre, pompe d’amorçage, clapet de pression résiduelle).', next: 'end_bp' }; } };
  C.air = { type: 'choice', title: 'Présence d’air dans le gazole ?', why: '<p>Pose une <b>durite transparente</b> avant la pompe HP : des bulles = prise d’air côté alimentation. L’air fait chuter la pression de rail et provoque des ratés.</p>',
    choices: [['Des bulles d’air passent', 'end_air'], ['Gazole sans bulles', 'hp']] };
  C.hp = { type: 'measure', title: 'Haute pression : consigne et mesure', why: '<p>Le calculateur calcule une <b>pression demandée</b> (régime, charge) et la régule en boucle fermée grâce au capteur de rail, avec le régulateur de débit (entrée de pompe) et / ou de pression (sur le rail ou la pompe). On compare la consigne et la mesure.</p>',
    how: '<ol><li>Valise : paramètres « pression de rail demandée » et « mesurée ».</li><li>Relève-les au ralenti, puis en accélération franche (la plus mauvaise des deux situations).</li></ol>', measures: ['p_cons', 'p_mes'],
    decide: function (m) {
      var c = m('p_cons').v, x = m('p_mes').v, e = c ? (x - c) / c * 100 : 0;
      if (Math.abs(e) <= 10) return { v: 'ok', msg: 'Écart ' + r1(e) + ' % : la haute pression suit la consigne. Si le manque de puissance persiste, contrôle l’air (turbo, débitmètre, EGR).', next: 'turbo' };
      if (e < 0) return { v: 'bad', msg: 'Pression mesurée ' + r1(-e) + ' % sous la consigne : fuite interne (retours injecteurs), manque de gavage, régulateur de débit ou pompe HP. On commence par les retours injecteurs.', next: 'ret' };
      return { v: 'bad', msg: 'Pression mesurée ' + r1(e) + ' % au-dessus de la consigne : régulateur de pression bloqué fermé, régulateur de débit bloqué ouvert, ou capteur de rail qui ment (compare sa tension contact mis : 0,5 V).', next: 'end_hp' };
    } };
  C.ret = { type: 'measure', title: 'Débit de retour des injecteurs', why: '<p>Un injecteur usé laisse fuir trop de gazole vers le <b>retour</b> : la pression de rail chute et le moteur démarre mal. On récupère le retour de chaque injecteur dans une éprouvette.</p><p>Valeur type Bosch : environ <b>22 ml en 3 min</b> au ralenti moteur chaud. Mais le plus fiable est de <b>comparer les injecteurs entre eux</b>. Test au démarreur (15 s) si le moteur ne démarre pas.</p>',
    how: '<ol><li>Débranche le retour de chaque injecteur, pose une durite transparente vers une éprouvette graduée (et bouche la rampe de retour).</li><li>Même durée pour tous (ralenti 1 à 3 min, ou démarreur 15 s).</li><li>Entre le volume de chaque injecteur (0 si pas de 4ᵉ cylindre).</li></ol>', measures: ['ret1', 'ret2', 'ret3', 'ret4'],
    decide: function (m) {
      var v = ['ret1', 'ret2', 'ret3', 'ret4'].map(function (k) { return m(k).v; }).filter(function (x) { return x > 0; });
      if (!v.length) return { v: 'warn', msg: 'Aucun retour mesuré : vérifie le montage.', next: 'ret' };
      var sorted = v.slice().sort(function (a, b) { return a - b; }), med = sorted[Math.floor((sorted.length - 1) / 2)];
      var bad = ['ret1', 'ret2', 'ret3', 'ret4'].filter(function (k) { return m(k).v > 0 && m(k).v > med * 2; }).map(function (k) { return k.slice(3); });
      if (bad.length) return { v: 'bad', msg: 'Injecteur(s) n°' + bad.join(', ') + ' : retour plus de 2 fois supérieur aux autres → fuite interne, injecteur à remplacer (puis codage IMA / C2I à la valise).', next: 'end_inj' };
      return { v: 'ok', msg: 'Retours homogènes (médiane ' + med + ' ml) : pas d’injecteur nettement fuyard. Compare avec la valeur constructeur, puis contrôle la pompe HP et les régulateurs.', next: 'end_hp' };
    } };
  C.corr = { type: 'measure', title: 'Corrections de débit par cylindre (équilibrage)', why: '<p>Au ralenti, le calculateur <b>corrige le débit de chaque injecteur</b> pour que tous les cylindres fournissent le même couple (il mesure les accélérations du vilebrequin). Une correction forte montre un cylindre qui travaille mal : injecteur, compression, jeu aux soupapes.</p>',
    how: '<p>Valise, moteur chaud au ralenti, paramètres « corrections de débit » ou « équilibrage ». Entre 0 pour un cylindre inexistant.</p>', measures: ['corr1', 'corr2', 'corr3', 'corr4'],
    decide: function (m) { var bad = ['corr1', 'corr2', 'corr3', 'corr4'].filter(function (k) { return m(k).st === 'bad'; }).map(function (k) { return k.slice(4); }); if (bad.length) return { v: 'bad', msg: 'Cylindre(s) n°' + bad.join(', ') + ' hors limite : contrôle l’injecteur (retour, codage), puis la compression de ce cylindre.', next: 'ret' }; return { v: 'ok', msg: 'Corrections dans les limites : cherche du côté du préchauffage, de l’air (EGR, turbo) ou d’un capteur.', next: 'turbo' }; } };
  C.turbo = { type: 'measure', title: 'Suralimentation : consigne et mesure', why: '<p>Le manque d’air donne de la <b>fumée noire</b> et un manque de puissance. Le calculateur pilote le turbo (géométrie variable ou wastegate) par une électrovanne en RCO ou un actionneur électrique, et compare la pression mesurée par le capteur à la consigne.</p>',
    how: '<p>Valise, essai en charge (3ᵉ rapport, pied à fond de 1 500 à 3 500 tr/min) : relève la pression demandée et la pression mesurée au même moment.</p>', measures: ['ps_cons', 'ps_mes'],
    decide: function (m) { var c = m('ps_cons').v, x = m('ps_mes').v, e = c ? (x - c) / c * 100 : 0; if (Math.abs(e) <= 10) return { v: 'ok', msg: 'Suralimentation conforme (écart ' + r1(e) + ' %) : contrôle le débitmètre, l’EGR (module Antipollution) et le FAP.', next: 'end_ok' }; if (e < 0) return { v: 'bad', msg: 'Sous-suralimentation (' + r1(e) + ' %) : fuite d’air (durites, échangeur), turbo ou géométrie variable grippée, électrovanne de commande, capteur de suralimentation, FAP colmaté.', next: 'end_turbo' }; return { v: 'bad', msg: 'Sur-suralimentation (+' + r1(e) + ' %) : géométrie variable grippée en position fermée, électrovanne de commande, capteur.', next: 'end_turbo' }; } };
  C.end_elec = end('bad', 'Alimentation électrique / démarrage', '<p>Charge ou remplace la batterie, contrôle les câbles, les masses et le démarreur, puis recommence le diagnostic.</p>');
  C.end_capt = end('bad', 'Capteur de régime / phase', '<p>Contrôle le capteur et son faisceau avec le module <b>Multiplexage → capteur inductif / Hall</b>.</p>');
  C.end_bp = end('bad', 'Défaut de basse pression', '<p>Remplace le filtre, contrôle la crépine, les tuyaux et la pompe de gavage, <b>purge</b> le circuit (en finissant par la culasse / la pompe HP), puis recontrôle la pression de rail.</p>');
  C.end_air = end('bad', 'Prise d’air côté alimentation', '<p>Recherche la prise d’air entre le réservoir et la pompe HP : raccords rapides, joint de filtre, pompe d’amorçage, clapet de pression résiduelle. Purge ensuite le circuit.</p>');
  C.end_hp = end('warn', 'Pompe HP ou régulation haute pression', '<p>Contrôle les régulateurs (résistance, commande RCO) et le capteur de rail (module Multiplexage). Si tout est bon, la pompe HP est suspecte : vérifie la présence de limaille (filtre, régulateur) avant tout remplacement, sinon il faut remplacer tout le circuit HP.</p>');
  C.end_inj = end('bad', 'Injecteur fuyard', '<p>Remplace l’injecteur (rondelle pare-flamme neuve, tuyau HP neuf selon constructeur), fais le <b>codage injecteur</b> à la valise, puis refais le test de retour.</p>');
  C.end_turbo = end('bad', 'Défaut de suralimentation', '<p>Contrôle dans l’ordre : durites et échangeur (fuite), électrovanne / actionneur de commande, géométrie variable (libre sur toute sa course), capteur de suralimentation, FAP et EGR.</p>');
  C.end_ok = end('ok', 'Contrôles conformes', '<p>Alimentation, haute pression et suralimentation sont bonnes : continue avec le module Antipollution (EGR, FAP) et vérifie les défauts mémorisés.</p>');

  /* ========================= ANTIPOLLUTION ========================= */
  mes('dp_ral', 'Pression différentielle du FAP au ralenti (moteur chaud)', 'mbar', 3, 20, 'Valeur type : 5 à 20 mbar sur un FAP sain ; au-delà de 50 mbar, filtre très chargé.');
  mes('dp_3000', 'Pression différentielle du FAP à 3 000 tr/min à vide', 'mbar', 20, 180, 'Valeur type : ne dépasse pas 150 à 180 mbar sur un FAP sain ; plus de 250 mbar = fortement colmaté.');
  mes('egr_cons', 'Position de vanne EGR DEMANDÉE (valise)', '%', free, free);
  mes('egr_mes', 'Position de vanne EGR MESURÉE (valise)', '%', free, free);
  mes('adblue', 'Concentration d’AdBlue (réfractomètre)', '%', 31.8, 33.2, 'AdBlue = 32,5 % d’urée (± 0,7).');
  mes('t_cata', 'Température du catalyseur SCR (valise)', '°C', 180, 700, 'Cours : le SCR s’active au-delà de 180 °C.');
  mes('nox_am', 'NOx en amont du SCR (valise)', 'ppm', free, free);
  mes('nox_av', 'NOx en aval du SCR (valise)', 'ppm', free, free);
  mes('q_dem', 'Test du doseur : quantité DEMANDÉE (valise)', 'ml', free, free);
  mes('q_rec', 'Test du doseur : quantité RECUEILLIE (éprouvette)', 'ml', free, free);
  mes('l_min', 'Sonde lambda amont : tension mini (moteur chaud, 2 500 tr/min)', 'V', 0, 0.3, 'Sonde à oxyde de zirconium : oscille entre environ 0,1 V (mélange pauvre) et 0,9 V (mélange riche).');
  mes('l_max', 'Sonde lambda amont : tension maxi', 'V', 0.7, 1, '');
  mes('r_chauf', 'Résistance de chauffage de la sonde lambda', 'Ω', 2, 15, 'Valeur type : quelques ohms à froid. Utilise la valeur constructeur.');

  var P = {};
  P.start = { type: 'choice', title: 'Quel système contrôler ?', why: '<p>Les systèmes antipollution : <b>EGR</b> (recirculation des gaz, baisse des NOx), <b>FAP</b> (piège les particules, régénéré en brûlant les suies), <b>SCR / AdBlue</b> (l’ammoniac réduit les NOx dans un catalyseur), <b>sonde lambda et catalyseur</b> (essence). Un défaut antipollution allume le voyant moteur et peut mettre le moteur en mode dégradé.</p>',
    choices: [['Voyant FAP / colmatage / régénération', 'fap'], ['Vanne EGR (défaut, manque de puissance, fumée)', 'egr'], ['Défaut AdBlue / SCR', 'scr'], ['Essence : sonde lambda / catalyseur', 'lambda']] };
  P.fap = { type: 'measure', title: 'FAP : pression différentielle', why: '<p>Un capteur mesure la <b>différence de pression</b> entre l’entrée et la sortie du FAP. Plus il est chargé en suie, plus elle monte. Le calculateur s’en sert pour déclencher les régénérations (post-injection pour monter à environ 600 °C). La mesure à 3 000 tr/min est la plus parlante.</p>',
    how: '<ol><li>Moteur chaud (> 80 °C), valise : paramètre « pression différentielle FAP ».</li><li>Relève au ralenti, puis maintiens 3 000 tr/min à vide.</li></ol>', measures: ['dp_ral', 'dp_3000'],
    decide: function (m) { var a = m('dp_ral').v, b = m('dp_3000').v;
      if (b < 5 && a < 2) return { v: 'bad', msg: 'Pression quasi nulle même à 3 000 tr/min : durites du capteur débranchées ou percées, capteur HS, ou FAP fissuré / vidé.', next: 'end_fap_capt' };
      if ((m('dp_3000').st === 'bad' && m('dp_3000').dir === 'high') || m('dp_ral').v > 50) return { v: 'bad', msg: 'Pression différentielle trop haute : FAP colmaté. Il faut trouver pourquoi il ne se régénère pas avant de le nettoyer ou de le remplacer.', next: 'fap_cause' };
      if (b < m('dp_3000').min) return { v: 'warn', msg: 'Pression un peu basse : vérifie les durites du capteur et l’étanchéité du FAP.', next: 'end_fap_capt' };
      return { v: 'ok', msg: 'Pression différentielle normale : FAP sain. Si le voyant persiste, contrôle le capteur (dérive) et l’additif (PSA).', next: 'end_ok' }; } };
  P.fap_cause = { type: 'choice', title: 'Pourquoi le FAP s’est-il colmaté ?', why: '<p>La régénération a besoin de <b>trajets assez longs</b> et de <b>température</b>. Un moteur qui produit trop de suie (injecteur, EGR, turbo) encrasse aussi le FAP. Sur PSA, un <b>additif</b> (cérine, Eolys) aide à brûler les suies : réservoir vide = pas de régénération.</p>',
    choices: [['Uniquement des trajets courts', 'end_fap_trajet'], ['Véhicule PSA : réservoir d’additif bas ou défaut additif', 'end_fap_add'], ['Fumée, consommation d’huile ou défaut EGR / turbo / injecteur', 'end_fap_moteur'], ['Je ne sais pas', 'end_fap_trajet']] };
  P.egr = { type: 'measure', title: 'Vanne EGR : consigne et position', why: '<p>La vanne EGR renvoie une partie des gaz d’échappement à l’admission pour baisser la température de combustion (moins de NOx). Encrassée, elle reste ouverte (manque de puissance, fumée noire) ou bloquée fermée (défaut, NOx élevés). Le calculateur connaît sa position grâce à un capteur de recopie.</p>',
    how: '<p>Valise : test actionneur EGR ou moteur au ralenti chaud. Relève la position demandée et la position mesurée.</p>', measures: ['egr_cons', 'egr_mes'],
    decide: function (m) { var e = m('egr_mes').v - m('egr_cons').v; if (Math.abs(e) <= 10) return { v: 'ok', msg: 'La vanne suit la consigne (écart ' + r1(e) + ' points) : contrôle l’étanchéité du circuit, le refroidisseur EGR et le débitmètre.', next: 'end_ok' }; return { v: 'bad', msg: 'La vanne ne suit pas la consigne (écart ' + r1(e) + ' points) : vanne encrassée ou grippée, moteur de vanne ou capteur de recopie. Contrôle-la électriquement (module Multiplexage → électrovanne) et nettoie-la.', next: 'end_egr' }; } };
  P.scr = { type: 'measure', title: 'SCR : qualité de l’AdBlue et conditions d’activation', why: '<p>Le calculateur de dosage injecte l’AdBlue en amont du catalyseur SCR ; l’urée se transforme en <b>ammoniac</b> qui réduit les NOx. Conditions d’activation (cours PPLOG) : T° moteur > 40 °C, <b>T° catalyseur > 180 °C</b>, régime > 400 tr/min, couple > 5 %. Un AdBlue dilué ou pollué fait baisser l’efficacité.</p>',
    how: '<ol><li>Prélève de l’AdBlue et mesure sa concentration au réfractomètre.</li><li>Moteur chaud, roulage : relève la température du catalyseur à la valise.</li></ol>', measures: ['adblue', 't_cata'],
    decide: function (m) { if (m('adblue').st === 'bad') return { v: 'bad', msg: 'AdBlue hors norme (dilué, pollué ou vieilli) : vidange complète du réservoir (vanne multivoies si équipée), rinçage, remplissage neuf.', next: 'end_scr' }; if (m('t_cata').st === 'bad' && m('t_cata').dir === 'low') return { v: 'warn', msg: 'Catalyseur trop froid : le SCR n’est pas activé (roule plus longtemps). Vérifie aussi les sondes de température.', next: 'scr_nox' }; return { v: 'ok', msg: 'AdBlue conforme et SCR en température : on vérifie l’efficacité (NOx).', next: 'scr_nox' }; } };
  P.scr_nox = { type: 'measure', title: 'SCR : efficacité (capteurs NOx)', why: '<p>Deux capteurs NOx (avant et après le catalyseur SCR) permettent au calculateur de vérifier l’<b>efficacité</b> : les NOx doivent nettement baisser après le catalyseur.</p>', how: '<p>Roulage stabilisé, catalyseur chaud : relève les NOx amont et aval à la valise.</p>', measures: ['nox_am', 'nox_av'],
    decide: function (m) { var a = m('nox_am').v, b = m('nox_av').v, e = a ? (a - b) / a * 100 : 0; if (e >= 60) return { v: 'ok', msg: 'Efficacité ≈ ' + Math.round(e) + ' % : le SCR travaille. Si le défaut persiste, fais le test du doseur.', next: 'scr_dos' }; return { v: 'bad', msg: 'Efficacité faible (≈ ' + Math.round(e) + ' %) : dosage insuffisant (doseur, pompe, filtre, cristaux d’urée), capteur NOx défaillant ou catalyseur SCR usé. Test du doseur.', next: 'scr_dos' }; } };
  P.scr_dos = { type: 'measure', title: 'SCR : test du doseur (quantité injectée)', why: '<p>La valise commande le doseur pendant un temps donné : on recueille l’AdBlue dans une éprouvette et on compare à la quantité demandée. Un doseur bouché par des cristaux dose trop peu.</p>', how: '<p>Dépose le doseur (reste branché), place-le dans une éprouvette, lance le test à la valise.</p>', measures: ['q_dem', 'q_rec'],
    decide: function (m) { var d = m('q_dem').v, r = m('q_rec').v, e = d ? (r - d) / d * 100 : 0; if (Math.abs(e) <= 15) return { v: 'ok', msg: 'Dosage correct (écart ' + r1(e) + ' %) : si l’efficacité reste faible, suspecte les capteurs NOx ou le catalyseur SCR.', next: 'end_scr' }; return { v: 'bad', msg: 'Écart de dosage ' + r1(e) + ' % : doseur encrassé (cristaux), pompe AdBlue, filtre ou tuyau (gel, bouchon).', next: 'end_scr' }; } };
  P.lambda = { type: 'measure', title: 'Essence : sonde lambda amont', why: '<p>La sonde lambda amont mesure l’oxygène restant dans l’échappement : le calculateur ajuste l’injection pour rester à <b>λ = 1</b>. Une sonde à oxyde de zirconium <b>oscille</b> rapidement entre ≈ 0,1 V (pauvre) et ≈ 0,9 V (riche). Elle doit être chaude (résistance de chauffage).</p>',
    how: '<ol><li>Moteur chaud, 2 500 tr/min stabilisés : relève la tension mini et maxi (valise ou oscilloscope).</li><li>Sonde débranchée : résistance de chauffage entre ses 2 fils de chauffage.</li></ol>', measures: ['l_min', 'l_max', 'r_chauf'],
    decide: function (m) { if (m('r_chauf').st === 'bad') return { v: 'bad', msg: 'Chauffage de sonde HS : la sonde met trop de temps à fonctionner → remplace la sonde (contrôle aussi fusible et relais).', next: 'end_lambda' }; if (m('l_min').st === 'bad' || m('l_max').st === 'bad') return { v: 'bad', msg: 'La sonde n’oscille pas sur toute la plage : sonde paresseuse ou empoisonnée, ou mélange réellement trop riche / pauvre (prise d’air, injecteur, pression d’essence). Contrôle avant de remplacer.', next: 'end_lambda' }; return { v: 'ok', msg: 'Sonde amont correcte : on contrôle le catalyseur avec la sonde aval.', next: 'cata' }; } };
  P.cata = { type: 'choice', title: 'Essence : sonde aval (catalyseur)', why: '<p>Un catalyseur en bon état <b>stocke l’oxygène</b> : la sonde aval reste <b>stable</b> (≈ 0,6 à 0,7 V). Si elle oscille comme la sonde amont, le catalyseur ne fait plus son travail.</p>',
    choices: [['La sonde aval reste stable', 'end_ok'], ['La sonde aval oscille comme la sonde amont', 'end_cata']] };
  P.end_ok = end('ok', 'Système antipollution conforme', '<p>Efface les défauts, fais un essai routier et relis les paramètres.</p>');
  P.end_fap_capt = end('bad', 'Capteur de pression différentielle ou FAP', '<p>Contrôle les durites du capteur (percées, inversées, débranchées), le capteur (alimentation 5 V, signal) puis l’état du FAP.</p>');
  P.end_fap_trajet = end('warn', 'FAP colmaté par manque de régénération', '<p>Régénération forcée à la valise (ou roulage prolongé sur voie rapide) si la charge le permet ; au-delà, nettoyage ou remplacement. Informe le client sur l’usage (trajets courts).</p>');
  P.end_fap_add = end('bad', 'Additif FAP (PSA)', '<p>Remplis le réservoir d’additif, contrôle la pompe d’additif, puis <b>réinitialise le niveau</b> à la valise et lance une régénération.</p>');
  P.end_fap_moteur = end('bad', 'Le moteur produit trop de suie', '<p>Répare d’abord la cause (injecteur, EGR, turbo, consommation d’huile), sinon le FAP se recolmatera. Puis régénération ou nettoyage.</p>');
  P.end_egr = end('bad', 'Vanne EGR', '<p>Nettoie ou remplace la vanne, fais l’<b>apprentissage</b> de sa position à la valise, efface les défauts.</p>');
  P.end_scr = end('warn', 'Système SCR / AdBlue', '<p>Traite dans l’ordre : qualité de l’AdBlue, cristaux (doseur, tuyaux), pompe et filtre, capteurs NOx, catalyseur. Fais les apprentissages demandés par la valise.</p>');
  P.end_lambda = end('bad', 'Sonde lambda', '<p>Remplace la sonde si elle est en cause, sinon corrige le mélange (prise d’air, injecteur, pression d’essence). Efface les adaptations.</p>');
  P.end_cata = end('bad', 'Catalyseur inefficace', '<p>Remplace le catalyseur, mais cherche d’abord pourquoi il est mort : ratés d’allumage, consommation d’huile, mélange trop riche.</p>');

  /* ========================= DSFT ========================= */
  mes('par', 'Parallélisme total (+ = pincement, − = ouverture)', 'mm', -2, 0, 'Exemple de cours (tableau ALFA) : −1 ± 1 mm. Saisis la valeur constructeur de ton véhicule.');
  mes('carG', 'Carrossage gauche', '°', -0.667, 0.333, 'Exemple de cours : −0°10′ ± 30′.'); mes('carD', 'Carrossage droit', '°', -0.667, 0.333, 'Exemple de cours : −0°10′ ± 30′.');
  mes('chG', 'Chasse gauche', '°', 2.833, 3.833, 'Exemple de cours : 3°20′ ± 30′.'); mes('chD', 'Chasse droite', '°', 2.833, 3.833, 'Exemple de cours : 3°20′ ± 30′.');
  mes('pvG', 'Inclinaison de pivot gauche', '°', 10, 11, 'Exemple de cours : 10°30′ ± 30′.'); mes('pvD', 'Inclinaison de pivot droite', '°', 10, 11, 'Exemple de cours : 10°30′ ± 30′.');
  mes('fAvG', 'Banc : effort de freinage AV gauche (maxi)', 'daN', free, free); mes('fAvD', 'Banc : effort de freinage AV droit (maxi)', 'daN', free, free);
  mes('fArG', 'Banc : effort de freinage AR gauche (maxi)', 'daN', free, free); mes('fArD', 'Banc : effort de freinage AR droit (maxi)', 'daN', free, free);
  mes('fPG', 'Banc : frein de stationnement gauche', 'daN', free, free); mes('fPD', 'Banc : frein de stationnement droit', 'daN', free, free);
  mes('masse', 'Masse du véhicule (pesée au banc ou carte grise, rubrique G)', 'kg', free, free);

  var G = {};
  G.start = { type: 'choice', title: 'Que veux-tu contrôler ?', why: '<p>La DSFT regroupe la <b>géométrie</b> (angles du train), les <b>pneus</b> et le <b>freinage au banc</b>. L’usure des pneus et le comportement (le véhicule tire) orientent vers le bon contrôle.</p>',
    choices: [['Analyser un relevé de géométrie (banc de géométrie)', 'geo'], ['Usure anormale d’un pneu', 'usure'], ['Le véhicule tire d’un côté en roulant', 'tire'], ['Analyser un passage au banc de freinage', 'banc']] };
  G.geo = { type: 'measure', title: 'Relevé de géométrie', why: '<p>Rappels du cours : <b>parallélisme</b> = différence d’écartement avant / arrière (vue de dessus) ; <b>carrossage</b> = angle plan de roue / verticale (vue de face) ; <b>pivot</b> = axe de pivot / verticale (vue de face) ; <b>chasse</b> = axe de pivot / verticale (vue de côté). <b>Angle inclus = pivot + carrossage</b> (+ 90°) : angle de diagnostic.</p><p>Les tolérances changent d’un véhicule à l’autre : clique sur <b>« J’ai la valeur constructeur »</b> pour chaque angle (fiche du banc).</p>',
    how: '<p>Entre les valeurs du relevé : en degrés décimaux (<b>-0,15</b>) ou en degrés et minutes (<b>-0°09</b>).</p>', measures: ['par', 'carG', 'carD', 'chG', 'chD', 'pvG', 'pvD'],
    decide: function (m) {
      var out = [], v = 'ok';
      var hors = ['par', 'carG', 'carD', 'chG', 'chD', 'pvG', 'pvD'].filter(function (k) { return m(k).st !== 'ok'; });
      if (hors.length) { v = 'bad'; out.push('Hors tolérance ou en limite : ' + hors.map(function (k) { return D.MEASURES[k].label.replace(/\s*\(.*\)/, '').toLowerCase(); }).join(', ') + '.'); }
      var iG = m('pvG').v + m('carG').v, iD = m('pvD').v + m('carD').v, di = Math.abs(iG - iD);
      out.push('Angle inclus (pivot + carrossage) : G ' + deg(iG) + ', D ' + deg(iD) + '.');
      var geoBad = ['carG', 'carD', 'pvG', 'pvD'].some(function (k) { return m(k).st !== 'ok'; });
      if (geoBad) out.push(di <= 0.5 ? 'Angle inclus identique G / D : la fusée n’est pas tordue, c’est la position du pivot qui a bougé → triangle, berceau ou châssis.' : 'Angle inclus différent G / D (' + deg(di) + ') → fusée, porte-fusée et / ou jambe de force (pièce tordue).');
      if (m('chG').st !== 'ok' || m('chD').st !== 'ok') out.push('Chasse hors tolérance → tirant, triangle ou longeron.');
      if (Math.abs(m('carG').v - m('carD').v) > 0.5 || Math.abs(m('chG').v - m('chD').v) > 0.5) out.push('Le véhicule tire du côté du carrossage le plus positif (' + (m('carG').v > m('carD').v ? 'gauche' : 'droite') + ') et de la chasse la plus faible (' + (m('chG').v < m('chD').v ? 'gauche' : 'droite') + ').');
      if (m('par').st !== 'ok') out.push(m('par').v > m('par').max ? 'Trop de pincement → usure rugueuse côté extérieur.' : 'Trop d’ouverture → usure rugueuse côté intérieur.');
      out.push('Ordre de réglage : hauteur de caisse → chasse → pivot → carrossage → hauteur de crémaillère → parallélisme en dernier (valeur à la barre d’accouplement, répartition à la barre de direction, volant bloqué droit).');
      return { v: v, msg: out.join(' '), next: v === 'ok' ? 'end_geo_ok' : 'end_geo' };
    } };
  G.usure = { type: 'choice', title: 'Quel type d’usure ?', why: '<p>Cours : usure <b>rugueuse</b> (en dents de scie, on sent des arêtes au toucher) = <b>parallélisme</b> ; usure <b>lisse</b> = <b>carrossage</b>. Le côté (intérieur / extérieur) donne le sens du défaut.</p>',
    choices: [['Rugueuse à l’intérieur de la bande', 'u_ouv'], ['Rugueuse à l’extérieur de la bande', 'u_pinc'], ['Lisse à l’intérieur', 'u_cneg'], ['Lisse à l’extérieur', 'u_cpos'], ['Au centre de la bande', 'u_surg'], ['Sur les deux bords', 'u_sousg'], ['En facettes / méplats', 'u_fac']] };
  G.u_ouv = end('bad', 'Trop d’ouverture (parallélisme)', '<p>Usure rugueuse intérieure = parallélisme en <b>ouverture</b> excessive. Contrôle les rotules et biellettes de direction, puis règle le parallélisme au banc de géométrie.</p>');
  G.u_pinc = end('bad', 'Trop de pincement (parallélisme)', '<p>Usure rugueuse extérieure = <b>pincement</b> excessif. Contrôle les rotules et biellettes, puis règle le parallélisme.</p>');
  G.u_cneg = end('bad', 'Carrossage trop négatif', '<p>Usure lisse intérieure = carrossage trop négatif (roue penchée vers l’intérieur en haut). Contrôle hauteur de caisse, silentblocs, triangle, jambe de force ; relevé de géométrie.</p>');
  G.u_cpos = end('bad', 'Carrossage trop positif', '<p>Usure lisse extérieure = carrossage trop positif. Contrôle le train (pièce tordue après un choc) et fais un relevé de géométrie.</p>');
  G.u_surg = end('warn', 'Surgonflage', '<p>Usure au centre = pneu trop gonflé. Règle la pression (à froid, valeur constructeur sur la porte ou la trappe à carburant).</p>');
  G.u_sousg = end('warn', 'Sous-gonflage', '<p>Usure sur les deux bords = pneu sous-gonflé (échauffement, consommation). Règle la pression et cherche une fuite lente (valve, jante, clou).</p>');
  G.u_fac = end('bad', 'Amortisseurs / équilibrage', '<p>Usure en facettes (méplats) = la roue rebondit : <b>amortisseurs</b> HS, et / ou roue mal équilibrée, voile de jante. Contrôle les amortisseurs et équilibre les roues.</p>');
  G.tire = { type: 'choice', title: 'Le véhicule tire : dans quelle situation ?', why: '<p>Un véhicule qui tire en roulant n’a pas la même cause qu’un véhicule qui tire au freinage.</p>',
    choices: [['En roulant, sans freiner', 'tire_r'], ['Seulement au freinage', 'tire_f']] };
  G.tire_r = { type: 'info', title: 'Tire en roulant', html: '<ol><li><b>Pressions des pneus</b> gauche / droite identiques, pneus de même modèle et même usure (inverser les roues AV : si le tirage change de côté, c’est un pneu).</li><li>Frein qui frotte (étrier grippé : jante plus chaude d’un côté).</li><li><b>Géométrie</b> : le véhicule tire du côté du <b>carrossage le plus positif</b> et de la <b>chasse la plus faible</b>.</li></ol>', bouton: 'Analyser un relevé de géométrie', next: 'geo' };
  G.tire_f = { type: 'info', title: 'Tire au freinage', html: '<p>Au freinage, le véhicule tire du côté qui <b>freine le plus</b> : c’est l’<b>autre côté</b> qui freine mal (cours : « tire à gauche = c’est le côté droit qui freine mal »). Causes : étrier ou piston grippé, garnitures grasses, flexible gonflé ou obstrué. Le passage au banc le confirme.</p>', bouton: 'Analyser un passage au banc', next: 'banc' };
  G.banc = { type: 'measure', title: 'Banc de freinage : efforts relevés', why: '<p>Le banc mesure l’<b>effort de freinage de chaque roue</b>. On calcule :</p><ul><li><b>Déséquilibre</b> par essieu = (effort maxi − effort mini) / effort maxi × 100. Plus de 30 % = défaillance majeure au contrôle technique (à surveiller dès 20 %).</li><li><b>Efficacité</b> = somme des efforts / poids du véhicule × 100. Frein de service ≥ <b>50 %</b>, frein de stationnement ≥ <b>18 %</b>.</li></ul><p>Pendant la mesure, surveille aussi la <b>fluctuation</b> de l’effort sur un tour de roue (ovalisation : disque voilé ou tambour ovalisé).</p>',
    how: '<p>Entre les efforts maxi en daN (1 daN = 10 N) et la masse du véhicule. Entre 0 pour une valeur non mesurée.</p>', measures: ['fAvG', 'fAvD', 'fArG', 'fArD', 'fPG', 'fPD', 'masse'],
    decide: function (m) {
      function des(a, b) { var mx = Math.max(a, b); return mx ? (mx - Math.min(a, b)) / mx * 100 : 0; }
      var dAv = des(m('fAvG').v, m('fAvD').v), dAr = des(m('fArG').v, m('fArD').v), P = m('masse').v * 9.81 / 10;
      var eS = P ? (m('fAvG').v + m('fAvD').v + m('fArG').v + m('fArD').v) / P * 100 : 0, eP = P ? (m('fPG').v + m('fPD').v) / P * 100 : 0;
      var v = 'ok', out = [];
      function lvl(d, nom) { if (d > 30) { v = 'bad'; return nom + ' : déséquilibre ' + r1(d) + ' % ❌ (défaillance majeure > 30 %).'; } if (d > 20) { if (v === 'ok') v = 'warn'; return nom + ' : déséquilibre ' + r1(d) + ' % ⚠️ (à surveiller, > 20 %).'; } return nom + ' : déséquilibre ' + r1(d) + ' % ✅.'; }
      out.push(lvl(dAv, 'Essieu AV')); out.push(lvl(dAr, 'Essieu AR'));
      if (P) { out.push('Efficacité frein de service : ' + r1(eS) + ' % ' + (eS >= 50 ? '✅' : '❌ (mini 50 %)') + '.'); if (eS < 50) v = 'bad'; if (m('fPG').v + m('fPD').v > 0) { out.push('Efficacité frein de stationnement : ' + r1(eP) + ' % ' + (eP >= 18 ? '✅' : '❌ (mini 18 %)') + '.'); if (eP < 18) v = 'bad'; } }
      var faible = [['AV gauche', m('fAvG').v, m('fAvD').v], ['AV droit', m('fAvD').v, m('fAvG').v], ['AR gauche', m('fArG').v, m('fArD').v], ['AR droit', m('fArD').v, m('fArG').v]].filter(function (x) { return x[2] && x[1] < x[2] * 0.8; }).map(function (x) { return x[0]; });
      if (faible.length) out.push('Roue(s) qui freinent le moins : ' + faible.join(', ') + ' → contrôle étrier / cylindre de roue, garnitures (grasses, vitrifiées), flexible.');
      return { v: v, msg: out.join(' '), next: v === 'ok' ? 'end_banc_ok' : 'end_banc' };
    } };
  G.end_geo_ok = end('ok', 'Géométrie conforme', '<p>Tous les angles sont dans les tolérances. Si un défaut de comportement persiste : pneus, pressions, amortisseurs, jeux dans les rotules et silentblocs.</p>');
  G.end_geo = end('bad', 'Géométrie à corriger', '<p>Remplace d’abord les pièces tordues ou usées (voir le verdict), puis règle dans l’ordre : hauteur de caisse → chasse → pivot → carrossage → hauteur de crémaillère → <b>parallélisme en dernier</b>. Refais un relevé après réglage.</p>');
  G.end_banc_ok = end('ok', 'Freinage conforme au banc', '<p>Déséquilibre et efficacité conformes. Vérifie aussi l’état des disques, plaquettes et du liquide (module Freinage).</p>');
  G.end_banc = end('bad', 'Freinage à reprendre', '<p>Traite la roue qui freine le moins : étrier / piston grippé, garnitures grasses (fuite de liquide ou de joint spi), flexible, réglage du frein de stationnement. Remplace toujours les garnitures <b>par essieu</b>. Refais un passage au banc.</p>');

  /* ========================= FREINAGE ========================= */
  mes('eau_lf', 'Teneur en eau du liquide de frein (testeur)', '%', 0, 2, 'Au-delà de 2 à 3 % d’eau, le point d’ébullition chute : liquide à remplacer.');
  mes('dep_sv', 'Dépression de la pompe à vide / servofrein (valeur absolue)', 'bar', 0.6, 0.95, 'Valeur type : 0,6 à 0,9 bar de dépression moteur tournant.');
  mes('i_abs_lo', 'Capteur ABS actif : courant niveau bas', 'mA', 5, 9, 'Capteur actif (2 fils, magnéto-résistif / Hall) : signal en courant d’environ 7 mA et 14 mA.');
  mes('i_abs_hi', 'Capteur ABS actif : courant niveau haut', 'mA', 12, 17, '');
  mes('voile', 'Voile du disque (comparateur)', 'mm', 0, 0.05, 'Valeur type : quelques centièmes de mm maxi. Utilise la valeur constructeur.');
  mes('marge_d', 'Épaisseur du disque − cote mini gravée sur le disque', 'mm', 0, Infinity, 'L’épaisseur doit rester au-dessus de la cote mini (gravée sur le disque ou dans la doc).');
  mes('ep_plaq', 'Épaisseur de garniture restante (la plus usée)', 'mm', 3, Infinity, 'Remplacement conseillé sous 2 à 3 mm (témoin d’usure).');

  var F = {};
  F.start = { type: 'info', title: 'Identifier le circuit de freinage', html: '<p>Un véhicule léger a un <b>maître-cylindre tandem</b> : deux circuits indépendants. Suis les deux canalisations qui sortent du maître-cylindre (ou du bloc ABS) :</p><ul><li><b>Circuit en X (diagonal)</b> : un circuit freine AV gauche + AR droit, l’autre AV droit + AR gauche. Si un circuit fuit, il reste une roue AV et une roue AR (freinage équilibré). C’est le montage le plus courant sur les tractions.</li><li><b>Circuit en H (AV / AR)</b> : un circuit pour l’AV, un pour l’AR. Si le circuit AV fuit, il ne reste que l’AR.</li></ul><p>Repère aussi : <b>ABS / ESP</b> (bloc hydraulique avec calculateur), <b>correcteur / répartiteur</b> AR (ou répartition électronique EBV), <b>frein de stationnement</b> à câble ou électrique.</p>', bouton: 'Choisir le symptôme', next: 'symp' };
  F.symp = { type: 'choice', title: 'Quel est le symptôme ?', choices: [['Pédale longue, spongieuse ou qui s’enfonce', 'pedale'], ['Pédale dure, freinage peu assisté', 'assist'], ['Le véhicule tire au freinage', 'tire'], ['Voyant ABS / ESP allumé', 'abs'], ['Vibrations ou bruit au freinage', 'vib'], ['Frein de stationnement inefficace', 'parc']] };
  F.pedale = { type: 'choice', title: 'Comment se comporte la pédale ?', why: '<p>La pédale renseigne sur le circuit : <b>spongieuse</b> = air ou liquide qui bout ; <b>s’enfonce lentement</b> pied maintenu = fuite interne du maître-cylindre (coupelles) ; <b>longue</b> avec niveau qui baisse = fuite externe ; pédale longue en circuit X = un circuit hors service (une diagonale).</p>',
    choices: [['Spongieuse, élastique', 'lf'], ['S’enfonce lentement pied maintenu, sans fuite visible', 'end_mc'], ['Longue et le niveau du bocal baisse', 'end_fuite'], ['Longue, niveau stable (après intervention ou freins arrière)', 'end_reglage']] };
  F.lf = { type: 'measure', title: 'État du liquide de frein', why: '<p>Le liquide de frein (DOT 4…) est <b>hygroscopique</b> : il absorbe l’humidité. Son point d’ébullition baisse ; en freinage appuyé, il bout, forme des bulles de vapeur compressibles → pédale spongieuse. De l’air après une intervention donne le même symptôme.</p>', how: '<p>Testeur de teneur en eau (ou de point d’ébullition) dans le bocal.</p>', measures: ['eau_lf'],
    decide: function (m) { if (m('eau_lf').st === 'ok') return { v: 'ok', msg: 'Liquide correct : la pédale spongieuse vient d’air dans le circuit (purge complète, en commençant par la roue la plus éloignée ou selon l’ordre constructeur ; purge du bloc ABS à la valise si besoin).', next: 'end_purge' }; return { v: 'bad', msg: 'Liquide chargé en eau : remplacement complet du liquide et purge.', next: 'end_purge' }; } };
  F.assist = { type: 'measure', title: 'Assistance (servofrein)', why: '<p>Le servofrein utilise la <b>dépression</b> (collecteur d’admission en essence, <b>pompe à vide</b> en diesel) pour multiplier l’effort du pied. Test rapide : moteur arrêté, pompe plusieurs fois, garde le pied sur la pédale et démarre : la pédale doit <b>s’enfoncer légèrement</b>.</p>', how: '<p>Vacuomètre sur la durite du servofrein, moteur au ralenti.</p>', measures: ['dep_sv'],
    decide: function (m) { if (m('dep_sv').st === 'bad' && m('dep_sv').dir === 'low') return { v: 'bad', msg: 'Dépression insuffisante : pompe à vide, durite fendue ou clapet anti-retour du servofrein.', next: 'end_assist' }; return { v: 'ok', msg: 'Dépression correcte : si la pédale reste dure, le servofrein lui-même est défectueux (membrane, valve) — ou étriers grippés.', next: 'end_assist' }; } };
  F.tire = { type: 'info', title: 'Tire au freinage', html: '<p>Le véhicule tire du côté qui <b>freine le plus</b> : l’<b>autre côté</b> freine mal (cours : « tire à gauche = le côté droit freine mal »). Contrôle de ce côté : étrier / piston grippé, garnitures grasses ou vitrifiées, flexible gonflé ou obstrué. Confirme au <b>banc de freinage</b> (module DSFT).</p>', bouton: 'Terminer', next: 'end_tire' };
  F.abs = { type: 'choice', title: 'ABS : quel type de capteur de roue ?', why: '<p>Le calculateur ABS compare la vitesse des 4 roues. Un capteur (ou sa cible dentée / magnétique) en défaut allume le voyant ABS (et souvent ESP). <b>Capteur passif</b> = inductif 2 fils (génère une tension alternative). <b>Capteur actif</b> = 2 fils alimentés, signal en <b>courant</b> (≈ 7 / 14 mA), cible magnétique souvent dans le joint de roulement.</p>',
    choices: [['Capteur passif (inductif)', 'abs_pass'], ['Capteur actif', 'abs_act']] };
  F.abs_pass = { type: 'info', title: 'Capteur ABS passif (inductif)', html: '<p>Il se contrôle comme un capteur inductif : résistance du bobinage, isolement, tension alternative en tournant la roue, <b>entrefer</b> et état de la couronne dentée (dents cassées, encrassement). Utilise le module <b>🔌 Multiplexage → capteur inductif</b>.</p>', bouton: 'Terminer', next: 'end_abs' };
  F.abs_act = { type: 'measure', title: 'Capteur ABS actif', why: '<p>Le capteur actif module le <b>courant</b> qui le traverse : environ 7 mA et 14 mA en alternance quand la cible magnétique défile. On le mesure en série (ampèremètre) en tournant lentement la roue, ou à l’oscilloscope.</p>', how: '<p>Ampèremètre en série dans un des 2 fils (adaptateur), contact mis, roue tournée lentement à la main.</p>', measures: ['i_abs_lo', 'i_abs_hi'],
    decide: function (m) { if (m('i_abs_lo').st === 'ok' && m('i_abs_hi').st === 'ok') return { v: 'ok', msg: 'Le capteur commute correctement : contrôle le faisceau (continuité, isolement) et la cible magnétique (joint de roulement endommagé, bague aimantée), puis les autres roues.', next: 'end_abs' }; return { v: 'bad', msg: 'Pas de commutation correcte : capteur HS, cible magnétique absente ou roulement monté à l’envers (face magnétique côté capteur), ou alimentation absente.', next: 'end_abs' }; } };
  F.vib = { type: 'measure', title: 'Disques et garnitures', why: '<p>Des vibrations dans la pédale ou le volant au freinage viennent le plus souvent d’un <b>disque voilé</b> ou d’épaisseur irrégulière (dépôts de garniture). On contrôle aussi l’usure.</p>', how: '<ol><li>Comparateur sur le disque (roue serrée avec des écrous pour plaquer le disque), 1 tour : lis le voile.</li><li>Palmer : épaisseur du disque, compare à la cote mini gravée.</li><li>Épaisseur de garniture de la plaquette la plus usée.</li></ol>', measures: ['voile', 'marge_d', 'ep_plaq'],
    decide: function (m) { var bad = []; if (m('voile').st === 'bad') bad.push('voile trop important (vérifie d’abord la propreté du moyeu)'); if (m('marge_d').st === 'bad') bad.push('disque sous la cote mini'); if (m('ep_plaq').st === 'bad') bad.push('garnitures usées'); if (bad.length) return { v: 'bad', msg: bad.join(' ; ') + ' : remplace disques et / ou plaquettes par essieu.', next: 'end_disques' }; return { v: 'ok', msg: 'Disques et garnitures corrects : cherche un jeu (rotules, silentblocs, roulement) ou un étrier mal fixé.', next: 'end_disques' }; } };
  F.parc = { type: 'choice', title: 'Quel frein de stationnement ?', why: '<p>Au contrôle technique, le frein de stationnement doit atteindre <b>18 %</b> d’efficacité au banc.</p>', choices: [['À câble (levier)', 'end_parc_cable'], ['Électrique (bouton)', 'end_parc_elec']] };
  F.end_mc = end('bad', 'Maître-cylindre', '<p>Fuite interne (coupelles) : remplace le maître-cylindre, puis purge complète.</p>');
  F.end_fuite = end('bad', 'Fuite de liquide', '<p>Cherche la fuite : étriers, cylindres de roue, flexibles, canalisations, raccords, maître-cylindre (côté servofrein). Répare, remplis, purge. Des garnitures touchées par le liquide sont à remplacer.</p>');
  F.end_reglage = end('warn', 'Réglage ou air', '<p>Freins AR à tambour mal réglés (rattrapage automatique grippé), piston d’étrier non repoussé, ou air dans le circuit : réglage et purge.</p>');
  F.end_purge = end('warn', 'Purge / remplacement du liquide', '<p>Remplace le liquide (tous les 2 ans environ) et purge chaque roue dans l’ordre constructeur ; sur ABS, purge assistée à la valise si le bloc a été vidé.</p>');
  F.end_assist = end('warn', 'Assistance de freinage', '<p>Remplace l’élément défectueux (pompe à vide, durite, clapet, servofrein), puis contrôle la pédale moteur arrêté / moteur tournant.</p>');
  F.end_tire = end('warn', 'Côté qui freine mal', '<p>Répare l’étrier, les garnitures ou le flexible du côté qui freine le moins, par essieu, puis passage au banc.</p>');
  F.end_abs = end('warn', 'Capteur ou cible ABS', '<p>Remplace le capteur ou la cible (roulement), efface les défauts et fais un essai : le voyant doit s’éteindre au-delà de quelques km/h.</p>');
  F.end_disques = end('warn', 'Disques et plaquettes', '<p>Remplacement <b>par essieu</b>, nettoyage des moyeux, serrage au couple, rodage progressif.</p>');
  F.end_parc_cable = end('warn', 'Frein de stationnement à câble', '<p>Contrôle les câbles (grippés, détendus), le réglage au levier et les garnitures AR ; règle selon le nombre de crans constructeur. Vérifie au banc (≥ 18 %).</p>');
  F.end_parc_elec = end('warn', 'Frein de stationnement électrique', '<p>Lis les défauts à la valise ; pour changer les plaquettes, utilise le <b>mode maintenance</b> (ouverture des étriers) de la valise ; contrôle les moteurs d’étrier et leurs faisceaux, puis fais l’apprentissage.</p>');

  function add(id, icon, titre, sous, steps, comprendre) { D.MODULES[id] = { id: id, icon: icon, titre: titre, sous: sous, start: 'start', steps: steps, comprendre: comprendre }; }
  add('cr', '⛽', 'Moteur diesel common rail', 'Démarrage, basse et haute pression, injecteurs, suralimentation', C,
    '<h3>Le principe</h3><p>Une <b>pompe de gavage</b> alimente la <b>pompe HP</b>, qui remplit la <b>rampe commune</b> (jusqu’à plus de 1 600 bar). Le calculateur régule la pression (régulateur de débit et / ou de pression, capteur de rail) et commande les <b>injecteurs</b> (solénoïde ou piézo). Le débit injecté dépend du <b>temps d’ouverture</b>, de la <b>pression de rail</b> et de la section des trous.</p>' +
    '<div class="tw"><table><tr><th>Élément</th><th>Contrôle</th><th>Valeur type</th></tr><tr><td>Pression de rail au démarreur</td><td>Valise</td><td>≈ 200 bar (cours)</td></tr><tr><td>Capteur de rail</td><td>Tension</td><td>0,5 V contact mis ; 1 à 1,5 V au démarreur</td></tr><tr><td>Gavage électrique</td><td>Manomètre</td><td>3 à 8 bar selon système</td></tr><tr><td>Retours injecteurs</td><td>Éprouvettes</td><td>≈ 22 ml / 3 min (Bosch) — comparer entre eux</td></tr></table></div>' +
    '<div class="box piege"><b>⚠️ Sécurité</b><ul><li>Ne jamais desserrer un raccord HP moteur tournant (jet sous plusieurs centaines de bar : pénétration sous la peau).</li><li>Propreté absolue : bouchons sur tous les orifices ouverts.</li><li>Après ouverture du circuit HP, tuyaux HP neufs selon constructeur.</li></ul></div>');
  add('anti', '🌫️', 'Antipollution', 'FAP, EGR, SCR / AdBlue, sonde lambda et catalyseur', P,
    '<h3>Les systèmes</h3><div class="tw"><table><tr><th>Système</th><th>Rôle</th><th>Contrôle clé</th></tr><tr><td>EGR</td><td>Baisser les NOx en renvoyant des gaz à l’admission</td><td>Position demandée / mesurée</td></tr><tr><td>FAP</td><td>Piéger les particules, régénération vers 600 °C</td><td>Pression différentielle (5 à 20 mbar au ralenti)</td></tr><tr><td>SCR</td><td>Réduire les NOx avec l’ammoniac de l’AdBlue (32,5 % d’urée)</td><td>Concentration, T° cata > 180 °C, NOx amont / aval, test du doseur</td></tr><tr><td>Lambda / catalyseur (essence)</td><td>Rester à λ = 1, oxyder CO et HC, réduire les NOx</td><td>Oscillation 0,1 ↔ 0,9 V amont, aval stable</td></tr></table></div>');
  add('dsft', '📐', 'DSFT : géométrie, pneus, banc de freinage', 'Relevé de géométrie, usure des pneus, véhicule qui tire, banc de freinage', G,
    '<h3>Rappels</h3><ul><li><b>Usure rugueuse</b> = parallélisme ; <b>usure lisse</b> = carrossage.</li><li><b>Angle inclus</b> (pivot + carrossage) : bon → triangle, berceau, châssis ; pas bon → fusée, porte-fusée, jambe de force.</li><li>Le véhicule tire du côté du <b>carrossage le plus positif</b> et de la <b>chasse la plus faible</b>.</li><li>Ordre de réglage : hauteur de caisse → chasse → pivot → carrossage → hauteur de crémaillère → <b>parallélisme en dernier</b>.</li><li>Banc de freinage : efficacité ≥ 50 % (service) et ≥ 18 % (stationnement) ; déséquilibre > 30 % = défaillance majeure.</li></ul>');
  add('frein', '🛑', 'Freinage', 'Type de circuit, pédale, assistance, ABS, disques, frein de stationnement', F,
    '<h3>Le circuit hydraulique</h3><p>Le <b>maître-cylindre tandem</b> alimente deux circuits indépendants, montés <b>en X</b> (diagonale) ou <b>en H</b> (AV / AR). Le <b>servofrein</b> multiplie l’effort grâce à la dépression. L’<b>ABS</b> module la pression de chaque roue pour éviter le blocage (stabilité, directibilité, efficacité) ; l’<b>ESP</b> freine une roue pour corriger la trajectoire.</p><div class="box piege"><b>⚠️ Pièges</b><ul><li>Le liquide de frein absorbe l’eau : à remplacer régulièrement.</li><li>Garnitures toujours remplacées <b>par essieu</b>.</li><li>Frein de stationnement électrique : mode maintenance à la valise avant de repousser les pistons.</li></ul></div>');

  /* utilitaire partagé avec la conclusion DSFT */
  function deg(n) { var sg = n < 0 ? '−' : '', a = Math.abs(n), d = Math.floor(a), mm = Math.round((a - d) * 60); if (mm === 60) { d++; mm = 0; } return sg + d + '°' + (mm < 10 ? '0' : '') + mm + '′'; }
})();
